GCC_MAJOR_VERSION = 3
GCC_MINOR_VERSION = 4
GCC_TEENY_VERSION = 5
GCC_EXTRA_VERSION =

GCC_VERSION = $(strip $(if $(GCC_EXTRA_VERSION), \
	$(GCC_MAJOR_VERSION).$(GCC_MINOR_VERSION)-$(GCC_EXTRA_VERSION), \
	$(GCC_MAJOR_VERSION).$(GCC_MINOR_VERSION).$(GCC_TEENY_VERSION)))

GCC_DIR = \
	$(DESTDIR)$(libdir)/gcc/$(GARHOST)/$(GARTARGET)/$(GCC_MAJOR_VERSION).$(GCC_MINOR_VERSION).$(GCC_TEENY_VERSION)
GCC_LIBDIR = \
	$(GCC_DIR)
GCC_INCLUDEDIR = \
	$(GCC_DIR)/include

CROSS_GCC_DIR = \
	$(build_DESTDIR)$(build_libdir)/gcc/$(GARTARGET)/$(GCC_MAJOR_VERSION).$(GCC_MINOR_VERSION).$(GCC_TEENY_VERSION)
CROSS_GCC_LIBDIR = \
	$(CROSS_GCC_DIR)
CROSS_GCC_INCLUDEDIR = \
	$(CROSS_GCC_DIR)/include
