#!/bin/sh

# Change the read-only root file system into a read-write root file system.
/bin/mount -n -t tmpfs none /rw
/bin/mkdir -p /rw/rootfs
/bin/mount -n -t unionfs -o dirs=/rw/rootfs=rw:/rootfs-ro=ro none /rootfs
cd /rootfs
/bin/mkdir -p initrd
/sbin/pivot_root . initrd

if /usr/bin/test -z "${MM_INIT_TYPE}" ; then
    MM_INIT_TYPE='perl'
fi

# Save boot line options that we need later.
/bin/mkdir -p /etc/conf.d/
set | /bin/grep -e '^BOOT_IMAGE=' >> /etc/conf.d/boot
set | /bin/grep -e '^initrd='     >> /etc/conf.d/boot
set | /bin/grep -e '^MM_'         >> /etc/conf.d/boot

if   /usr/bin/test ${MM_INIT_TYPE} = 'perl'        ; then
    /bin/ln -s /etc/inittab.perl /etc/inittab
elif /usr/bin/test ${MM_INIT_TYPE} = 'sh.obsolete' ; then
    /bin/ln -s /etc/inittab.sh   /etc/inittab
else
    /bin/echo "error: MM_INIT_TYPE=${MM_INIT_TYPE} is invalid."
    exit 1
fi

# Change root to the read-write root file system and start the real init.
exec /usr/sbin/chroot . ./bin/sh -c 'exec /sbin/init' <dev/console >dev/console 2>&1
