#!/bin/sh
################################################################################
# dev.script
################################################################################
[ -n "`mm_var_get MM_DEBUG`" ] && set -x

mount -t ramfs  none /dev

mknod -m 600 /dev/console c 5 1
mknod -m 640 /dev/mem     c 1 1
mknod -m 666 /dev/null    c 1 3
mknod -m 666 /dev/ptmx    c 5 2
mknod -m 666 /dev/random  c 1 8
mknod -m 666 /dev/tty     c 5 0
mknod -m 660 /dev/tty0    c 4 0
mknod -m 660 /dev/tty1    c 4 1
mknod -m 660 /dev/tty2    c 4 2
mknod -m 444 /dev/urandom c 1 9
mknod -m 666 /dev/zero    c 1 5

ln -s /proc/kcore     /dev/core
ln -s /proc/self/fd   /dev/fd
ln -s /proc/self/fd/0 /dev/stdin
ln -s /proc/self/fd/1 /dev/stdout
ln -s /proc/self/fd/2 /dev/stderr

mkdir /dev/pts
mount -t devpts none /dev/pts

mkdir /dev/shm
mount -t tmpfs  none /dev/shm

echo "/sbin/udev" > /proc/sys/kernel/hotplug

udevstart
