#!/bin/sh
################################################################################
# web.script
################################################################################
[ -n "`mm_var_get MM_DEBUG`" ] && set -x

case $1 in
    start)
        # Start web server daemon.
        webfsd -u 0 -g 0 -p 80 -f index.html -r /srv/www -x /cgi-bin -s
        ;;
    stop)
        if [ -n "`pidof webfsd`" ] ; then
            killall webfsd
        fi
        ;;
esac

exit 0
