GARNAME        = perl-DBD-mysql
GARVERSION     = 4.021
MASTER_SITES   = http://www.cpan.org/authors/id/C/CA/CAPTTOFU/
DEPENDS        = db/mariadb perl/perl-DBI
PERL_MODULE_SO = true

include ../../perl/perl/perl-module.mk
