#!/bin/sh
################################################################################
# mm_audio
#
# Arguments:
#     name        : The name of the audio device. Use %k.
#     audio_card  : The audio card. Using %i should work.
#     audio_device: The audio device number that supports audio playback.
################################################################################

. /lib/minimyth/mm_detect

name=$1
audio_card=$2
audio_device=$3

case "${ACTION}" in
    add)
        if /usr/bin/test -z "${name}" ; then
            exit 0
        fi

        mm_detect_state_put 'audio' 'automatic' "${name}" "${audio_card},${audio_device}"
        ;;
    remove)
        if /usr/bin/test -z "${name}" ; then
            exit 0
        fi

        mm_detect_state_delete 'audio' 'automatic' "${name}"
        ;;
esac

exit 0
