#!/bin/sh
################################################################################
# mm_detect
#
# This is a wrapper that calls functions in /lib/minimyth/mm_detect on behalf
# of udev.
################################################################################

. /lib/minimyth/mm_detect

group=$1
name=$2
state=$3

if /usr/bin/test -z "${group}" || /usr/bin/test -z "${name}"  ; then
    exit 1
fi

case "${ACTION}" in
    add)    mm_detect_state_put    "${group}" 'automatic' "${name}" "${state}" ;;
    remove) mm_detect_state_delete "${group}" 'automatic' "${name}"            ;;
esac

exit 0
