#!/bin/sh
################################################################################
# mm_detect
#
#
################################################################################

. /lib/minimyth/mm_detect

group=$1
name=$2
state=$3

case "${ACTION}" in
    add)
        if /usr/bin/test -z "${name}" ; then
            exit 0
        fi

        mm_detect_state_put "${group}" 'automatic' "${name}" "${state}"
        ;;
    remove)
        if /usr/bin/test -z "${name}" ; then
            exit 0
        fi

        mm_detect_state_delete "${group}" 'automatic' "${name}"
        ;;
esac

exit 0
