#!/bin/sh

. /lib/minimyth/mm_lirc

name="${1}"
driver="${2}"
remote="${3}"

device="${DEVNAME}"

case "${ACTION}" in
    add)
        if /usr/bin/test -z "${name}"   || \
           /usr/bin/test -z "${device}" || \
           /usr/bin/test -z "${driver}" ; then
            exit 0
        fi

        wakeup=
        if /usr/bin/test -r /proc/acpi/wakeup ; then
            physical_path=
            if /usr/bin/test -e "/sys/${DEVPATH}/device" ; then
                 physical_path=`/usr/bin/readlink -f "/sys/${DEVPATH}/device"`
                 physical_path=`/usr/bin/dirname "${physical_path}"`
                 physical_path=`/usr/bin/dirname "${physical_path}"`
                 if /usr/bin/test -e "${physical_path}/subsystem" ; then
                     bus_type=`/usr/bin/readlink -f "${physical_path}/subsystem"`
                     bus_type=`/usr/bin/basename "${bus_type}"`
                     bus_device=`/usr/bin/basename "${physical_path}"`
                     if /usr/bin/test -n "${bus_type}" && /usr/bin/test -n "${bus_device}" ; then
                         wakeup=`/bin/cat /proc/acpi/wakeup                 \
                             | /bin/grep -e " ${bus_type}:${bus_device}\$"  \
                             | /bin/sed -e 's%  *% %g'                      \
                             | /usr/bin/cut -d ' ' -f 1`
                     fi
                 fi
            fi
        fi

        mm_lirc_state_put 'automatic' "${name}" "${device}" "${driver}" "${remote}" "${wakeup}"
        ;;
    remove)
        if /usr/bin/test -z "${name}"   ; then
            exit 0
        fi

        mm_lirc_state_delete 'automatic' "${name}"
        ;;
esac

exit 0
