GARNAME         = perl-IO-Compress-Zlib
GARVERSION      = 2.008
MASTER_SITES    = http://www.cpan.org/authors/id/P/PM/PMQS/
DEPENDS         = perl/perl-IO-Compress-Base
PERL_NOT_NEEDED = 5.10.0

include ../../perl/perl/perl-module.mk
