#!/bin/sh
################################################################################
# mm_lcdproc
#
# LCDproc related functions.
################################################################################
. /lib/minimyth/mm_state

mm_lcdproc_state_get() {
    local type="$1"

    mm_state_get 'lcdproc' "${type}"
}

mm_lcdproc_state_put() {
    local type="$1"
    local device="$2"
    local driver="$3"

    local state

    if /usr/bin/test -n "${device}" ; then
        state="${device},${driver}"

        mm_state_put 'lcdproc' "${type}" "${device}" "${state}"
    fi
}

mm_lcdproc_state_delete() {
    local type="$1"
    local device="$2"

    if /usr/bin/test -n "${device}" ; then
        mm_state_delete 'lcdproc' "${type}" "${device}"
    fi
}
