GARNAME      = perl-DateTime-TimeZone
GARVERSION   = 1.23
MASTER_SITES = http://www.cpan.org/authors/id/D/DR/DROLSKY/
DEPENDS      = perl/perl-Class-Singleton perl/perl-Params-Validate

include ../../perl/perl/perl-module.mk
