GARNAME           = perl-DateTime-TimeZone
GARVERSION        = 1.27
MASTER_SITES      = http://www.cpan.org/authors/id/D/DR/DROLSKY/
PERL_MODULE_STYLE = Build.PL
DEPENDS           = perl/perl-Class-Load perl/perl-Class-Singleton perl/perl-Params-Validate

include ../../perl/perl/perl-module.mk
