LINUX_HEADERS_MAJOR_VERSION = 2
LINUX_HEADERS_MINOR_VERSION = 6
LINUX_HEADERS_TEENY_VERSION = 26
LINUX_HEADERS_EXTRA_VERSION = .6

LINUX_HEADERS_VERSION = $(LINUX_HEADERS_MAJOR_VERSION).$(LINUX_HEADERS_MINOR_VERSION).$(LINUX_HEADERS_TEENY_VERSION)$(LINUX_HEADERS_EXTRA_VERSION)
LINUX_HEADERS_FULL_VERSION = $(LINUX_HEADERS_VERSION)
