#!/bin/sh

if /usr/bin/test ! -e /var/cache/minimyth/init/conf/MM_FIRMWARE_FILE_LIST ; then
    if /sbin/modprobe --show-depends $MODALIAS | /bin/grep -q '/firmware_class.ko' 2> /dev/null ; then
        exit 0
    fi
fi

exit 1
