#!/bin/sh
################################################################################
# mm_lircd
################################################################################

case "${ACTION}" in
    add)
        if /usr/bin/test "x${lircd_driver}" = "x" ; then
            exit 1;
        fi
        if /usr/bin/test "x${lircd_conf}" = "x" ; then
            exit 1;
        fi
        if /usr/bin/test ! -e '/var/run/lirc' ; then
            /bin/mkdir -p '/var/run/lirc'
        fi
        instance=`/bin/echo $DEVNAME | /bin/sed -e 's/\/\+/~/g' -e 's/^~dev~//'`;
        if /usr/bin/test ! -e "/var/run/lirc/lircd-${instance}.pid" ; then
            daemon='/usr/sbin/lircd'
            daemon="${daemon} --uinput"
            daemon="${daemon} --device=${DEVNAME}"
            daemon="${daemon} --driver=${lircd_driver}"
            daemon="${daemon} --output=/var/run/lirc/lircd-${instance}"
            daemon="${daemon} --pidfile=/var/run/lirc/lircd-${instance}.pid"
            daemon="${daemon} ${lircd_conf}"
            ${daemon}
        fi
        ;;
    remove)
        instance=`/bin/echo $DEVNAME | /bin/sed -e 's/\/\+/~/g' -e 's/^~dev~//'`;
        if /usr/bin/test -e "/var/run/lirc/lircd-${instance}.pid" ; then
            pid=`/bin/cat /var/run/lirc/lircd-${instance}.pid`
            if /usr/bin/test ! "x${pid}" = "x" ; then
                /bin/kill ${pid}
            fi
        fi
        ;;
esac

exit 0
