#!/bin/sh
################################################################################
# mm_lirc_wakeup_enable
################################################################################

devpath=`/usr/bin/readlink -f "${DEVPATH}"`
while /usr/bin/test ! "x${devpath}" = "x" && /usr/bin/test ! "x${devpath}" = "x/sys" ; do
    if /usr/bin/test -e "${devpath}/power/wakeup" ; then                                 
        state=`/bin/cat "${devpath}/power/wakeup"`                                       
        if /usr/bin/test "x${state}" = "xdisabled" ; then
            /bin/echo "enabled" > "${devpath}/power/wakeup"
        fi                                                 
    fi                                                     
    devpath=`/usr/bin/dirname "${devpath}"`
done                                       
                                           
exit 0
