#!/bin/sh

. /etc/minimyth.d/env.script

box() {
    return 0;
}

rc_progress_update() {
    progress=$((progress + 1))
    if [ -e "/var/cache/splash/fifo" ] ; then
        echo "progress $(( 65535 * $progress / $progress_max ))" >> /var/cache/splash/fifo
        echo "repaint"                                           >> /var/cache/splash/fifo
    fi
}

rc_command_run() {
    COMMAND="$1"
    MESSAGE="$2"
    mm_message_output info "${MESSAGE}"
    mm_command_run "${COMMAND}"
    if [ $? != 0 ] ; then
        exit $?
    fi
    rc_progress_update
}

case $1 in
    # init
    1|2|3|4|5)
        progress=0
        progress_max=18
        mm_command_run "sh /etc/minimyth.d/init.script     start"
        mm_command_run "sh /etc/minimyth.d/fs.script       start"
        mm_command_run "sh /etc/minimyth.d/log.script      start"
        mm_command_run "sh /etc/minimyth.d/splash.script   start"
        rc_command_run "sh /etc/minimyth.d/ld.script       start" 'configuring shared libraries ...'
        rc_command_run "sh /etc/minimyth.d/network.script  start" 'starting network ...'
        rc_command_run "sh /etc/minimyth.d/log.script      start" 'starting system logging ...'
        rc_command_run "sh /etc/minimyth.d/telnet.script   start" 'starting telnet server ...'
        rc_command_run "sh /etc/minimyth.d/core.script     start" 'fetching user configuration ...'
        rc_command_run "sh /etc/minimyth.d/minimyth.script      " 'running user script ...'
        rc_command_run "sh /etc/minimyth.d/modules.script  start" 'loading kernel modules ...'
        rc_command_run "sh /etc/minimyth.d/mythtv.script   start" 'configuring mythtv ...'
        rc_command_run "sh /etc/minimyth.d/extras.script   start" 'installing extras ...'
        rc_command_run "sh /etc/minimyth.d/sensors.script  start" 'starting sensors ...'
        rc_command_run "sh /etc/minimyth.d/acpi.script     start" 'starting ACPI ...'
        rc_command_run "sh /etc/minimyth.d/time.script     start" 'starting NTP client ...'
        rc_command_run "sh /etc/minimyth.d/web.script      start" 'starting web server ...'
        rc_command_run "sh /etc/minimyth.d/mount.script    start" 'mounting media shares ...'
        rc_command_run "sh /etc/minimyth.d/audio.script    start" 'configuring audio ...'
        rc_command_run "sh /etc/minimyth.d/video.script    start" 'configuring video ...'
        rc_command_run "sh /etc/minimyth.d/lirc.script     start" 'starting remote control ...'
        rc_command_run "sh /etc/minimyth.d/x.script        start" 'starting X ...'
        mm_command_run "sh /etc/minimyth.d/splash.script   stop "
        ;;
    # halt and reboot.
    0|6)
        progress=0
        progress_max=6
        mm_command_run "sh /etc/minimyth.d/splash.script   start"
        rc_command_run "sh /etc/minimyth.d/x.script        stop " 'stopping X ...'
        rc_command_run "sh /etc/minimyth.d/mount.script    stop " 'unmounting media shares ...'
        rc_command_run "sh /etc/minimyth.d/web.script      stop " 'stopping web server ...'
        rc_command_run "sh /etc/minimyth.d/time.script     stop " 'stopping NTP client ...'
        rc_command_run "sh /etc/minimyth.d/telnet.script   stop " 'stopping telnet server ...'
        rc_command_run "sh /etc/minimyth.d/shutdown.script $1   " 'finishing shutdown ...'
        ;;
esac
