GARNAME      = perl-XML-SAX
GARVERSION   = 0.16
MASTER_SITES = http://www.cpan.org/authors/id/G/GR/GRANTM/
DEPENDS      = perl/perl-File-Temp perl/perl-XML-NamespaceSupport

include ../../perl/perl/perl-module.mk

CONFIGURE_ENV := echo Y | $(CONFIGURE_ENV)

PARALLELMFLAGS := -j1
