#!/bin/sh

. /etc/minimyth.d/env.script

box() {
    return 0;
}

rc_progress_update() {
    progress=$((progress + 1))
    if [ -e "/var/cache/splash/fifo" ] ; then
        echo "progress $(( 65535 * $progress / $progress_max ))" >> /var/cache/splash/fifo
        echo "repaint"                                           >> /var/cache/splash/fifo
    fi
}

rc_command_run() {
    COMMAND="$1"
    MESSAGE="$2"
    mm_message_output info "${MESSAGE}"
    mm_command_run "${COMMAND}"
    if [ $? != 0 ] ; then
        exit $?
    fi
    rc_progress_update
}

progress=0
progress_max=18
mm_command_run 'sh /etc/minimyth.d/fs.script'
mm_command_run 'sh /etc/minimyth.d/log.script'
mm_command_run 'sh /etc/minimyth.d/splash.script start'
rc_command_run 'sh /etc/minimyth.d/ld.script'           'configuring shared libraries ...'
rc_command_run 'sh /etc/minimyth.d/network.script'      'starting network ...'
rc_command_run 'sh /etc/minimyth.d/log.script'          'starting system logging ...'
rc_command_run 'sh /etc/minimyth.d/telnet.script'       'starting telnet server ...'
rc_command_run 'sh /etc/minimyth.d/core.script'         'fetching user configuration ...'
rc_command_run 'sh /etc/minimyth.d/minimyth.script'     'running user script ...'
rc_command_run 'sh /etc/minimyth.d/modules.script'      'loading kernel modules ...'
rc_command_run 'sh /etc/minimyth.d/mythtv.script'       'configuring mythtv ...'
rc_command_run 'sh /etc/minimyth.d/extras.script'       'installing extras ...'
rc_command_run 'sh /etc/minimyth.d/sensors.script'      'starting sensors ...'
rc_command_run 'sh /etc/minimyth.d/acpi.script'         'starting ACPI ...'
rc_command_run 'sh /etc/minimyth.d/time.script'         'starting NTP client ...'
rc_command_run 'sh /etc/minimyth.d/web.script'          'starting web server ...'
rc_command_run 'sh /etc/minimyth.d/mount.script'        'mounting media shares ...'
rc_command_run 'sh /etc/minimyth.d/audio.script'        'configuring audio ...'
rc_command_run 'sh /etc/minimyth.d/video.script'        'configuring video ...'
rc_command_run 'sh /etc/minimyth.d/lirc.script'         'starting remote control ...'
rc_command_run 'sh /etc/minimyth.d/x.script start'      'starting X ...'
mm_command_run 'sh /etc/minimyth.d/splash.script stop'
