#!/bin/sh
################################################################################
# firmware
################################################################################
. /etc/rc.d.sh/functions

start() {

    if /usr/bin/test -e '/lib/firmware' ; then
        mm_message_output info "loading kernel module firmware ..."

        # Enable firmware loading udev rules.
        /bin/mv -f /lib/udev/rules.d/06-minimyth-firmware.rules.disabled /lib/udev/rules.d/06-minimyth-firmware.rules

        # Trigger udev with the additional udev rules that handle firmware loading.
        /sbin/udevadm trigger
        /sbin/udevadm settle --timeout=60
    fi

    return 0
}

stop() {

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
