#!/bin/sh
################################################################################
# gtk
################################################################################
. /etc/rc.d.sh/functions

start() {

    mm_message_output info "configuring GTK ..."

    if /usr/bin/test -e '/usr/bin/gdk-pixbuf-query-loaders' ; then
        if /usr/bin/test ! -e '/etc/gtk-2.0' ; then
            /bin/mkdir '/etc/gtk-2.0'
        fi
        /bin/chmod 0755 '/etc/gtk-2.0'
        /usr/bin/gdk-pixbuf-query-loaders > '/etc/gtk-2.0/gdk-pixbuf.loaders'
        /bin/chmod 0644 '/etc/gtk-2.0/gdk-pixbuf.loaders'
    fi

    return 0
}

stop() {

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
