#!/bin/sh
################################################################################
# lirc
#
# This script configures and starts LIRC.
################################################################################
. /etc/rc.d.sh/functions

# Find USB devices associated with each LIRC device and enable ACPI wakeup.
remote_wakeup_enable() {
    local device_list="$1"

    local devpath
    local lirc_list
    local lirc
    local name
    local busnum
    local serial
    local entry
    local device
    local status

    if /usr/bin/test ! -r "/sys/class/lirc" ; then
        return
    fi
    lirc_list=`cd /sys/class/lirc ; ls -1`
    
    for lirc in ${lirc_list} ; do
        if /usr/bin/test -z "${lirc}" ; then
            continue
        fi

        name=`/sbin/udevadm info --query=name --root --path=/sys/class/lirc/${lirc}`
        /bin/echo " ${device_list}" | grep -q " ${name},"
        if /usr/bin/test $? -ne 0 ; then
            continue
        fi

        devpath=`/usr/bin/readlink -f "/sys/class/lirc/${lirc}/device"`
        devpath=`/usr/bin/dirname "${devpath}"`
        devpath=`/usr/bin/dirname "${devpath}"`

        if /usr/bin/test ! -r "${devpath}/busnum" ; then
            continue
        fi
        busnum=`/bin/cat "${devpath}/busnum" 2> /dev/null`
        if /usr/bin/test $? -ne 0 || /usr/bin/test -z "${busnum}" ; then
            continue
        fi
    
        if /usr/bin/test ! -r "${devpath}/subsystem/devices/usb${busnum}/serial" ; then
            continue
        fi
        serial=`/bin/cat "${devpath}/subsystem/devices/usb${busnum}/serial"`
        if /usr/bin/test $? -ne 0 || /usr/bin/test -z "${serial}" ; then
            continue
        fi

        if /usr/bin/test ! -r "/proc/acpi/wakeup" ; then
            continue
        fi
        entry=`/bin/cat /proc/acpi/wakeup | /bin/grep -e "${serial}\$" | /bin/sed -e 's%  *% %g'`
        if /usr/bin/test $? -ne 0 || /usr/bin/test -z "${entry}" ; then
            continue
        fi

        device=`/bin/echo ${entry} | /usr/bin/cut -d ' ' -f 1`
        if /usr/bin/test $? -ne 0 || /usr/bin/test -z "${device}" ; then
            continue
        fi

        status=`/bin/echo ${entry} | /usr/bin/cut -d ' ' -f 3`
        if /usr/bin/test $? -ne 0 || /usr/bin/test -z "${status}" ; then
            continue
        fi

        if /usr/bin/test ! -w "/proc/acpi/wakeup" ; then
            continue
        fi
        if /usr/bin/test ! "${status}" = "enabled" ; then
            /bin/echo ${device} > /proc/acpi/wakeup
            if /usr/bin/test $? -ne 0 ; then
                continue
            fi
        fi
    done
}

start() {

    local application_path
    local daemon
    local daemon_master
    local delay
    local device
    local device_count
    local device_item
    local driver
    local file
    local index
    local instance
    local lircd_conf
    local map

    # Count the LIRC devices.
    device_count=0
    for device_item in ${MM_LIRC_DEVICE_LIST} ; do
        device_count=$((${device_count}+1))
    done

    # There are no remote control devices, so there is no need to continue.
    if /usr/bin/test ${device_count} -eq 0 ; then
        return
    fi

    mm_message_output info "starting remote control(s) ..."

    # Load user configured kernel module.
    if /usr/bin/test -n "${MM_LIRC_KERNEL_MODULE}" ; then
        /sbin/modprobe ${MM_LIRC_KERNEL_MODULE} ${MM_LIRC_KERNEL_MODULE_OPTIONS}
        # Wait up to 60 seconds for the device to appear in the device file system.
        delay=0
        while /usr/bin/test ! -e ${MM_LIRC_DEVICE} && /usr/bin/test ${delay} -lt 60 ; do
            /bin/sleep 1
            delay=$((delay + 1))
            mm_message_output info "waiting for remote control device (${delay} seconds) ..."
        done
        if /usr/bin/test ! -e ${MM_LIRC_DEVICE} ; then
            mm_message_output err "error: timed out waiting for remote control device."
            exit 1
        fi
    fi

    # Determine master LIRC daemon.
    # The master LIRC daemon combines the LIRC daemons for multiple LIRC devices.
    # Therefore, if there is more than one LIRC device, then we need a master LIRC daemon.
    daemon_master=
    if /usr/bin/test ${device_count} -gt 1 ; then
        daemon_master="/usr/sbin/lircd"
        daemon_master="${daemon_master} --driver=null"
        daemon_master="${daemon_master} --output=/dev/lircd --pidfile=/var/run/lircd.pid"
        index=1
        while /usr/bin/test ${index} -le ${device_count} ; do
            daemon_master="${daemon_master} --connect=localhost:$((8765 + ${index} - 1))"
            index=$((${index} + 1))
        done
    fi

    # If there is no lircd.conf file, then create it.
    if /usr/bin/test ! -e /etc/lircd.conf ; then
        /bin/rm -rf /tmp/lircd.conf.$$
        /bin/touch /tmp/lircd.conf.$$
        for file in `/bin/ls -d /etc/lirc.d/lircd.conf/* 2> /dev/null` ; do
            if /usr/bin/test -f "${file}" ; then
                /bin/echo "include <${file}>" >> /tmp/lircd.conf.$$
            fi
        done
        /bin/echo "# autogenerated" >> /etc/lircd.conf
        /bin/cat /tmp/lircd.conf.$$ | /usr/bin/sort >> /etc/lircd.conf
        /bin/rm -rf /tmp/lircd.conf.$$
    fi

    # If there is no lircrc file, then create it.
    if /usr/bin/test ! -e /etc/lircrc ; then
        /bin/rm -rf /tmp/lircrc.$$
        /bin/touch /tmp/lircrc.$$
        for application_path in `/bin/ls -d /etc/lirc.d/lircrc/* 2> /dev/null` ; do
            if   /usr/bin/test -f "${application_path}" ; then
                /bin/echo "include ${application_path}" >> /tmp/lircrc.$$
            elif /usr/bin/test -d "${application_path}" ; then
                for file in `/bin/ls -d ${application_path}/* 2> /dev/null` ; do
                    if /usr/bin/test -f "${file}" ; then
                        /bin/echo "include ${file}" >> /tmp/lircrc.$$
                    fi
                done
                if /usr/bin/test "${MM_LIRC_SLEEP_ENABLED}" = "yes" ; then
                    if /usr/bin/test -f "${application_path}/optional/key.power.sleep" ; then
                        /bin/echo "include ${application_path}/optional/key.power.sleep" >> /tmp/lircrc.$$
                    fi
                fi
                if /usr/bin/test "${MM_EXTERNAL_VOLUME_ENABLED}" = "yes" ; then
                    if /usr/bin/test -f "${application_path}/optional/key.volume.external" ; then
                        /bin/echo "include ${application_path}/optional/key.volume.external" >> /tmp/lircrc.$$
                    fi
                else
                    if /usr/bin/test -f "${application_path}/optional/key.volume.internal" ; then
                        /bin/echo "include ${application_path}/optional/key.volume.internal" >> /tmp/lircrc.$$
                    fi
                fi
            fi
        done
        /bin/echo "# autogenerated" >> /tmp/lircrc
        /bin/cat /tmp/lircrc.$$ | /usr/bin/sort >> /etc/lircrc
        /bin/rm -rf /tmp/lircrc.$$
    fi

    # Create directories used by the LIRC daemon.
    /bin/mkdir -p /var/lock
    /bin/mkdir -p /var/run

    # Start an LIRC daemon for each device.
    index=1
    for device_item in ${MM_LIRC_DEVICE_LIST} ; do
        device=`/bin/echo ${device_item} | /usr/bin/cut -d ',' -f1`
        driver=`/bin/echo ${device_item} | /usr/bin/cut -d ',' -f2`
        lircd_conf=`/bin/echo ${device_item} | /usr/bin/cut -d ',' -f3`

        # Convert driver to the the lirc daemon appropriate driver.
        if /usr/bin/test -n "${driver}" ; then
            driver=`/usr/sbin/lircd --driver=help 2>&1 | /bin/sed -e 's%[[:cntrl:]]%%g' | /bin/grep -i -e "^${driver}$"`
            if /usr/bin/test -z "${driver}" ; then
                driver="default"
            fi
        fi

        # Start daemon.
        daemon=
        instance=${device}
        for symlink in `/sbin/udevadm info --query=symlink --root --name="${device}"` ; do
            if /bin/echo "${symlink}" | grep -q -e '^/dev/persistent' > /dev/null 2>&1 ; then
                instance=${symlink}
            fi
        done
        instance=`/bin/echo ${instance} | /bin/sed -e 's%//*%~%g' | /bin/sed -e 's%^~dev~%%'`
        if /usr/bin/test -n "${daemon_master}" ; then
            daemon="/usr/sbin/lircd"
            daemon="${daemon} --device=${device} --driver=${driver}"
            daemon="${daemon} --output=/dev/lircd-${instance} --pidfile=/var/run/lircd-${instance}.pid"
            daemon="${daemon} --listen=$((8765 + ${index} - 1))"
            daemon="${daemon} ${lircd_conf}"
        else
            daemon="/usr/sbin/lircd"
            daemon="${daemon} --device=${device} --driver=${driver}"
            daemon="${daemon} --output=/dev/lircd --pidfile=/var/run/lircd.pid"
            daemon="${daemon} ${lircd_conf}"
            /bin/ln -s lircd /dev/lircd-${instance}
        fi
        /usr/bin/logger -t minimyth -p "local0.info" "started '${daemon}'."
        ${daemon}

        index=$((${index} + 1))
    done

    # Start master LIRC daemon.
    if /usr/bin/test -n "${daemon_master}" ; then
        ${daemon_master}
    fi

    # Auto-configure usage of 'irexec'.
    if /usr/bin/test "${MM_LIRC_IREXEC_ENABLED}" = "auto" ; then
        /usr/bin/logger -t minimyth -p "local0.info" "attempting to auto-configure usage of 'irexec'."
        MM_LIRC_IREXEC_ENABLED='no'
        if /usr/bin/test -e /etc/lircrc ; then
            # Only one level of includes is supported.
            lircrc_files="/etc/lircrc `/bin/cat /etc/lircrc | /bin/grep -e '^include ' | /bin/sed -e 's%^include *%%'`"
            for lircrc_file in ${lircrc_files} ; do
                if /bin/cat ${lircrc_file} | /bin/grep -q -e '^ *prog *= *irexec' ; then
                    MM_LIRC_IREXEC_ENABLED='yes'
                fi
           done
        fi
        /usr/bin/logger -t minimyth -p "local0.info" "auto-configured usage of 'irexec' as '${MM_LIRC_IREXEC_ENABLED}'."
    fi

    # Start the irexec daemon.
    if /usr/bin/test "${MM_LIRC_IREXEC_ENABLED}" = "yes" ; then
        /usr/bin/irexec -d /etc/lircrc
    fi

    # Enable wakeup on remote.
    if /usr/bin/test "${MM_LIRC_WAKEUP_ENABLED}" = "yes" ; then
        remote_wakeup_enable "${MM_LIRC_DEVICE_LIST}"
    fi
}

stop() {
    mm_message_output info "stopping remote control ..."

    /usr/bin/test -n "`/bin/pidof irexec`" && /usr/bin/killall irexec 
    /usr/bin/test -n "`/bin/pidof lircd`"  && /usr/bin/killall lircd
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
