#!/bin/sh
################################################################################
# time
################################################################################
. /etc/rc.d.sh/functions

start() {

    local NTP_SERVER
    local NTP_SERVERS
    local NTP_SUCCESS

    # Set time.
    mm_message_output info "setting time ..."
    NTP_SERVERS=`/bin/cat /etc/ntp.conf | /bin/grep '^server ' | /bin/sed 's%^server  *%%'`
    NTP_SUCCESS=0
    for NTP_SERVER in ${NTP_SERVERS} ; do
        /usr/bin/ntpdate -b -s "${NTP_SERVER}"
        if /usr/bin/test $? -eq 0 ; then
            NTP_SUCCESS=1
            continue
        fi
    done
    if /usr/bin/test ${NTP_SUCCESS} -eq 0 ; then
        mm_message_output warn "warning: 'ntpd' failed to synchronize with any NTP server." 
    fi

    # Start NTP daemon.
    mm_message_output info "starting NTP daemon ..."
    /usr/bin/ntpd -p /var/run/ntpd.pid

    return 0
}

stop() {
    mm_message_output info "saving time ..."

    if /usr/bin/test -n "`/bin/pidof ntpd`" ; then
        /usr/bin/killall ntpd
        /sbin/hwclock -w -u
    fi

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
