#!/bin/sh
################################################################################
# telnet.script
################################################################################
[ -n "`mm_var_get MM_DEBUG`" ] && set -x

case $1 in
    start)
        # Start telnet server daemon.
        telnetd -l /bin/sh
        ;;
    stop)
        if [ -n "`pidof telnetd`" ] ; then
            killall telnetd
        fi
        ;;
esac

exit 0
