#!/bin/sh
################################################################################
# video.script
#
# The script configures the video.
################################################################################
[ -n "`mm_var_get MM_DEBUG`" ] && set -x

MM_VIDEO_ASPECT_RATIO=`mm_var_get MM_VIDEO_ASPECT_RATIO`

sed -i "s%@MM_VIDEO_ASPECT_RATIO@%${MM_VIDEO_ASPECT_RATIO}%" /root/.mplayer/config

exit 0
