#!/bin/sh

. /lib/minimyth/mm_lcdproc

name="${1}"
driver="${2}"

device="${DEVNAME}"

case "${ACTION}" in
    add)
        if /usr/bin/test -z "${name}"   || \
           /usr/bin/test -z "${device}" || \
           /usr/bin/test -z "${driver}" ; then
            exit 0
        fi

        mm_lcdproc_state_put 'automatic' "${name}" "${device}" "${driver}"
        ;;
    remove)
        if /usr/bin/test -z "${name}"   ; then
            exit 0
        fi

        mm_lcdproc_state_delete 'automatic' "${name}"
        ;;
esac

exit 0
