#!/bin/sh

. /lib/minimyth/mm_detect

name="${1}"
driver="${2}"
remote="${3}"

device="${DEVNAME}"

case "${ACTION}" in
    add)
        if /usr/bin/test -z "${name}"   || \
           /usr/bin/test -z "${device}" || \
           /usr/bin/test -z "${driver}" ; then
            exit 0
        fi

        mm_detect_state_put 'lirc' 'automatic' "${name}" "${device},${driver},${remote}"
        ;;
    remove)
        if /usr/bin/test -z "${name}"   ; then
            exit 0
        fi

        mm_detect_state_delete 'lirc' 'automatic' "${name}"
        ;;
esac

exit 0
