GARNAME      = perl-Compress-Zlib
GARVERSION   = 2.008
MASTER_SITES = http://www.cpan.org/authors/id/P/PM/PMQS/
DEPENDS      = perl/perl-Compress-Raw-Zlib perl/perl-IO-Compress-Base perl/perl-IO-Compress-Zlib

include ../../perl/perl/perl-module.mk
