GARNAME           = perl-Params-Validate
GARVERSION        = 0.95
MASTER_SITES      = http://www.cpan.org/authors/id/D/DR/DROLSKY/
PERL_MODULE_STYLE = Build.PL
DEPENDS           =

include ../../perl/perl/perl-module.mk
