GARNAME         = perl-IO-Compress-Base
GARVERSION      = 2.008
MASTER_SITES    = http://www.cpan.org/authors/id/P/PM/PMQS/
DEPENDS         = utils/gzip
PERL_NOT_NEEDED = 5.10.0

include ../../perl/perl/perl-module.mk
