#!/bin/sh
################################################################################
# dhcp
################################################################################
. /etc/rc.d.sh/functions

start() {

    local COMMAND
    local DHCLIENT_CONF
    local INTERFACE
    local INTERFACE_ITEM
    local INTERFACE_LIST
    local IP_ADDRESS

    UDHCPC_CONF='/etc/udhcpc.conf'

    # Start 'udhcpc'.
    if /usr/bin/test -z "`/bin/pidof udhcpc`" ; then
        mm_message_output info "starting DHCP client ..."

        # Create a 'udhcpc.conf' file.
        /bin/rm -f "${UDHCPC_CONF}~"
        /bin/mkdir -p "`/usr/bin/dirname ${UDHCPC_CONF}~`"
        /bin/touch "${UDHCPC_CONF}~"
        /bin/chmod 644 "${UDHCPC_CONF}~"
        set | /bin/grep -e '^MM_DHCP_' > "${UDHCPC_CONF}~"
        /bin/mv -f "${UDHCPC_CONF}~" "${UDHCPC_CONF}"

        COMMAND='/sbin/udhcpc'
        COMMAND="${COMMAND} -S"
        COMMAND="${COMMAND} -p /var/run/udhcpc.pid"
        COMMAND="${COMMAND} -s /etc/udhcpc.script"

        # Determine network interface.
        INTERFACE=${MM_NETWORK_INTERFACE}
        if /usr/bin/test -z "${INTERFACE}" ; then
            # Locate a connected network interface.
            # We use the first connected network interface found.
            INTERFACE_LIST=
            if /usr/bin/test -e /sys/class/net ; then
                INTERFACE_LIST=`/bin/ls -1 /sys/class/net | /bin/grep -v '^lo$'`
            fi
            INTERFACE=
            for INTERFACE_ITEM in ${INTERFACE_LIST} ; do
                /usr/sbin/ifplugstatus -q ${INTERFACE_ITEM}
                if /usr/bin/test $? -eq 2 ; then
                    INTERFACE=${INTERFACE_ITEM}
                    break
                fi
            done
        fi
        if /usr/bin/test -z "${INTERFACE}" ; then
            mm_message_output info "no network interface found, defaulting to 'eth0'."
            INTERFACE='eth0'
        fi
        COMMAND="${COMMAND} -i ${INTERFACE}"

        # Reuse any existing IP address.
        IP_ADDRESS=`/sbin/ifconfig ${INTERFACE} | /bin/grep '^ *inet addr:' | /bin/sed 's%^ *inet addr:\([^ ]*\) .*%\1%'`
        if /usr/bin/test -n "${IP_ADDRESS}" ; then
            COMMAND="${COMMAND} -r ${IP_ADDRESS}"
        fi

        # Decide whether or not to run once.
        if /usr/bin/test ! -e /etc/conf.d/dhcp.override ; then
            COMMAND="${COMMAND} -q"
        fi

        COMMAND="${COMMAND} > /var/log/udhcpc 2>&1"

        # Start DHCP client on the interface.
        ${COMMAND}
        if /usr/bin/test $? -ne 0 ; then
            mm_message_output err "error: DHCP on interface '${INTERFACE}' failed."
            exit 1
        fi

        # Make sure we got an IP address.
        IP_ADDRESS=`/sbin/ifconfig ${INTERFACE} | /bin/grep '^ *inet addr:' | /bin/sed 's%^ *inet addr:\([^ ]*\) .*%\1%'`
        if /usr/bin/test -z "${IP_ADDRESS}" ; then
            mm_message_output err "error: DHCP on interface '${INTERFACE}' failed."
            exit 1
        fi
    fi

    return 0
}

stop() {

    mm_message_output info "stopping DHCP client ..."
    /usr/bin/test -n "`/bin/pidof udhcpc`" && /usr/bin/killall udhcpc

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
