#!/bin/sh
################################################################################
# ld
################################################################################
. /etc/rc.d.sh/functions

start() {
    mm_message_output info "configuring shared libraries ..."

    /sbin/ldconfig

    return 0
}

stop() {
    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
