#!/bin/sh
################################################################################
# modules_automatic
################################################################################
. /etc/rc.d.sh/functions

start() {

    local file
    local file_old
    local file_new

    mm_message_output info "loading kernel modules (automatic) ..."

    # Real time clock.
    /sbin/modprobe rtc

    # IO scheduler.
    /sbin/modprobe as-iosched

    # Loopback device.
    /sbin/modprobe loop

    # Net.
    /sbin/modprobe af_packet

    # Parallel port.
    /sbin/modprobe parport
    /sbin/modprobe parport_pc
    /sbin/modprobe ppdev

    # Enable modeprobe udev rules.
    /bin/mv -f /lib/udev/rules.d/01-minimyth-modprobe.rules.disabled /lib/udev/rules.d/01-minimyth-modprobe.rules

    # Trigger udev with the additional udev rules that handle detected hardware.
    /sbin/udevadm trigger
    /sbin/udevadm settle --timeout=60

    return 0
}

stop() {

    local module
    local modules

    mm_message_output info "unloading kernel modules (automatic) ..."

    modules=`/bin/lsmod | /bin/sed -e 's%  *% %g' | /usr/bin/cut -d ' ' -f 1 | /bin/grep -v Module`
    for module in ${modules} ; do
        /sbin/modprobe -r ${module}
    done

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
