#!/bin/sh
################################################################################
# mm_state
#
# State related functions.
################################################################################
mm_state_file_get() {
    local group="${1:-'null'}"
    local mode="${2:-'null'}"
    local item="${3:-'null'}"

    local state_file;

    state_file=`/bin/echo ${item} | /bin/sed -e 's%^/*%%' -e 's%/%~%g'`
    state_file="/var/cache/minimyth/state/${group}/${mode}/${state_file}"

    /bin/echo "${state_file}"
}

mm_state_get() {
    local group="$1"
    local mode="$2"

    local state_dir
    local state_file
    local state_file_list
    local state_item
    local state_list

    state_file=`mm_state_file_get "${group}" "${mode}" 'null'`
    state_dir=`/usr/bin/dirname "${state_file}"`
    state_file_list=`/bin/ls ${state_dir}/* 2> /dev/null`
    state_list=
    for state_file in ${state_file_list} ; do
        state_item=`/bin/cat "${state_file}"`
        state_list="${state_list} ${state_item}"
    done
    state_list=`/bin/echo "${state_list}" | /bin/sed -e 's%  *% %g' -e 's%^ %%' -e 's% $%%'`

    /bin/echo "${state_list}"
}

mm_state_put() {
    local group="$1"
    local mode="$2"
    local item="$3"
    local state="$4"

    local state_dir
    local state_file

    # Write state.
    state_file=`mm_state_file_get "${group}" "${mode}" "${item}"`
    state_dir=`/usr/bin/dirname "${state_file}"`
    if /usr/bin/test ! -e "${state_dir}" ; then
        /bin/mkdir -p        "${state_dir}"
        /bin/chown root:root "${state_dir}"
        /bin/chmod 0755      "${state_dir}"
    fi
    /bin/rm -f           "${state_file}"
    /bin/touch           "${state_file}"
    /bin/chown root:root "${state_file}"
    /bin/chmod 0644      "${state_file}"
    /bin/echo "${state}" >> "${state_file}"
}

mm_state_delete() {
    local group="$1"
    local mode="$2"
    local item="$3"

    if /usr/bin/test -n "${item}" ; then
        state_file=`mm_state_file_get "${group}" "${mode}" "${item}"`
        /bin/rm -f "${state_file}"
    fi
}
