#!/bin/sh
################################################################################
# mm_x
#
# X related functions.
################################################################################
. /lib/minimyth/mm_state

mm_x_state_get() {
    local type="$1"

    mm_state_get 'x' "${type}"
}

mm_x_state_put() {
    local type="$1"
    local name="$2"
    local driver="$3"

    local state

    if /usr/bin/test -n "${name}" ; then
        state="${driver}"

        mm_state_put 'x' "${type}" "${name}" "${state}"
    fi
}

mm_x_state_delete() {
    local type="$1"
    local name="$2"

    if /usr/bin/test -n "${name}" ; then
        mm_state_delete 'x' "${type}" "${name}"
    fi
}
