#!/bin/sh
################################################################################
# rc
################################################################################
. /etc/rc.d/functions

script_list_start="\
    ld \
    network \
    telnet \
    modules.automatic \
    conf \
    modules.manual \
    name \
    log \
    minimyth"
script_list_kill_halt="
    halt"
script_list_kill_reboot="\
    reboot"

rc_script_list_run() {
    local phase=$1
    local action=$2
    local script_list=$3

    local count
    local script

    count=`/bin/echo ${script_list} | /usr/bin/wc -w`
    if /usr/bin/test ${phase} -eq 0 ; then
        mm_splash_progress_set 0        $(( ${count} + ${count} ))
    else
        mm_splash_progress_set ${count} $(( ${count} + ${count} ))
    fi
    for script in ${script_list} ; do
        mm_command_run "${script} ${action}"
        if /usr/bin/test $? -ne 0 ; then
            exit $?
        fi
        mm_splash_progress_update
    done
}

case $1 in
    1|2|3|4|5)
        mm_splash_init
        script_list=`scripts=${script_list_start}       ; for script in ${scripts} ; do /bin/echo /etc/rc.d/init.d/${script} ; done`
        rc_script_list_run 0 "start" "${script_list}"
        script_list=`ls -1 /etc/rc.d/rc.d/S*`
        rc_script_list_run 1 "start" "${script_list}"
        mm_splash_halt
        ;;
    0)
        mm_splash_init
        script_list=`ls -1 /etc/rc.d/rc.d/K*`
        rc_script_list_run 0 "stop" "${script_list}"
        script_list=`scripts=${script_list_kill_halt}   ; for script in ${scripts} ; do /bin/echo /etc/rc.d/init.d/${script} ; done`
        rc_script_list_run 1 "stop" "${script_list}"
        mm_splash_halt
	;;
    6)
        mm_splash_init
        script_list=`ls -1 /etc/rc.d/rc.d/K*`
        rc_script_list_run 0 "stop" "${script_list}"
        script_list=`scripts=${script_list_kill_reboot} ; for script in ${scripts} ; do /bin/echo /etc/rc.d/init.d/${script} ; done`
        rc_script_list_run 1 "stop" "${script_list}"
        mm_splash_halt
	;;
esac

exit 0
