GARNAME             = perl-libwww-perl
GARVERSION          = 5.808
MASTER_SITES        = http://www.cpan.org/authors/id/G/GA/GAAS/
PERL_MODULE_PATCHES = useragent.patch
DEPENDS             = perl/perl-Compress-Zlib perl/perl-HTML-Parser perl/perl-URI

include ../../perl/perl/perl-module.mk
