#!/bin/sh

# This script copies the needed GAR files
# from the directory ${GAR_LNX_BBC_DIR} to ${SCRIPT_DIR}
# and makes the needed modifications.

cd `echo ${0} | sed 's%/[^/]*$%%'`
GAR_LNX_BBC_DIR=`pwd`/gar-lnx-bbc
cd ..
SCRIPT_DIR=`pwd`/script

#-------------------------------------------------------------------------------
# GAR values to change.
#-------------------------------------------------------------------------------
ALL_DESTIMGS='main build'
GARBUILD='$(shell gcc -dumpmachine)'
build_GARHOST='$(GARBUILD)'
build_GARCH='$(strip $(subst x86_64,x86-64, \\\
    $(if $(filter-out unknown,$(shell uname -m)), \\\
        $(shell uname -m) \\\
    , \\\
        $(shell arch) \\\
    )))'
build_GARCH_FAMILY='$(strip \\\
    $(if $(filter i386 i486 i586 i686,$(build_GARCH)),i386  ) \\\
    $(if $(filter x86-64             ,$(build_GARCH)),x86_64))'
main_GARHOST='$(mm_GARHOST)'
main_GARCH='$(mm_GARCH)'
main_GARCH_FAMILY='$(mm_GARCH_FAMILY)'
build_DESTDIR='/'
build_rootdir='$(mm_HOME)/images/build'
main_DESTDIR='$(mm_HOME)/images/main'
main_rootdir=''
GARCHIVEROOT='$(mm_HOME)/source'
PATCHDIR='$(WORKSRC)'
GAR_EXTRA_CONF='extras/extras.conf.mk devel/gcc/package-api.mk'
GAR_EXTRA_LIBS='minimyth.lib.mk'
MASTER_SITES='http://minimyth.org/download/garchive/'
build_NODEPEND='kernel/linux-headers devel/glibc'
build_compiler_prefix=''
main_compiler_prefix='$(GARHOST)-'
build_CPPFLAGS=''
build_CFLAGS='-pipe -march=$(build_GARCH) -O2 $(if $(filter i386,$(build_GARCH_FAMILY)),-m32) $(if $(filter x86_64,$(build_GARCH_FAMILY)),-m64)'
build_CXXFLAGS='$(build_CFLAGS)'
build_LDFLAGS=''
main_CPPFLAGS=''
main_CFLAGS='$(mm_CFLAGS)'
main_CXXFLAGS='$(main_CFLAGS)'
main_LDFLAGS='-Wl,--as-needed'
GAR_SYSTEM_PATH='$(build_DESTDIR)$(build_esbindir):$(build_DESTDIR)$(build_ebindir):$(build_DESTDIR)$(build_sbindir):$(build_DESTDIR)$(build_bindir):$(build_DESTDIR)$(build_kdebindir):$(build_DESTDIR)$(build_rootdir)/bin-build-system'
_LD_LIBRARY_PATH='$(build_DESTDIR)$(build_elibdir):$(build_DESTDIR)$(build_libdir):$(build_DESTDIR)$(build_qt4libdir):$(build_DESTDIR)$(build_qt3libdir):$(build_DESTDIR)$(build_kdelibdir):$(build_DESTDIR)$(build_libdir)/mysql'
_LIBRARY_PATH='$(build_DESTDIR)$(build_elibdir):$(build_DESTDIR)$(build_libdir):$(build_DESTDIR)$(build_qt4libdir):$(build_DESTDIR)$(build_qt3libdir):$(build_DESTDIR)$(build_kdelibdir):$(build_DESTDIR)$(build_libdir)/mysql$(strip $(if $(filter i386,$(build_GARCH_FAMILY)),:/lib32:/usr/lib32:/lib:/usr/lib) $(if $(filter x86_64,$(build_GARCH_FAMILY)),:/lib64:/usr/lib64:/lib:/usr/lib))'
_PKG_CONFIG_LIBDIR='$(DESTDIR)$(libdir)/pkgconfig:$(DESTDIR)$(qt4libdir)/pkgconfig:$(DESTDIR)$(qt3libdir)/pkgconfig'
_PKG_CONFIG_SYSROOT_DIR='$(DESTDIR)'

# Replace current GAR files with clean GAR files.
rm -f ${SCRIPT_DIR}/gar.mk      ; cp ${GAR_LNX_BBC_DIR}/gar.mk ${SCRIPT_DIR}
rm -f ${SCRIPT_DIR}/gar.*.mk    ; cp ${GAR_LNX_BBC_DIR}/gar.*.mk ${SCRIPT_DIR}
rm -f ${SCRIPT_DIR}/category.mk ; cp ${GAR_LNX_BBC_DIR}/category.mk ${SCRIPT_DIR}
rm -f ${SCRIPT_DIR}/Makefile    ; cp ${GAR_LNX_BBC_DIR}/Makefile ${SCRIPT_DIR}

# Fix bugs.
sed -i 's%^STAGE_EXPORTS *+= *CPPFLAGS .*%& CXXFLAGS%g' ${SCRIPT_DIR}/gar.conf.mk
sed -i 's%^STAGE_EXPORTS *+= *CC .*%& LD%g' ${SCRIPT_DIR}/gar.conf.mk
sed -i '/main_[^ ]* = $(prefix)/ { s%$(prefix)%$(main_prefix)%g }' ${SCRIPT_DIR}/gar.conf.mk
sed -i '/main_[^ ]* = $(exec_prefix)/ { s%$(exec_prefix)%$(main_exec_prefix)%g }' ${SCRIPT_DIR}/gar.conf.mk
sed -i 's%# Extra configuration for the lnx-bbc build%# Extra confs to include after gar.conf.mk%g' ${SCRIPT_DIR}/gar.conf.mk

# Add additional licenses.

sed -i 's%Clarified-Artistic.txt%Clarified_Artistic.txt%g' ${SCRIPT_DIR}/gar.lib.mk
sed -i 's%public-domain.txt%Public_Domain.txt%g' ${SCRIPT_DIR}/gar.lib.mk

sed -i 's%^GPL_LICENSE_TEXT *=%FDL_LICENSE_TEXT = $(LICENSEDIR)/FDL.txt\nGPL_LICENSE_TEXT =%' ${SCRIPT_DIR}/gar.lib.mk
sed -i 's%^GPL_LICENSE_TEXT *=%FDL1_2_LICENSE_TEXT = $(LICENSEDIR)/FDL1_2.txt\nGPL_LICENSE_TEXT =%' ${SCRIPT_DIR}/gar.lib.mk
sed -i 's%^GPL_LICENSE_TEXT *=%FDL1_3_LICENSE_TEXT = $(LICENSEDIR)/FDL1_3.txt\nGPL_LICENSE_TEXT =%' ${SCRIPT_DIR}/gar.lib.mk
sed -i 's%^GPL_LICENSE_TEXT *=%BSD_2_Clause_LICENSE_TEXT = $(LICENSEDIR)/BSD_2_Clause.txt\nGPL_LICENSE_TEXT =%' ${SCRIPT_DIR}/gar.lib.mk
sed -i 's%^GPL_LICENSE_TEXT *=%BSD_3_Clause_LICENSE_TEXT = $(LICENSEDIR)/BSD_3_Clause.txt\nGPL_LICENSE_TEXT =%' ${SCRIPT_DIR}/gar.lib.mk
sed -i 's%^GPL_LICENSE_TEXT *=%BSD_4_Clause_LICENSE_TEXT = $(LICENSEDIR)/BSD_4_Clause.txt\nGPL_LICENSE_TEXT =%' ${SCRIPT_DIR}/gar.lib.mk
sed -i 's%^GPL_LICENSE_TEXT *=%MIT_Modified_LICENSE_TEXT = $(LICENSEDIR)/MIT_Modified.txt\nGPL_LICENSE_TEXT =%' ${SCRIPT_DIR}/gar.lib.mk
sed -i 's%^GPL_LICENSE_TEXT *=%MPL1_1_LICENSE_TEXT = $(LICENSEDIR)/MPL1_1.txt\nGPL_LICENSE_TEXT =%' ${SCRIPT_DIR}/gar.lib.mk
sed -i 's%^GPL_LICENSE_TEXT *=%LGPL3_LICENSE_TEXT = $(LICENSEDIR)/LGPL3.txt\nGPL_LICENSE_TEXT =%' ${SCRIPT_DIR}/gar.lib.mk

# Add install-version.
sed -i 's%^INSTALL_TARGETS *= *\(.*\)$%INSTALL_TARGETS = \1 install-version%g' ${SCRIPT_DIR}/gar.mk
sed -i 's%^install-license%install-version:\n\t@install -d $(DESTDIR)$(versiondir) \n\t@echo $(GARVERSION) > \$(DESTDIR)$(versiondir)/$(GARNAME)\n\t@\$(MAKECOOKIE)\n\ninstall-license%' ${SCRIPT_DIR}/gar.lib.mk
sed -i 's%^\(build\|main\)_licensedir *=.*$%&\n\1_versiondir = $(\1_exec_prefix)/versions%g' ${SCRIPT_DIR}/gar.conf.mk
sed -i 's%^$(DESTIMG)_licensedir *?= *$(main_licensedir)%&\n$(DESTIMG)_versiondir ?= $(main_versiondir)%g' ${SCRIPT_DIR}/gar.mk
sed -i 's%^licensedir *= *$($(DESTIMG)_licensedir)%&\nversiondir = $($(DESTIMG)_versiondir)%g' ${SCRIPT_DIR}/gar.mk

# Add the --oldincludedir directory path.
sed -i 's%^\(build\|main\)_includedir *=.*$%&\n\1_oldincludedir = $(\1_exec_prefix)/include%g' ${SCRIPT_DIR}/gar.conf.mk
sed -i 's%^$(DESTIMG)_includedir *?= *$(main_includedir)%&\n$(DESTIMG)_oldincludedir ?= $(main_oldincludedir)%g' ${SCRIPT_DIR}/gar.mk
sed -i 's%^includedir *= *$($(DESTIMG)_includedir)%&\noldincludedir = $($(DESTIMG)_oldincludedir)%g' ${SCRIPT_DIR}/gar.mk
sed -i '/^INSTALL_DIRS *=/s% $(includedir)%& $(oldincludedir)%g' ${SCRIPT_DIR}/gar.mk
sed -i '/^TMP_DIRPATHS *=/s% --includedir=$(includedir)%& --oldincludedir=$(oldincludedir)%g' ${SCRIPT_DIR}/gar.lib.mk
sed -i '/^STAGE_EXPORTS *+=/s% includedir%& oldincludedir%g' ${SCRIPT_DIR}/gar.conf.mk

# Make directory hierarchy compliant with Filesystem Hierarchy Standard.
# Add the variable rootdir.
# Set prefix=rootdir/usr.
# Make all prefixes and directories relative to rootdir.
# Set sysconfdir=rootdir/etc and locatestatedir=rootdir/var.
# Set mandir=rootdir/usr/share/man
# Add qt and kde directories
# Add essential library (elib), user binary (ebin) and system binary (esbin) directories.
sed -i "s%^build_prefix *?=.*%build_rootdir ?= ${build_rootdir}\n&%g" ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^main_prefix *?=.*%main_rootdir ?= ${main_rootdir}\n&%g" ${SCRIPT_DIR}/gar.conf.mk
sed -i 's%^$(DESTIMG)_prefix *?=.*%$(DESTIMG)_rootdir ?= $(main_rootdir)\n&%g' ${SCRIPT_DIR}/gar.mk
sed -i 's%^prefix *=.*%rootdir = $($(DESTIMG)_rootdir)\n&%g' ${SCRIPT_DIR}/gar.mk

sed -i 's%^\(build\|main\)_prefix *?=.*%\1_prefix = $(\1_rootdir)/usr%g' ${SCRIPT_DIR}/gar.conf.mk
sed -i 's%^\(main\|build\)\(_[^ ]*\) *= *$(\(main\|build\)_prefix)%\1\2 = $(\3_rootdir)/usr%g' ${SCRIPT_DIR}/gar.conf.mk
sed -i 's%^\(main\|build\)\(_[^ ]*\) *= *$(\(main\|build\)_exec_prefix)%\1\2 = $(\3_rootdir)/usr%g' ${SCRIPT_DIR}/gar.conf.mk

sed -i 's%^\(build\|main\)_sysconfdir *=.*%\1_sysconfdir = $(\1_rootdir)/etc%g' ${SCRIPT_DIR}/gar.conf.mk
sed -i 's%^\(build\|main\)_localstatedir *=.*%\1_localstatedir = $(\1_rootdir)/var%g' ${SCRIPT_DIR}/gar.conf.mk

sed -i 's%^\(build\|main\)_mandir *=.*%\1_mandir = $(\1_rootdir)/usr/share/man%g' ${SCRIPT_DIR}/gar.conf.mk

sed -i 's%^\(build\|main\)_versiondir *=.*$%&\n\1_kdelibdir = $(\1_kdeprefix)/lib%g' ${SCRIPT_DIR}/gar.conf.mk
sed -i 's%^$(DESTIMG)_versiondir *?= *$(main_versiondir)%&\n$(DESTIMG)_kdelibdir ?= $(main_kdelibdir)%g' ${SCRIPT_DIR}/gar.mk
sed -i 's%^versiondir *= *$($(DESTIMG)_versiondir)%&\nkdelibdir = $($(DESTIMG)_kdelibdir)%g' ${SCRIPT_DIR}/gar.mk

sed -i 's%^\(build\|main\)_versiondir *=.*$%&\n\1_kdeincludedir = $(\1_kdeprefix)/include%g' ${SCRIPT_DIR}/gar.conf.mk
sed -i 's%^$(DESTIMG)_versiondir *?= *$(main_versiondir)%&\n$(DESTIMG)_kdeincludedir ?= $(main_kdeincludedir)%g' ${SCRIPT_DIR}/gar.mk
sed -i 's%^versiondir *= *$($(DESTIMG)_versiondir)%&\nkdeincludedir = $($(DESTIMG)_kdeincludedir)%g' ${SCRIPT_DIR}/gar.mk

sed -i 's%^\(build\|main\)_versiondir *=.*$%&\n\1_kdedatadir = $(\1_kdeprefix)/share%g' ${SCRIPT_DIR}/gar.conf.mk
sed -i 's%^$(DESTIMG)_versiondir *?= *$(main_versiondir)%&\n$(DESTIMG)_kdedatadir ?= $(main_kdedatadir)%g' ${SCRIPT_DIR}/gar.mk
sed -i 's%^versiondir *= *$($(DESTIMG)_versiondir)%&\nkdedatadir = $($(DESTIMG)_kdedatadir)%g' ${SCRIPT_DIR}/gar.mk

sed -i 's%^\(build\|main\)_versiondir *=.*$%&\n\1_kdebindir = $(\1_kdeprefix)/bin%g' ${SCRIPT_DIR}/gar.conf.mk
sed -i 's%^$(DESTIMG)_versiondir *?= *$(main_versiondir)%&\n$(DESTIMG)_kdebindir ?= $(main_kdebindir)%g' ${SCRIPT_DIR}/gar.mk
sed -i 's%^versiondir *= *$($(DESTIMG)_versiondir)%&\nkdebindir = $($(DESTIMG)_kdebindir)%g' ${SCRIPT_DIR}/gar.mk

sed -i 's%^\(build\|main\)_versiondir *=.*$%&\n\1_kdeprefix = $(\1_prefix)/kde%g' ${SCRIPT_DIR}/gar.conf.mk
sed -i 's%^$(DESTIMG)_versiondir *?= *$(main_versiondir)%&\n$(DESTIMG)_kdeprefix ?= $(main_kdeprefix)%g' ${SCRIPT_DIR}/gar.mk
sed -i 's%^versiondir *= *$($(DESTIMG)_versiondir)%&\nkdeprefix = $($(DESTIMG)_kdeprefix)%g' ${SCRIPT_DIR}/gar.mk

sed -i 's%^\(build\|main\)_versiondir *=.*$%&\n\1_qt4libdir = $(\1_qt4prefix)/lib%g' ${SCRIPT_DIR}/gar.conf.mk
sed -i 's%^$(DESTIMG)_versiondir *?= *$(main_versiondir)%&\n$(DESTIMG)_qt4libdir ?= $(main_qt4libdir)%g' ${SCRIPT_DIR}/gar.mk
sed -i 's%^versiondir *= *$($(DESTIMG)_versiondir)%&\nqt4libdir = $($(DESTIMG)_qt4libdir)%g' ${SCRIPT_DIR}/gar.mk

sed -i 's%^\(build\|main\)_versiondir *=.*$%&\n\1_qt4includedir = $(\1_qt4prefix)/include%g' ${SCRIPT_DIR}/gar.conf.mk
sed -i 's%^$(DESTIMG)_versiondir *?= *$(main_versiondir)%&\n$(DESTIMG)_qt4includedir ?= $(main_qt4includedir)%g' ${SCRIPT_DIR}/gar.mk
sed -i 's%^versiondir *= *$($(DESTIMG)_versiondir)%&\nqt4includedir = $($(DESTIMG)_qt4includedir)%g' ${SCRIPT_DIR}/gar.mk

sed -i 's%^\(build\|main\)_versiondir *=.*$%&\n\1_qt4bindir = $(\1_qt4prefix)/bin%g' ${SCRIPT_DIR}/gar.conf.mk
sed -i 's%^$(DESTIMG)_versiondir *?= *$(main_versiondir)%&\n$(DESTIMG)_qt4bindir ?= $(main_qt4bindir)%g' ${SCRIPT_DIR}/gar.mk
sed -i 's%^versiondir *= *$($(DESTIMG)_versiondir)%&\nqt4bindir = $($(DESTIMG)_qt4bindir)%g' ${SCRIPT_DIR}/gar.mk

sed -i 's%^\(build\|main\)_versiondir *=.*$%&\n\1_qt4prefix = $(\1_libdir)/qt4%g' ${SCRIPT_DIR}/gar.conf.mk
sed -i 's%^$(DESTIMG)_versiondir *?= *$(main_versiondir)%&\n$(DESTIMG)_qt4prefix ?= $(main_qt4prefix)%g' ${SCRIPT_DIR}/gar.mk
sed -i 's%^versiondir *= *$($(DESTIMG)_versiondir)%&\nqt4prefix = $($(DESTIMG)_qt4prefix)%g' ${SCRIPT_DIR}/gar.mk

sed -i 's%^\(build\|main\)_versiondir *=.*$%&\n\1_qt3libdir = $(\1_qt3prefix)/lib%g' ${SCRIPT_DIR}/gar.conf.mk
sed -i 's%^$(DESTIMG)_versiondir *?= *$(main_versiondir)%&\n$(DESTIMG)_qt3libdir ?= $(main_qt3libdir)%g' ${SCRIPT_DIR}/gar.mk
sed -i 's%^versiondir *= *$($(DESTIMG)_versiondir)%&\nqt3libdir = $($(DESTIMG)_qt3libdir)%g' ${SCRIPT_DIR}/gar.mk

sed -i 's%^\(build\|main\)_versiondir *=.*$%&\n\1_qt3includedir = $(\1_qt3prefix)/include%g' ${SCRIPT_DIR}/gar.conf.mk
sed -i 's%^$(DESTIMG)_versiondir *?= *$(main_versiondir)%&\n$(DESTIMG)_qt3includedir ?= $(main_qt3includedir)%g' ${SCRIPT_DIR}/gar.mk
sed -i 's%^versiondir *= *$($(DESTIMG)_versiondir)%&\nqt3includedir = $($(DESTIMG)_qt3includedir)%g' ${SCRIPT_DIR}/gar.mk

sed -i 's%^\(build\|main\)_versiondir *=.*$%&\n\1_qt3bindir = $(\1_qt3prefix)/bin%g' ${SCRIPT_DIR}/gar.conf.mk
sed -i 's%^$(DESTIMG)_versiondir *?= *$(main_versiondir)%&\n$(DESTIMG)_qt3bindir ?= $(main_qt3bindir)%g' ${SCRIPT_DIR}/gar.mk
sed -i 's%^versiondir *= *$($(DESTIMG)_versiondir)%&\nqt3bindir = $($(DESTIMG)_qt3bindir)%g' ${SCRIPT_DIR}/gar.mk

sed -i 's%^\(build\|main\)_versiondir *=.*$%&\n\1_qt3prefix = $(\1_libdir)/qt3%g' ${SCRIPT_DIR}/gar.conf.mk
sed -i 's%^$(DESTIMG)_versiondir *?= *$(main_versiondir)%&\n$(DESTIMG)_qt3prefix ?= $(main_qt3prefix)%g' ${SCRIPT_DIR}/gar.mk
sed -i 's%^versiondir *= *$($(DESTIMG)_versiondir)%&\nqt3prefix = $($(DESTIMG)_qt3prefix)%g' ${SCRIPT_DIR}/gar.mk

sed -i 's%^\(build\|main\)_libdir *=.*$%\1_elibdir = $(\1_rootdir)/lib\n&%g' ${SCRIPT_DIR}/gar.conf.mk
sed -i 's%^$(DESTIMG)_libdir *?= *$(main_libdir)%$(DESTIMG)_elibdir ?= $(main_elibdir)\n&%g' ${SCRIPT_DIR}/gar.mk
sed -i 's%^libdir *= *$($(DESTIMG)_libdir)%elibdir = $($(DESTIMG)_elibdir)\n&%g' ${SCRIPT_DIR}/gar.mk

sed -i 's%^\(build\|main\)_bindir *=.*$%\1_ebindir = $(\1_rootdir)/bin\n&%g' ${SCRIPT_DIR}/gar.conf.mk
sed -i 's%^$(DESTIMG)_bindir *?= *$(main_bindir)%$(DESTIMG)_ebindir ?= $(main_ebindir)\n&%g' ${SCRIPT_DIR}/gar.mk
sed -i 's%^bindir *= *$($(DESTIMG)_bindir)%ebindir = $($(DESTIMG)_ebindir)\n&%g' ${SCRIPT_DIR}/gar.mk

sed -i 's%^\(build\|main\)_sbindir *=.*$%\1_esbindir = $(\1_rootdir)/sbin\n&%g' ${SCRIPT_DIR}/gar.conf.mk
sed -i 's%^$(DESTIMG)_sbindir *?= *$(main_sbindir)%$(DESTIMG)_esbindir ?= $(main_esbindir)\n&%g' ${SCRIPT_DIR}/gar.mk
sed -i 's%^sbindir *= *$($(DESTIMG)_sbindir)%esbindir = $($(DESTIMG)_esbindir)\n&%g' ${SCRIPT_DIR}/gar.mk

sed -i 's%^\(build\|main\)_rootdir *?=.*%&\n# Warning: any changes to these paths will cause certain packages to break.%g' ${SCRIPT_DIR}/gar.conf.mk

# Configure compiler programs
sed -i "s%^build_CC *?=%build_compiler_prefix ?= ${build_compiler_prefix}\n&%" ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^main_CC *?=%main_compiler_prefix ?= ${main_compiler_prefix}\n&%" ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^\$(DESTIMG)_CC *?=%\$(DESTIMG)_compiler_prefix ?= \$(main_compiler_prefix)\n&%" ${SCRIPT_DIR}/gar.mk
sed -i "s%^CC *=%compiler_prefix = \$(\$(DESTIMG)_compiler_prefix)\n&%" ${SCRIPT_DIR}/gar.mk
programs="CC CXX LD"
sed -i "s%^build_CC *?=.*%build_CC = \$(build_compiler_prefix)gcc%" ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^main_CC *?=.*%main_CC = \$(main_compiler_prefix)gcc%" ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^build_CXX *?=.*%build_CXX = \$(build_compiler_prefix)g++%" ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^main_CXX *?=.*%main_CXX = \$(main_compiler_prefix)g++%" ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^build_LD *?=.*%build_LD = \$(build_compiler_prefix)ld%" ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^main_LD *?=.*%main_LD = \$(main_compiler_prefix)ld%" ${SCRIPT_DIR}/gar.conf.mk
programs="CPP AR AS NM RANLIB STRIP OBJCOPY OBJDUMP"
for program in ${programs} ; do
    program_uc=`echo ${program} | sed -r 's%[a-z]+%\U&%g'`
    program_lc=`echo ${program} | sed -r 's%[A-Z]+%\L&%g'`
    sed -i "s%^build_LD *=.*$%&\nbuild_${program_uc} = \$(build_compiler_prefix)${program_lc}%g" ${SCRIPT_DIR}/gar.conf.mk
    sed -i "s%^main_LD *=.*$%&\nmain_${program_uc} = \$(main_compiler_prefix)${program_lc}%g" ${SCRIPT_DIR}/gar.conf.mk
    sed -i "s%^\$(DESTIMG)_LD *?= *\$(main_LD)%&\n\$(DESTIMG)_${program_uc} ?= \$(main_${program_uc})%g" ${SCRIPT_DIR}/gar.mk
    sed -i "s%^LD *= *\$(\$(DESTIMG)_LD)%&\n${program_uc} = \$(\$(DESTIMG)_${program_uc})%g" ${SCRIPT_DIR}/gar.mk
    sed -i "s%^STAGE_EXPORTS *+= *CC .*%& ${program_uc}%g" ${SCRIPT_DIR}/gar.conf.mk
done
    
sed -i "s%^\(#*ALL_DESTIMGS\) *=.*$%\1 = ${ALL_DESTIMGS}%g" ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^\(#*GARBUILD\) *?=.*$%\1 ?= ${GARBUILD}%g" ${SCRIPT_DIR}/gar.mk
sed -i "s%^\(#*build_GARHOST\) *:=.*$%\1 := ${build_GARHOST}%g" ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^\(#*build_GARCH\) *:=.*$%\1 := ${build_GARCH}%g" ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^\(#*main_GARHOST\) *?=.*$%\1 ?= ${main_GARHOST}%g" ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^\(#*main_GARCH\) *?=.*$%\1 ?= ${main_GARCH}%g" ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^\(#*build_DESTDIR\) *?=.*$%\1 ?= ${build_DESTDIR}%g" ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^\(#*main_DESTDIR\) *?=.*$%\1 ?= ${main_DESTDIR}%g" ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^\(#*GARCHIVEROOT\) *?=.*$%\1 ?= ${GARCHIVEROOT}%g" ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^\(#*build_NODEPEND\) *=.*$%\1 += ${build_NODEPEND}%g" ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^\(#*MASTER_SITES\) *+=.*$%\1 += ${MASTER_SITES}%g" ${SCRIPT_DIR}/gar.conf.mk

#sed -i 's%^\(include \$(GARDIR)/gar.conf.mk\)%\1\n-include $(HOME)/.minimyth/minimyth.conf.mk\ninclude $(GARDIR)/minimyth.conf.mk%' ${SCRIPT_DIR}/gar.mk
sed -i 's%^\(include \$(GARDIR)/gar.conf.mk\)%include $(GARDIR)/minimyth.conf.mk\n\1%' ${SCRIPT_DIR}/gar.mk
sed -i "s%^\(#*GAR_EXTRA_CONF\) *+=.*$%\1 +=%g" ${SCRIPT_DIR}/gar.conf.mk
sed -i '$!N; /^\(GAR_EXTRA_CONF +=.*\)\n\1$/!P; D' ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^GAR_EXTRA_CONF +=.*$%GAR_EXTRA_CONF += ${GAR_EXTRA_CONF}%g" ${SCRIPT_DIR}/gar.conf.mk

sed -i "s%^\(#*GAR_EXTRA_LIBS\) *+=.*$%\1 +=%g" ${SCRIPT_DIR}/gar.conf.mk
sed -i '$!N; /^\(GAR_EXTRA_LIBS +=.*\)\n\1$/!P; D' ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^GAR_EXTRA_LIBS +=.*$%GAR_EXTRA_LIBS += ${GAR_EXTRA_LIBS}%g" ${SCRIPT_DIR}/gar.conf.mk

if [ "x${GAR_EXTRA_LIBS}" = "x" ] ; then
	sed -i 's%^include *.*$(GAR_EXTRA_LIBS).*$%#&%g' ${SCRIPT_DIR}/gar.lib.mk
fi

# Enable CXXFLAGS
sed -i "s%^#*\(.*_CXXFLAGS *+=.*\)$%\1%g" ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^#*\(.*_CXXFLAGS *?=.*\)$%\1%g" ${SCRIPT_DIR}/gar.mk
sed -i "s%^#*\(CXXFLAGS *+=.*\)$%\1%g" ${SCRIPT_DIR}/gar.mk

# Replace compiler flags
sed -i 's%^#*\(build_[^ ]*FLAGS\) *+=.*$%\1 +=%g' ${SCRIPT_DIR}/gar.conf.mk
sed -i -n 'G; s%\n%&&%; /^\(build_[^ ]*FLAGS +=.*\n\).*\n\1/d; s%\n%%; h; P' ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^#*\(build_CPPFLAGS\) *+=.*$%\1 += ${build_CPPFLAGS}%g" ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^#*\(build_CFLAGS\) *+=.*$%\1 += ${build_CFLAGS}%g" ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^#*\(build_CXXFLAGS\) *+=.*$%\1 += ${build_CXXFLAGS}%g" ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^#*\(build_LDFLAGS\) *+=.*$%\1 += ${build_LDFLAGS}%g" ${SCRIPT_DIR}/gar.conf.mk

sed -i 's%^#*\(main_[^ ]*FLAGS\) *+=.*$%\1 +=%g' ${SCRIPT_DIR}/gar.conf.mk
sed -i -n 'G; s%\n%&&%; /^\(main_[^ ]*FLAGS +=.*\n\).*\n\1/d; s%\n%%; h; P' ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^#*\(main_CPPFLAGS\) *+=.*$%\1 += ${main_CPPFLAGS}%g" ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^#*\(main_CFLAGS\) *+=.*$%\1 += ${main_CFLAGS}%g" ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^#*\(main_CXXFLAGS\) *+=.*$%\1 += ${main_CXXFLAGS}%g" ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^#*\(main_LDFLAGS\) *+=.*$%\1 += ${main_LDFLAGS}%g" ${SCRIPT_DIR}/gar.conf.mk

# Add GARCH_FAMILY attribute.
sed -i "s%^build_GARHOST *:=.*$%build_GARCH_FAMILY := ${build_GARCH_FAMILY}\n&%g" ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^main_GARHOST *?=.*$%main_GARCH_FAMILY ?= ${main_GARCH_FAMILY}\n&%g" ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^\$(DESTIMG)_GARHOST *?= *\$(main_GARHOST)%\$(DESTIMG)_GARCH_FAMILY ?= \$(main_GARCH_FAMILY)\n&%g" ${SCRIPT_DIR}/gar.mk
sed -i "s%^GARHOST *= *\$(\$(DESTIMG)_GARHOST)%GARCH_FAMILY = \$(\$(DESTIMG)_GARCH_FAMILY)\n&%g" ${SCRIPT_DIR}/gar.mk

# # Disable LD_LIBRARY_PATH
# # We use the Linux From Scratch patches instead.
# sed -i "s%^LD_LIBRARY_PATH *:=.*$%#&%g" ${SCRIPT_DIR}/gar.mk

# Set LD_LIBRARY_PATH and LIBRARY_PATH.
sed -i "s%^\(LD_LIBRARY_PATH\) *:=.*$%LIBRARY_PATH = ${_LIBRARY_PATH}\n\1 = ${_LD_LIBRARY_PATH}%g" ${SCRIPT_DIR}/gar.mk
sed -i '/^export .* LD_LIBRARY_PATH /s% LD_LIBRARY_PATH % LIBRARY_PATH LD_LIBRARY_PATH %' ${SCRIPT_DIR}/gar.conf.mk

# Change PATCHDIR
sed -i "s%^\(#*PATCHDIR\) *?=.*$%\1 ?= ${PATCHDIR}%g" ${SCRIPT_DIR}/gar.lib.mk

# Change PATH
sed -i "s%^PATH *:= *%BUILD_SYSTEM_PATH := \$(if \$(BUILD_SYSTEM_PATH),\$(BUILD_SYSTEM_PATH),\$(PATH))\nPATH := %g" ${SCRIPT_DIR}/gar.mk
sed -i "s%^PATH *:= *%GAR_SYSTEM_PATH := ${GAR_SYSTEM_PATH}\nPATH := %g" ${SCRIPT_DIR}/gar.mk
sed -i "s%^PATH *:=.*$%PATH := \$(if \$(wildcard \$(build_DESTDIR)\$(build_rootdir)/bin-build-system),\$(GAR_SYSTEM_PATH),\$(GAR_SYSTEM_PATH):\$(BUILD_SYSTEM_PATH))%g" ${SCRIPT_DIR}/gar.mk
sed -i "s%^export PATH%export BUILD_SYSTEM_PATH GAR_SYSTEM_PATH PATH%g" ${SCRIPT_DIR}/gar.conf.mk

# Clear PKG_CONFIG_PATH, add PKG_CONFIG_LIBDIR and PKG_CONFIG_SYSROOT_DIR, and clear PERLLIB and PERL5LIB.
sed -i "s%^PKG_CONFIG_PATH *=.*$%PKG_CONFIG_PATH = \nPKG_CONFIG_LIBDIR = ${_PKG_CONFIG_LIBDIR}\nPKG_CONFIG_SYSROOT_DIR = ${_PKG_CONFIG_SYSROOT_DIR}\nPERLLIB = \nPERL5LIB =%g" ${SCRIPT_DIR}/gar.conf.mk
sed -i "s%^export  *PKG_CONFIG_PATH$%export PKG_CONFIG_PATH PKG_CONFIG_LIBDIR PKG_CONFIG_SYSROOT_DIR\nexport PERLLIB PERL5LIB%g" ${SCRIPT_DIR}/gar.conf.mk

sed -i '/^INSTALL_DIRS *=/s%$(sbindir)%$(esbindir) &%' ${SCRIPT_DIR}/gar.mk
sed -i '/^INSTALL_DIRS *=/s%$(bindir)%$(ebindir) &%' ${SCRIPT_DIR}/gar.mk
sed -i '/^INSTALL_DIRS *=/s%$(libdir)%$(elibdir) &%' ${SCRIPT_DIR}/gar.mk

# Change build_DEPENDS
sed -i "s%^build_DEPENDS *+= *\(.*\)$%build_DEPENDS += devel/build-system-bins \1%g" ${SCRIPT_DIR}/gar.lib.mk

# Add additional licenses
sed -i 's%^\(GPL2_LICENSE_TEXT *=.*\)$%\1\nGPL3_LICENSE_TEXT = \$(LICENSEDIR)/GPL3.txt%' ${SCRIPT_DIR}/gar.lib.mk

# Fixed wget dependent fetches
sed -i 's%^\t@wget -c -P \$(PARTIALDIR) http://\$\*$%\t@cd \$(PARTIALDIR) ; wget -c http://\$\*%' ${SCRIPT_DIR}/gar.lib.mk
sed -i 's%^\t@wget -c --passive-ftp -P \$(PARTIALDIR) ftp://\$\*$%\t@cd \$(PARTIALDIR) ; wget -c --passive-ftp ftp://\$\*%' ${SCRIPT_DIR}/gar.lib.mk
