NVIDIA_MAJOR_VERSION = 1
NVIDIA_MINOR_VERSION = 0
NVIDIA_TEENY_VERSION = 8178

NVIDIA_VERSION = $(NVIDIA_MAJOR_VERSION).$(NVIDIA_MINOR_VERSION)-$(NVIDIA_TEENY_VERSION)

NVIDIA_DISTFILE = NVIDIA-Linux-x86-$(NVIDIA_VERSION)-pkg1
