#!/bin/sh
################################################################################
# mm_uid
#
# This script provides a unique identifier based on hardware information.
#
# The output has the formats:
#     pci:<class>:<class_prog>:<vendor>:<device>:<subsystem_vendor>:<subsystem_device>:<bus_id>
#     usb:<idVendor>:<idProduct>:<serial>
################################################################################

script='BEGIN
        {
            FS="\n"
            RS=""
            mm_uid=""
        }
        mm_uid !~ /^$/ { next }
        $1 !~ /^ *looking at / { next }
        {
            x = 1
            subsystem=""
            while ( x < NF ) {
                x++
                if ( $x ~ /^ *SUBSYSTEMS?=="pci"/ ) {
                    subsystem="pci"
                    break
                }
                if ( $x ~ /^ *SUBSYSTEMS?=="usb"/ ) {
                    subsystem="usb"
                    break
                }
            }
            if ( subsystem == "pci" ) {
                class=""
                class_prog=""
                vendor=""
                device=""
                subsystem_vendor=""
                subsystem_device=""
                bus_id=""
                while ( x < NF ) {
                    x++
                    if ( $x ~ /^ *ATTRS?\{vendor\}==/ ) {
                        vendor=$x
                        sub(/^ *ATTRS?\{vendor\}=="0x/, "", vendor)
                        sub(/"$/, "", vendor)
                    }
                    if ( $x ~ /^ *ATTRS?\{device\}==/ ) {
                        device=$x
                        sub(/^ *ATTRS?\{device\}=="0x/, "", device)
                        sub(/"$/, "", device)
                    }
                    if ( $x ~ /^ *ATTRS?\{subsystem_vendor\}==/ ) {
                        subsystem_vendor=$x
                        sub(/^ *ATTRS?\{subsystem_vendor\}=="0x/, "", subsystem_vendor)
                        sub(/"$/, "", subsystem_vendor)
                    }
                    if ( $x ~ /^ *ATTRS?\{subsystem_device\}==/ ) {
                        subsystem_device=$x
                        sub(/^ *ATTRS?\{subsystem_device\}=="0x/, "", subsystem_device)
                        sub(/"$/, "", subsystem_device)
                    }
                    if ( $x ~ /^ *KERNELS?==/ ) {
                        bus_id=$x
                        sub(/^ *KERNELS=="/, "", bus_id)
                        sub(/"$/, "", bus_id)
                    }
                }
                if ( class && class_prog && vendor && device && subsystem_vendor && subsystem_device && bus_id ) {
                    mm_uid="pci:" class ":" class_prog ":" vendor ":" device ":" subsystem_vendor ":" subsystem_device ":" bus_id
                }
            }
            if ( subsystem == "usb" ) {
                idVendor=""
                idProduct=""
                serial=""
                while ( x < NF ) {
                    x++
                    if ( $x ~ /^ *ATTRS?\{idVendor\}==/ ) {
                        idVendor=$x
                        sub(/^ *ATTRS?\{idVendor\}=="/, "", idVendor)
                        sub(/"$/, "", idVendor)
                        if ( idVendor == "0000" ) {
                            idVendor=""
                        }
                    }
                    if ( $x ~ /^ *ATTRS?\{idProduct\}==/ ) {
                        idProduct=$x
                        sub(/^ *ATTRS?\{idProduct\}=="/, "", idProduct)
                        sub(/"$/, "", idProduct)
                        if ( idProduct == "0000" ) {
                            idProduct=""
                        }
                    }
                    if ( $x ~ /^ *ATTRS?\{serial\}==/ ) {
                        serial=$x
                        sub(/^ *ATTRS?\{serial\}=="/, "", serial)
                        sub(/"$/, "", serial)
                    }
                }
                if ( idVendor && idProduct && serial) {
                    mm_uid="usb:" idVendor ":" idProduct ":" serial
                }
            }
            if ( mm_uid ) {
                print mm_uid
            }
        }'

/sbin/udevadm info --attribute-walk --path ${DEVPATH} | /usr/bin/awk "${script}"

exit 0
