#!/bin/sh
################################################################################
# audio
################################################################################
. /etc/rc.d/functions

start() {
    mm_message_output info 'configuring audio ...'

    # Wait for audio driver to load.
    timeout=10
    while [ ! `amixer > /dev/null 2>&1 ; echo $?` = "0" ] && [ ! "${timeout}" = "0" ] ; do
        sleep 1
        timeout=$((timeout-1))
    done
    if [ ! `amixer > /dev/null 2>&1 ; echo $?` = "0" ] ; then
        mm_message_output err "error: the audio driver does not appear to be loaded."
        exit 1
    fi

    # Unmute audio.
    if [ `amixer > /dev/null 2>&1 ; echo $?` = "0" ] ; then
        amixer | grep -e '^Simple mixer control' | sed -e "s%^[^']*'%%" | sed -e "s%'[^']*$%%" |
        while read control ; do
            case "${MM_AUDIO_TYPE}" in
                analog)
                    sed -i 's%@SPEAKER_ARRANGEMENT@%Stereo 2.0%'   /root/.xine/config
                    case "${control}" in
                        # General unmuting.
                        PCM)                         amixer set 'PCM'                       90% unmute ;;
                        Master)                      amixer set 'Master'                    90% unmute ;;
                        Front)                       amixer set 'Front'                     90% unmute ;;
                        Surround)                    amixer set 'Surround'                  90% unmute ;;
                        Center)                      amixer set 'Center'                    90% unmute ;;
                        LFE)                         amixer set 'LFE'                       90% unmute ;;
                        # VIA Specific unmuting.
                        VIA\ DXS)                    amixer set 'VIA DXS'                   100%       ;;
                    esac
                    ;;
                digital)
                    sed -i 's%@SPEAKER_ARRANGEMENT@%Pass Through%' /root/.xine/config
                    case "${control}" in
                        # General unmuting.
                        IEC958)                      amixer set 'IEC958'                    on         ;;
                        # VIA Specific unmuting.
                        IEC958\ Playback\ AC97-SPSA) amixer set 'IEC958 Playback AC97-SPSA' 0          ;;
                    esac
                    ;;
                digital+analog)
                    sed -i 's%@SPEAKER_ARRANGEMENT@%Pass Through%' /root/.xine/config
                    case "${control}" in
                        # General unmuting.
                        IEC958)                      amixer set 'IEC958'                    on         ;;
                        PCM)                         amixer set 'PCM'                       90% unmute ;;
                        Master)                      amixer set 'Master'                    90% unmute ;;
                        Front)                       amixer set 'Front'                     90% unmute ;;
                        Surround)                    amixer set 'Surround'                  90% unmute ;;
                        Center)                      amixer set 'Center'                    90% unmute ;;
                        LFE)                         amixer set 'LFE'                       90% unmute ;;
                        # VIA Specific unmuting.
                        IEC958\ Playback\ AC97-SPSA) amixer set 'IEC958 Playback AC97-SPSA' 0          ;;
                        VIA\ DXS)                    amixer set 'VIA DXS'                   100%       ;;
                    esac
                    ;;
            esac
        done
    fi

    return 0
}

stop () {
    mm_message_output info 'muting audio ...'

    # Mute audio.
    if [ `amixer > /dev/null 2>&1 ; echo $?` = "0" ] ; then
        amixer | grep -e '^Simple mixer control' | sed -e "s%^[^']*'%%" | sed -e "s%'[^']*$%%" |
        while read control ; do
            case "${MM_AUDIO_TYPE}" in
                analog)
                    case "${control}" in
                        # General muting.
                        PCM)      amixer set 'PCM'      0% mute ;;
                        Master)   amixer set 'Master'   0% mute ;;
                        Front)    amixer set 'Front'    0% mute ;;
                        Surround) amixer set 'Surround' 0% mute ;;
                        Center)   amixer set 'Center'   0% mute ;;
                        LFE)      amixer set 'LFE'      0% mute ;;
                        # VIA Specific muting.
                        VIA\ DXS) amixer set 'VIA DXS'  0%      ;;
                    esac
                    ;;
                digital)
                    case "${control}" in
                        # General unmuting.
                        IEC958)   amixer set 'IEC958'   off     ;;
                    esac
                    ;;
                digital+analog)
                    case "${control}" in
                        # General unmuting.
                        IEC958)   amixer set 'IEC958'   off     ;;
                        PCM)      amixer set 'PCM'      0% mute ;;
                        Master)   amixer set 'Master'   0% mute ;;
                        Front)    amixer set 'Front'    0% mute ;;
                        Surround) amixer set 'Surround' 0% mute ;;
                        Center)   amixer set 'Center'   0% mute ;;
                        LFE)      amixer set 'LFE'      0% mute ;;
                        # VIA Specific muting.
                        VIA\ DXS) amixer set 'VIA DXS'  0%      ;;
                    esac
                    ;;
            esac
        done
    fi

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
