#!/bin/sh
################################################################################
# video
#
# The script configures and starts the mythbackend.
################################################################################
. /etc/rc.d/functions

start() {

    if /usr/bin/test "${MM_BACKEND_ENABLED}" = "yes" ; then
        mm_message_output info "starting MythTV backend ..."

        /usr/bin/mythbackend --daemon
    fi

    return 0
}

stop() {
    if /usr/bin/test -n "`/bin/pidof mythbackend`" ; then
        mm_message_output info "stopping MythTV backend ..."

        /usr/bin/killall mythbackend
    fi

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
