#!/bin/sh
################################################################################
# boot
################################################################################
. /etc/rc.d/functions

start() {
    # If the boot type is ide, then load the drivers needed to read the ide drive.
    if   /usr/bin/test "${MM_BOOT_TYPE}" = "ide" ; then
        mm_message_output info 'mounting IDE boot device ...'

        # Wait for /minimyth directory to mount.
        waiting_time=0
        while /usr/bin/test ! -d "/minimyth" ; do
            mm_message_output info "waiting for /minimyth directory to mount (${waiting_time}) ..."
            /bin/sleep 1
            waiting_time=$((waiting_time+1))
        done

    # If the boot type is usb, then load the drivers needed to read the usb drive.
    elif /usr/bin/test "${MM_BOOT_TYPE}" = "usb" ; then
        mm_message_output info 'mounting USB boot device ...'

        # Wait for /minimyth directory to mount.
        waiting_time=0
        while /usr/bin/test ! -d "/minimyth" ; do
            mm_message_output info "waiting for /minimyth directory to mount (${waiting_time}) ..."
            /bin/sleep 1
            waiting_time=$((waiting_time+1))
        done
    fi

    return 0
}

stop() {
    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
