#!/bin/sh
################################################################################
# conf
#
# This script retrieves and processes the MiniMyth configure file.
################################################################################
. /etc/rc.d/functions

conf_reset() {

    local tempfile
    local filter

    tempfile=`/bin/mktemp /tmp/minimyth.conf.XXXXXX`

    rm -rf ${tempfile}
    for filter in "$@" ; do
        if echo ${filter} | grep -q -e '_$' > /dev/null 2>&1 ; then
            set                                    | /bin/grep -e "^${filter}"  | /bin/sed -e 's%=.*%=%' >> ${tempfile}
            /bin/cat /etc/minimyth.d/minimyth.conf | /bin/grep -e "^${filter}"                           >> ${tempfile}
        else
            set                                    | /bin/grep -e "^${filter}=" | /bin/sed -e 's%=.*%=%' >> ${tempfile}
            /bin/cat /etc/minimyth.d/minimyth.conf | /bin/grep -e "^${filter}="                          >> ${tempfile}
        fi
    done
    . ${tempfile}
    rm -rf ${tempfile}
}

conf_variable_write() {
    /bin/echo -n "$2=" >> $1
    /bin/echo -n "'"   >> $1
    /bin/echo -n "$3"  >> $1
    /bin/echo    "'"   >> $1

    return 0
}

start() {
    mm_message_output info 'processing configuration ...'

    # Get MiniMyth configuration file.
    mm_conf_get /minimyth.conf /etc/minimyth.d/minimyth.conf

    # Make sure that there is a MiniMyth configuration file.
    if /usr/bin/test ! -e /etc/minimyth.d/minimyth.conf ; then
        mm_message_output err 'error: MiniMyth configuration file not found.'
        exit 1
    fi
    if /usr/bin/test ! -r /etc/minimyth.d/minimyth.conf ; then
        mm_message_output err 'error: MiniMyth configuration file not readable.'
        exit 1
    fi

    # Read MiniMyth configuration file.
    . /etc/minimyth.d/minimyth.conf

    # Read MiniMyth configuration processing files
    for file in `cd /etc/rc.d/init.d/conf.d ; ls -1` ; do
        . /etc/rc.d/init.d/conf.d/${file}
    done

    # Check MiniMyth configuration variables.
    for file in `cd /etc/rc.d/init.d/conf.d ; ls -1` ; do
        conf_check_${file}
    done

    # Set default MiniMyth configuration variable values.
    for file in `cd /etc/rc.d/init.d/conf.d ; ls -1` ; do
        conf_default_${file}
    done

    # Write processed MiniMyth configuration file.
    /bin/rm -rf '/etc/conf.d/minimyth'
    for file in `cd /etc/rc.d/init.d/conf.d ; ls -1` ; do
        conf_write_${file} '/etc/conf.d/minimyth'
    done

    return 0
}

stop() {
    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
