#!/bin/sh
################################################################################
# conf
#
# This script retrieves and processes the MiniMyth configure file.
################################################################################
. /etc/rc.d/functions

conf_variable_write() {
    /bin/echo -n ${2} >> ${1}
    /bin/echo -n "="  >> ${1}
    /bin/echo -n "'"  >> ${1}
    /bin/echo -n ${3} >> ${1}
    /bin/echo    "'"  >> ${1}

    return 0
}

start() {
    mm_message_output info "processing configuration ..."

    # Get MiniMyth configuration file.
    mm_conf_get /minimyth.conf /etc/minimyth.d/minimyth.conf

    # Make sure that there is a MiniMyth configuration file.
    if /usr/bin/test ! -e /etc/minimyth.d/minimyth.conf ; then
        mm_message_output err "error: 'minimyth.conf' not found."
        exit 1
    fi
    if /usr/bin/test ! -r /etc/minimyth.d/minimyth.conf ; then
        mm_message_output err "error: 'minimyth.conf' not readable."
        exit 1
    fi

    # Unset variables set by the processed MiniMyth configuration file, except MM_DEBUG.
    # This is a hack for testing. It should never get invoked during normal boot.
    if /usr/bin/test -e /etc/conf.d/minimyth ; then
        /bin/cat /etc/conf.d/minimyth | /bin/grep -e '^MM_[^=]*=' | /bin/sed -e 's%=.*$%%' | \
        while read variable ; do
            if /usr/bin/test ! "${variable}" = "MM_DEBUG" ; then
                set ${variable}=''
            fi
        done
    fi

    # Read core and dhcp configuration files.
    /usr/bin/test -e /etc/conf.d/core && . /etc/conf.d/core
    /usr/bin/test -e /etc/conf.d/dhcp && . /etc/conf.d/dhcp

    # Read MiniMyth configuration file.
    . /etc/minimyth.d/minimyth.conf

    # Read MiniMyth configuration processing files
    for file in `cd /etc/rc.d/init.d/conf.d ; /bin/ls -1` ; do
        . /etc/rc.d/init.d/conf.d/${file}
    done

    # Clean configuration processing file state.
    for file in `cd /etc/rc.d/init.d/conf.d ; /bin/ls -1` ; do
        conf_clean_${file}
    done

    # Check MiniMyth configuration variables.
    mm_message_output info "processing configuration: checking variables ..."
    for file in `cd /etc/rc.d/init.d/conf.d ; /bin/ls -1` ; do
        /usr/bin/logger -s -t minimyth -p "local0.info" "    checking variables for ${file}"
        conf_check_${file}
    done

    # Set default MiniMyth configuration variable values.
    mm_message_output info "processing configuration: defaulting variables ..."
    for file in `cd /etc/rc.d/init.d/conf.d ; /bin/ls -1` ; do
        /usr/bin/logger -s -t minimyth -p "local0.info" "    defaulting variables for ${file}"
        conf_default_${file}
    done

    # Write processed MiniMyth configuration file.
    mm_message_output info "processing configuration: writing variables ..."
    /bin/rm -rf '/etc/conf.d/minimyth~'
    for file in `cd /etc/rc.d/init.d/conf.d ; /bin/ls -1` ; do
        /usr/bin/logger -s -t minimyth -p "local0.info" "    writing variables for ${file}"
        conf_write_${file} '/etc/conf.d/minimyth~'
    done
    /bin/rm -rf '/etc/conf.d/minimyth'
    /usr/bin/sort '/etc/conf.d/minimyth~' > '/etc/conf.d/minimyth'
    /bin/rm -rf '/etc/conf.d/minimyth~'

    # Fetch user files.
    mm_message_output info "processing configuration: fetching additional files ..."
    for file in `cd /etc/rc.d/init.d/conf.d ; /bin/ls -1` ; do
        /usr/bin/logger -s -t minimyth -p "local0.info" "    fetching additional files for ${file}"
        conf_fetch_${file}
    done

    # Clean configuration processing file state.
    for file in `cd /etc/rc.d/init.d/conf.d ; /bin/ls -1` ; do
        conf_clean_${file}
    done

    # If there are any errors, then do not continue
    if /usr/bin/test -e /var/log/minimyth.err.log &&
       /usr/bin/test `/bin/cat /var/log/minimyth.err.log | /usr/bin/wc -l` -gt 0 ; then
        # If telnet is not running, then start it so that the user can check the error logs.
        if /usr/bin/test -z "`/bin/pidof telnetd`" ; then
            /usr/sbin/telnetd -l /bin/login
        fi
        mm_message_output err "error: check '/var/log/minimyth.err.log' for details."
        exit 1
    fi

    return 0
}

stop() {
    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
