#!/bin/sh
################################################################################
# extras
#
# This script (downloads and) mounts the extras directory tree.
################################################################################
. /etc/rc.d/functions

start() {
    mm_message_output info 'installing extras ...'

    if /usr/bin/test "${MM_EXTRAS_URL}" = "default" ; then
        INITRD_DIR=` /bin/echo ${initrd} | /bin/sed 's%[^/]*$%%'`
        INITRD_FILE=`/bin/echo ${initrd} | /bin/sed 's%^.*/%%'`
        INITRD_FILE_PREFIX=`/bin/echo ${INITRD_FILE} | /bin/sed 's%-.*$%%'`
        if /usr/bin/test "${INITRD_FILE_PREFIX}" = "rootfs" ; then
            EXTRAS_DIR="${INITRD_DIR}"
            EXTRAS_FILE=`/bin/echo ${INITRD_FILE} | /bin/sed 's%^rootfs%extras%'`.sfs
            if /usr/bin/test -d "/minimyth" ; then
                MM_EXTRAS_URL="file:/minimyth/${EXTRAS_DIR}${EXTRAS_FILE}"
            else
                MM_EXTRAS_URL="tftp://${MM_TFTP_SERVER}/${MM_TFTP_ROOTDIR}/${EXTRAS_DIR}${EXTRAS_FILE}"
            fi
        else
            MM_EXTRAS_URL=
        fi
    fi
    if /usr/bin/test -n "${MM_EXTRAS_URL}" ; then
        mm_url_mount "${MM_EXTRAS_URL}" "@EXTRAS_ROOTDIR@"
        /usr/sbin/ldconfig
    fi

    return 0
}

stop() {
    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
