#!/bin/sh
################################################################################
# lcdproc
################################################################################
. /etc/rc.d/functions

start() {
    mm_message_output info 'starting LCD/VFD ...'

    # Only start the LCDd daemon when one is not running already.
    if /usr/bin/test -z "`/bin/pidof LCDd`" ; then
        # Load the LCDproc configuration file.
        if /usr/bin/test ! -e /etc/LCDd.conf ; then
            if /usr/bin/test -n "${MM_LCDPROC_DRIVER}" ; then
                if /usr/bin/test -e /etc/lcdproc.d/LCDd.conf.${MM_LCDPROC_DRIVER} ; then
                    cp /etc/lcdproc.d/LCDd.conf.${MM_LCDPROC_DRIVER} /etc/LCDd.conf
                else
                    cp /etc/lcdproc.d/LCDd.conf                      /etc/LCDd.conf
                fi
            fi
        fi

        if /usr/bin/test -e /etc/LCDd.conf ; then
            # Set the driver.
            /bin/sed -i "s%@MM_LCDPROC_DRIVER@%${MM_LCDPROC_DRIVER}%" /etc/LCDd.conf
            # Start LCDproc LCDd daemon and Myth LCD server.
            /usr/sbin/LCDd -c /etc/LCDd.conf
        fi
    fi

    # Enable LCD in MythTV.
    if /usr/bin/test -n "`/bin/pidof LCDd`" ; then
        mm_mythdb_settings_set "LCDEnable" "1"
    else
        mm_mythdb_settings_set "LCDEnable" "0"
    fi

    return 0
}


stop() {
    mm_message_output info 'stopping LCD/VFD display ...'

    /usr/bin/test -n "`/bin/pidof LCDd`" && /usr/bin/killall LCDd

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
