#!/bin/sh
################################################################################
# ld
################################################################################
. /etc/rc.d/functions

start() {
    mm_message_output info 'configuring shared libraries ...'

    ldconfig -f /etc/ld.so.conf -C /etc/ld.so.cache

    return 0
}

stop() {
    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
