#!/bin/sh
################################################################################
# log
################################################################################
. /etc/rc.d/functions

start() {
    mm_message_output info 'starting system logging ...'

    [ -n "`pidof klogd`" ]   && killall klogd
    [ -n "`pidof syslogd`" ] && killall syslogd
    # The network interface is not up yet, so (re)start only local syslogd.
    if [ -z "`pidof udhcpc`" ] ; then
        syslogd
    # The network interface is up, so (re)start both local/remote syslogd and klogd.
    else
        if [ -n "${MM_LOG_SERVER}" ] ; then
            syslogd -R "${MM_LOG_SERVER}"
        else
            syslogd
        fi
        klogd
    fi
}

stop() {
    mm_message_output info 'stopping system logging ...'

    [ -n "`pidof klogd`" ]   && killall klogd
    [ -n "`pidof syslogd`" ] && killall syslogd
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit $?
