#!/bin/sh
################################################################################
# log
################################################################################
. /etc/rc.d/functions

start() {
    mm_message_output info 'starting system logging ...'

    /usr/bin/test -n "`/bin/pidof klogd`"   && /usr/bin/killall klogd
    /usr/bin/test -n "`/bin/pidof syslogd`" && /usr/bin/killall syslogd
    # The network interface is not up yet, so (re)start only local syslogd.
    if /usr/bin/test -z "`/bin/pidof udhcpc`" ; then
        /sbin/syslogd
    # The network interface is up, so (re)start both local/remote syslogd and klogd.
    else
        if /usr/bin/test -n "${MM_LOG_SERVER}" ; then
            /sbin/syslogd -R "${MM_LOG_SERVER}"
        else
            /sbin/syslogd
        fi
        /sbin/klogd
    fi
}

stop() {
    mm_message_output info 'stopping system logging ...'

    /usr/bin/test -n "`/bin/pidof klogd`"   && /usr/bin/killall klogd
    /usr/bin/test -n "`/bin/pidof syslogd`" && /usr/bin/killall syslogd
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
