#!/bin/sh
################################################################################
# modules
################################################################################
. /etc/rc.d/functions

start() {
    mm_message_output info 'loading kernel modules ...'

    # ACPI.
    modprobe button
    modprobe fan
    modprobe processor
    modprobe thermal
    modprobe video

    # Real time clock.
    modprobe rtc

    # Input.
    modprobe evdev
    modprobe psmouse

    # Sensors.
    case "${MM_HARDWARE_SENSOR}" in
        VT1211)
            modprobe i2c-core
            modprobe i2c-dev
            modprobe i2c-isa
            modprobe vt1211
            ;;
        W83627EHG)
            modprobe i2c-core
            modprobe i2c-dev
            modprobe i2c-isa
            case "${MM_HARDWARE_SOUTHBRIDGE}" in
                NFORCE_430)
                    modprobe i2c-nforce2
                    ;;
            esac
            modprobe w83627ehf
            ;;
        W83782D)
            modprobe i2c-core
            modprobe i2c-dev
            modprobe i2c-isa
            case "${MM_HARDWARE_SOUTHBRIDGE}" in
                VT8235|VT8237)
                    modprobe i2c-viapro
                    ;;
            esac
            modprobe w83781d
            ;;
    esac

    # IO scheduler.
    modprobe as-iosched

    # Loopback device.
    modprobe loop

    # IDE.
    case "${MM_HARDWARE_SOUTHBRIDGE}" in
        NFORCE_430)
            modprobe amd74xx
            ;;
        VT8235|VT8237)
            modprobe via82cxxx
            ;;
    esac
    modprobe ide-core
    modprobe ide-cd

    # IEEE1394 (firewire).
    modprobe ieee1394
    modprobe ohci1394
    modprobe sbp2

    # Parallel port.
    modprobe parport
    modprobe parport_pc
    modprobe ppdev

    # USB.
    modprobe usbcore
    modprobe ehci-hcd
    modprobe uhci-hcd
    modprobe usbhid
    modprobe usblcd
    modprobe usb-storage
    modprobe usbserial
    modprobe ftdi-sio

    # SCSI (used by USB devices).
    modprobe sd_mod
    modprobe sr_mod

    # CD-ROM.
    modprobe cdrom

    # File systems.
    modprobe nls_ascii
    modprobe nls_base
    modprobe nls_cp437
    modprobe nls_cp850
    modprobe nls_iso8859-1
    modprobe nls_iso8859-15
    modprobe nls_utf8
    modprobe cifs
    modprobe fat
    modprobe isofs
    modprobe msdos
    modprobe smbfs
    modprobe udf
    modprobe vfat

    # Net.
    modprobe af_packet
    modprobe unix

    # Sound.
    modprobe soundcore
    case "${MM_HARDWARE_AUDIO}" in
        AD1986A)
            modprobe snd-hda-intel
            ;;
        VT1612A|VT1616|VT1617A)
            modprobe snd-via82xx
            ;;
    esac

    # Video.
    modprobe agpgart
    case "${MM_HARDWARE_NORTHBRIDGE}" in
        GFORCE_6150)
            modprobe nvidia-agp
            modprobe nvidia
            ;;
        CLE2666|CN400)
            modprobe via-agp
            modprobe via
            ;;
    esac


    return 0
}

stop() {
    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
