#!/bin/sh
################################################################################
# network
################################################################################
. /etc/rc.d/functions

conf_variable_write() {
    /bin/echo -n ${2} >> ${1}
    /bin/echo -n "="  >> ${1}
    /bin/echo -n "'"  >> ${1}
    /bin/echo -n ${3} >> ${1}
    /bin/echo    "'"  >> ${1}

    return 0
}

start() {

    local DHCP_CONF
    local ip_address

    mm_message_output info "starting network ..."

    # Write DCHP override parameters to the DHCP override file.
    DHCP_CONF=/etc/conf.d/dhcp.override
    /bin/rm -f "${DHCP_CONF}~"
    /bin/touch "${DHCP_CONF}~"
    /usr/bin/test -n "${MM_DHCP_HOSTNAME}"         && \
        conf_variable_write ${DHCP_CONF}~ MM_DHCP_HOSTNAME       "${MM_DHCP_HOSTNAME}"
    /usr/bin/test -n "${MM_DHCP_DOMAIN}"           && \
        conf_variable_write ${DHCP_CONF}~ MM_DHCP_DOMAIN         "${MM_DHCP_DOMAIN}"
    /usr/bin/test -n "${MM_DHCP_DNS_SERVERS}"      && \
        conf_variable_write ${DHCP_CONF}~ MM_DHCP_DNS_SERVERS    "${MM_DHCP_DNS_SERVERS}"
    /usr/bin/test -n "${MM_DHCP_NTP_SERVERS}"      && \
        conf_variable_write ${DHCP_CONF}~ MM_DHCP_NTP_SERVERS    "${MM_DHCP_NTP_SERVERS}"
    /usr/bin/test -n "${MM_DHCP_LOG_SERVERS}"      && \
        conf_variable_write ${DHCP_CONF}~ MM_DHCP_LOG_SERVERS    "${MM_DHCP_LOG_SERVERS}"
    /usr/bin/test -n "${MM_DHCP_TZ}"               && \
        conf_variable_write ${DHCP_CONF}~ MM_DHCP_TZ             "${MM_DHCP_TZ}"
    /usr/bin/test -n "${MM_DHCP_BOOT_URL}"         && \
        conf_variable_write ${DHCP_CONF}~ MM_DHCP_BOOT_URL       "${MM_DHCP_BOOT_URL}"
    /usr/bin/test -n "${MM_DHCP_SECURITY_ENABLED}" && \
        conf_variable_write ${DHCP_CONF}~ MM_DHCP_SECURITY_LEVEL "${MM_DHCP_SECURITY_LEVEL}"
    /bin/mv -f "${DHCP_CONF}~" "${DHCP_CONF}"

    # Bring up the local (loopback) interface.
    /sbin/ifconfig lo 127.0.0.1

    /sbin/ifconfig > /var/log/ifconfig.log

    # Get the IP address and other IP parameters.
    # If an IP address was already obtained then request the same address.
    ip_address=`/sbin/ifconfig eth0 | /bin/grep '^ *inet addr:' | /bin/sed 's%^ *inet addr:\([^ ]*\) .*%\1%'`
    if /usr/bin/test -n "${ip_address}" ; then
        /bin/echo "fixed-address ${ip_address} ;" >> /etc/dhclient.conf
    fi
    /bin/mkdir -p /var/db
    /usr/sbin/dhclient eth0
    if /usr/bin/test $? -ne 0 ; then
        mm_message_output err "error: DHCP failed."
        exit 1
    fi
    ip_address=`/sbin/ifconfig eth0 | /bin/grep '^ *inet addr:' | /bin/sed 's%^ *inet addr:\([^ ]*\) .*%\1%'`
    if /usr/bin/test -z "${ip_address}" ; then
        mm_message_output err "error: DHCP failed."
        exit 1
    fi

    # Start portmap on local interface.
    /sbin/portmap -l

    return 0
}

stop() {
    mm_message_output info "stopping network ..."

    /usr/bin/test -n "`/bin/pidof portmap`" && /usr/bin/killall portmap
    /usr/bin/test -n "`/bin/pidof udhcpc`"  && /usr/bin/killall udhcpc

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
