#!/bin/sh
################################################################################
# reboot
################################################################################
. /etc/rc.d/functions

start() {
    mm_message_output info 'rebooting system ...'
    /sbin/reboot -i

    return 0
}

stop() {
    start

    return $?
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit $?
