#!/bin/sh
################################################################################
# shutdown
################################################################################
. /etc/rc.d/functions

start() {
    mm_message_output info 'finishing shutdown ...'

    # unmount any remaining network file systems.
    cat /proc/mounts | while read mountpoint; do
        mountpoint=`echo ${mountline} | cut -d ' ' -f 2`
        mounttype=`echo  ${mountline} | cut -d ' ' -f 3`
        if [ "${mounttype}" = "cifs"  ] ||
           [ "${mounttype}" = "nfs"   ] ||
           [ "${mounttype}" = "smbfs" ] ; then
            umount -r ${mountpoint}
        fi
    done

    return 0
}

stop() {
    start

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
