#!/bin/sh
################################################################################
# ssh_remote
#
# This script configures ssh remote command execution.
################################################################################
. /etc/rc.d/functions

start() {
    mm_message_output info "configuring ssh remote command execution ..."

    if /usr/bin/test -e /etc/ssh/id_rsa ; then
        /bin/chmod 0600 /etc/ssh/id_rsa
        /bin/chown root:root /etc/ssh/id_rsa

        /bin/mkdir -p /root/.ssh
        /bin/cp /etc/ssh/id_rsa /root/.ssh/id_rsa
        /bin/chmod 0600 /root/.ssh/id_rsa
        /bin/chown root:root /root/.ssh/id_rsa

        /bin/mkdir -p /home/minimyth/.ssh
        /bin/cp /etc/ssh/id_rsa /home/minimyth/.ssh/id_rsa
        /bin/chmod 0600 /home/minimyth/.ssh/id_rsa
        /bin/chown root:root /home/minimyth/.ssh/id_rsa
    fi

    if /usr/bin/test "${MM_SSH_REMOTE_ENABLED}" = "yes" ; then
        if /usr/bin/test "${MM_MYTHSTREAM_ENABLED}" = "yes" ; then
            mm_ssh_remote_put /dev/null /usr/share/mythtv/mythstream/parsers
        fi
        if /usr/bin/test "${MM_MYTHVIDEO_ENABLED}" = "yes" ; then
            mm_ssh_remote_put /dev/null /usr/share/mythtv/mythvideo/scripts
        fi
    fi

    return 0
}

stop() {
    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
