#!/bin/sh
################################################################################
# telnet
################################################################################
. /etc/rc.d/functions

start() {
    mm_message_output info 'starting telnet ...'

    telnetd -l /bin/sh

    return 0
}

stop() {
    mm_message_output info 'stopping telnet ...'

    [ -n "`pidof telnetd`" ] && killall telnetd

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
