#!/bin/sh
################################################################################
# time
################################################################################
. /etc/rc.d/functions

start() {

    local NTP_SERVER
    local NTP_SERVERS
    local NTP_SUCCESS

    # Set time.
    mm_message_output info "setting time ..."
    /usr/bin/ntpd -p /var/run/ntpd.pid -q -g
    if /usr/bin/test $? -eq 0 ; then
        mm_message_output warn "warning: 'ntpd' failed to synchronize with any NTP server." 
    fi

    # Start NTP daemon.
    mm_message_output info "starting NTP daemon ..."
    /usr/bin/ntpd -p /var/run/ntpd.pid

    return 0
}

stop() {
    mm_message_output info "saving time ..."

    if /usr/bin/test -n "`/bin/pidof ntpd`" ; then
        /usr/bin/killall ntpd
        /sbin/hwclock --systohc --utc
    fi

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
