#!/bin/sh
################################################################################
# time
################################################################################
. /etc/rc.d/functions

start() {
    mm_message_output info 'starting NTP client ...'

    # Set and check localtime file.
    if [ ! -z "${MM_TZ}" ] ; then
        cp /usr/share/zoneinfo/${MM_TZ} /etc/localtime
    else
        mm_message_output err 'error: "MM_TZ" not present.'
        exit 1
    fi

    # Check for NTP time servers.
    for i in `cat /etc/ntp.conf | grep '^server ' | sed 's%^server %%'` ; do
        if [ -z "${TIME_SERVER}" ] ; then
            TIME_SERVER="$i"
        fi
    done
    if [ -z "${TIME_SERVER}" ] ; then
        mm_message_output err 'error: no NTP server(s) provided.'
        exit 1
    fi

    ntpdate ${TIME_SERVER}
    ntpd

    return 0
}

stop() {
    mm_message_output info 'stopping NTP client ...'

    [ -n "`pidof ntpd`" ] && killall ntpd

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
