#!/bin/sh
################################################################################
# usb-boot
################################################################################
. /etc/rc.d/functions

start() {
    mm_message_output info 'mounting USB boot device ...'

    # If the boot type is usb, then load the drivers needed to read the usb drive.
    if [ "${MM_BOOT_TYPE}" = "usb" ] ; then
        lspci -mn | grep -e '^[^ ][^ ]*  *"0c03"' | sed -e 's%"%%g' | while read pci ; do
            if   [ `echo "${pci}" | grep -c -e ' -p20'` = "1" ] ; then
	        modprobe ehci-hcd
            elif [ `echo "${pci}" | grep -c -e ' -p10'` = "1" ] ; then
	        modprobe ohci-hcd
            else
	        modprobe uhci-hcd
            fi
	done
        modprobe usb-storage
        modprobe sd_mod
        modprobe msdos
        # Wait for USB boot device to mount.
        waiting_time=0
        while [ ! -e /media/minimyth ] ; do
            mm_message_output info "waiting for USB boot device to mount (${waiting_time}) ..."
            sleep 1
            waiting_time=$((waiting_time+1))
        done
    fi

    # Get MiniMyth DCHP defaults,
    # allowing USB booted MiniMyth to work with limited DHCP servers.
    mm_conf_get /minimyth.dhcp /etc/minimyth.d/minimyth.dhcp

    return 0
}

stop() {
    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
