#!/bin/sh
################################################################################
# video
#
# The script configures the video.
################################################################################
. /etc/rc.d/functions

start() {

    local kernel_module
    local PREFERRED_MPEG2_DECODER
    local DEINTERLACE_FILTER

    mm_message_output info 'configuring video ...'

    PREFERRED_MPEG2_DECODER=''
    case "${MM_X_DRIVER}" in
        intel_810)
            /bin/sed -i "s%@MM_XVMC_LIB@%I810XvMC%"           /etc/X11/XvMCConfig
            PREFERRED_MPEG2_DECODER='xvmc'
            /bin/sed -i "s%@VIDEO_DRIVER@%xvmc%"              /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_TRUE@%%"                     /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_FALSE@%\#%"                  /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_TRUE@%%"                     /home/minimyth/.mplayer/config
            /bin/sed -i "s%@XVMC_FALSE@%\#%"                  /home/minimyth/.mplayer/config
            ;;
        intel_915)
            PREFERRED_MPEG2_DECODER='ffmpeg'
            /bin/sed -i "s%@VIDEO_DRIVER@%xv%"                /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_TRUE@%\#%"                   /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_FALSE@%%"                    /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_TRUE@%\#%"                   /home/minimyth/.mplayer/config
            /bin/sed -i "s%@XVMC_FALSE@%%"                    /home/minimyth/.mplayer/config
            ;;
        nvidia)
            /bin/sed -i "s%@MM_XVMC_LIB@%XvMCNVIDIA_dynamic%" /etc/X11/XvMCConfig
            # this should really be the more efficient 'libmpeg2',
            # but it causes stalls during when fast forwarding and rewinding.
            PREFERRED_MPEG2_DECODER='ffmpeg'
            /bin/sed -i "s%@VIDEO_DRIVER@%xv%"                /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_TRUE@%\#%"                   /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_FALSE@%%"                    /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_TRUE@%\#%"                   /home/minimyth/.mplayer/config
            /bin/sed -i "s%@XVMC_FALSE@%%"                    /home/minimyth/.mplayer/config
            ;;
        via)
            /bin/sed -i "s%@MM_XVMC_LIB@%viaXvMC%"            /etc/X11/XvMCConfig
            PREFERRED_MPEG2_DECODER='xvmc-vld'
            /bin/sed -i "s%@VIDEO_DRIVER@%xxmc%"              /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_TRUE@%%"                     /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_FALSE@%\#%"                  /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_TRUE@%%"                     /home/minimyth/.mplayer/config
            /bin/sed -i "s%@XVMC_FALSE@%\#%"                  /home/minimyth/.mplayer/config
            mm_mythdb_settings_set "UseChromaKeyOSD" "1"
            ;;
        via_pro)
            /bin/sed -i "s%@MM_XVMC_LIB@%viaXvMCPro%"         /etc/X11/XvMCConfig
            PREFERRED_MPEG2_DECODER='xvmc-vld'
            /bin/sed -i "s%@VIDEO_DRIVER@%xxmc%"              /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_TRUE@%%"                     /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_FALSE@%\#%"                  /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_TRUE@%%"                     /home/minimyth/.mplayer/config
            /bin/sed -i "s%@XVMC_FALSE@%\#%"                  /home/minimyth/.mplayer/config
            mm_mythdb_settings_set "UseChromaKeyOSD" "1"
            ;;
        vmware)
            PREFERRED_MPEG2_DECODER='ffmpeg'
            /bin/sed -i "s%@VIDEO_DRIVER@%xv%"                /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_TRUE@%\#%"                   /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_FALSE@%%"                    /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_TRUE@%\#%"                   /home/minimyth/.mplayer/config
            /bin/sed -i "s%@XVMC_FALSE@%%"                    /home/minimyth/.mplayer/config
            ;;
    esac

    case "${PREFERRED_MPEG2_DECODER}" in
        ffmpeg)
            mm_mythdb_settings_update PreferredMPEG2Decoder ${PREFERRED_MPEG2_DECODER}
            ;;
        libmpeg2)
            mm_mythdb_settings_update PreferredMPEG2Decoder ${PREFERRED_MPEG2_DECODER}
            ;;
        xvmc)
            mm_mythdb_settings_update PreferredMPEG2Decoder ${PREFERRED_MPEG2_DECODER}
            ;;
        xvmc-vld)
            mm_mythdb_settings_update PreferredMPEG2Decoder ${PREFERRED_MPEG2_DECODER}
            ;;
    esac

    if   /usr/bin/test "${MM_VIDEO_DEINTERLACE_ENABLED}" = "no"  ; then
        mm_mythdb_settings_update Deinterlace 0
        /bin/sed -i "s%@DEINTERLACE_BY_DEFAULT@%0%" /home/minimyth/.xine/config
        /bin/sed -i "s%@XVMC_BOB_DEINTERLACING@%0%" /home/minimyth/.xine/config
        /bin/sed -i "s%@BOBDEINT@%%"                /home/minimyth/.mplayer/config
    elif /usr/bin/test "${MM_VIDEO_DEINTERLACE_ENABLED}" = "yes" ; then
        case ${PREFERRED_MPEG2_DECODER} in
            ffmpeg)
                if /bin/cat /proc/cpuinfo | /bin/grep -e '^flags' | /bin/grep -q -e ' sse ' > /dev/null 2>&1 ; then
                    DEINTERLACE_FILTER='kerneldeint'
                else
                    DEINTERLACE_FILTER='linearblend'
                fi
                ;;
            libmpeg2)
                if /bin/cat /proc/cpuinfo | /bin/grep -e '^flags' | /bin/grep -q -e ' sse ' > /dev/null 2>&1 ; then
                    DEINTERLACE_FILTER='kerneldeint'
                else
                    DEINTERLACE_FILTER='linearblend'
                fi
                ;;
            xvmc)
                DEINTERLACE_FILTER='bobdeint'
                ;;
            xvmc-vld)
                DEINTERLACE_FILTER='bobdeint'
                ;;
            *)
                if /bin/cat /proc/cpuinfo | /bin/grep -e '^flags' | /bin/grep -q -e ' sse ' > /dev/null 2>&1 ; then
                    DEINTERLACE_FILTER='kerneldeint'
                else
                    DEINTERLACE_FILTER='linearblend'
                fi
                ;;
        esac
        mm_mythdb_settings_update Deinterlace 1
        mm_mythdb_settings_update DeinterlaceFilter ${DEINTERLACE_FILTER}
        /bin/sed -i "s%@DEINTERLACE_BY_DEFAULT@%1%" /home/minimyth/.xine/config
        /bin/sed -i "s%@XVMC_BOB_DEINTERLACING@%1%" /home/minimyth/.xine/config
        /bin/sed -i "s%@BOBDEINT@%:bobdeint%"       /home/minimyth/.mplayer/config
    else
        mm_message_output err "error: something is very wrong in the 'video' init script."
        exit 1
    fi

    if   /usr/bin/test "${MM_VIDEO_ASPECT_RATIO}" = "4:3"  ; then
        /bin/sed -i "s%@MONITORASPECT@%4:3%"  /home/minimyth/.mplayer/config
    elif /usr/bin/test "${MM_VIDEO_ASPECT_RATIO}" = "16:9" ; then
        /bin/sed -i "s%@MONITORASPECT@%16:9%" /home/minimyth/.mplayer/config
    else
        mm_message_output err "error: something is very wrong in the 'video' init script."
        exit 1
    fi

    return 0
}

stop() {
    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
