#!/bin/sh

. /etc/conf

page_host=`hostname`
page_date=`date +'%Y-%m-%d %H:%M:%S %Z'`

server=${HTTP_HOST:-${SERVER_ADDR}}

/bin/echo "Content-Type"content="text/html; charset=UTF-8"
/bin/echo
/bin/echo "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.1//EN\" \"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd\">"
/bin/echo "<html>"
/bin/echo "  <head>"
/bin/echo "    <meta name=\"author\" content=\"Paul Bender\" />"
/bin/echo "    <meta name=\"copyright\" content=\"2006 Paul Bender &amp; LinPVR.org\" />"
/bin/echo "    <meta name=\"keywords\" content=\"LinPVR,PVR,Linux,MythTV,MiniMyth\" />"
/bin/echo "    <meta name=\"description\" content=\"\" />"
/bin/echo "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />"
/bin/echo "    <title>MiniMyth Frontend Filesystem</title>"
/bin/echo "    <style type=\"text/css\">"
/bin/echo "      @import \"../css/linpvr.css\";"
/bin/echo "    </style>"
/bin/echo "  </head>"
/bin/echo "  <body>"
/bin/echo "    <div class=\"container\">"
/bin/echo "      <div class=\"watermark\">"
/bin/echo "        MiniMyth ${MM_VERSION}"
/bin/echo "        from"
/bin/echo "        <a href=\"http://linpvr.org/\">LinPVR.org</a><br />"
/bin/echo "        ${page_host}<br />"
/bin/echo "        ${page_date}"
/bin/echo "      </div>"
/bin/echo "      <div class=\"header\">"
/bin/echo "        <div class=\"banner\">"
/bin/echo "        </div>"
/bin/echo "      </div>"
/bin/echo "      <div class=\"sitemenu\">"
/bin/echo "        <span class=\"siteMenuItem\"><a href=\"../index.shtml\">Home</a></span>"
/bin/echo "        <span class=\"siteMenuItem\"><a href=\"filesystem.cgi\" class=\"active\">Filesystem</a></span>"
/bin/echo "      </div>"
/bin/echo "      <div class=\"pagebody\">"
/bin/echo "        <div class=\"content\">"
/bin/echo "          <div class=\"contentheader\">MiniMyth Frontend Filesystem</div>"
/bin/echo "          <div class=\"contentitem\">"
/bin/echo "           <p>"
/bin/echo "             You can use the URL <a href=\"http://${server}:8080/\">http://${server}:8080/</a> to access your MiniMyth frontend's filesystem."
/bin/echo "           </p>"
/bin/echo "          </div>"
/bin/echo "        </div> "
/bin/echo "        <div class=\"footer\">"
/bin/echo "          <hr />"
/bin/echo "          <a href=\"../index.shtml\">Home</a> |"
/bin/echo "          Filesystem"
/bin/echo "          <br />"
/bin/echo "          Last Updated: 2006-09-25 &lt;<a href=\"mailto:info at linpvr.org\">webmaster at linpvr.org</a>&gt;"
/bin/echo "        </div>"
/bin/echo "      </div>"
/bin/echo "    </div>"
/bin/echo "  </body>"
/bin/echo "</html>"
