#!/bin/sh
################################################################################
# g15daemon
################################################################################
. /etc/rc.d/functions

start() {

    if /usr/bin/test "${MM_LCDPROC_DRIVER}" = "g15" ; then
        m_message_output info "starting G15daemon ..."
        /sbin/modprobe uinput
        /usr/sbin/g15daemon
    fi

    return 0
}

stop() {

    if /usr/bin/test -n "`/bin/pidof g15daemon`" ; then
        mm_message_output info "stopping G15daemon ..."
        /usr/sbin/g15daemon -k
    fi

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
