#!/bin/sh
################################################################################
# audio
################################################################################
. /etc/rc.d/functions

start() {
    mm_message_output info 'configuring audio ...'

    case "${MM_HARDWARE_AUDIO}" in
        ANALOG_AD1986A)
            modprobe snd-hda-intel
            while [ ! `amixer > /dev/null 2>&1 ; echo $?` = "0" ] ; do sleep 1 ; done
            case "${MM_AUDIO_TYPE}" in
                analog)
                    sed -i 's%@SPEAKER_ARRANGEMENT@%Stereo 2.0%'   /root/.xine/config
                    amixer set 'PCM' 90% unmute 
                    amixer set 'Front' 90% unmute 
                    amixer set 'Surround' 90% unmute 
                    amixer set 'Center' 90% unmute 
                    amixer set 'LFE' 90% unmute 
                    ;;
                digital)
                    sed -i 's%@SPEAKER_ARRANGEMENT@%Pass Through%' /root/.xine/config
                    amixer set 'IEC958' on
                    ;;
                digital+analog)
                    sed -i 's%@SPEAKER_ARRANGEMENT@%Pass Through%' /root/.xine/config
                    amixer set 'IEC958' on
                    amixer set 'PCM' 90% unmute 
                    amixer set 'Front' 90% unmute 
                    amixer set 'Surround' 90% unmute 
                    amixer set 'Center' 90% unmute 
                    amixer set 'LFE' 90% unmute 
                    ;;
            esac
            ;;
        REALTEK_ALC655)
            modprobe snd-intel8x0
            while [ ! `amixer > /dev/null 2>&1 ; echo $?` = "0" ] ; do sleep 1 ; done
            case "${MM_AUDIO_TYPE}" in
                analog)
                    sed -i 's%@SPEAKER_ARRANGEMENT@%Stereo 2.0%'   /root/.xine/config
                    ;;
                digital)
                    sed -i 's%@SPEAKER_ARRANGEMENT@%Pass Through%' /root/.xine/config
                    ;;
                digital+analog)
                    sed -i 's%@SPEAKER_ARRANGEMENT@%Pass Through%' /root/.xine/config
                    ;;
            esac
            ;;
        VIA_VT1612A|VIA_VT1616|VIA_VT1617A)
            modprobe snd-via82xx
            while [ ! `amixer > /dev/null 2>&1 ; echo $?` = "0" ] ; do sleep 1 ; done
            case "${MM_AUDIO_TYPE}" in
                analog)
                    amixer set 'PCM' 90% unmute 
                    amixer set 'Master' 90% unmute 
                    amixer set 'VIA DXS',0 100%
                    sed -i 's%@SPEAKER_ARRANGEMENT@%Stereo 2.0%'   /root/.xine/config
                    ;;
                digital)
                    sed -i 's%@SPEAKER_ARRANGEMENT@%Pass Through%' /root/.xine/config
                    amixer set 'IEC958' on
                    amixer set 'IEC958 Playback AC97-SPSA' 0
                    amixer set 'VIA DXS',0 100%
                    ;;
                digital+analog)
                    sed -i 's%@SPEAKER_ARRANGEMENT@%Pass Through%' /root/.xine/config
                    amixer set 'IEC958' on
                    amixer set 'IEC958 Playback AC97-SPSA' 0
                    amixer set 'PCM' 90% unmute 
                    amixer set 'Master' 90% unmute 
                    amixer set 'VIA DXS',0 100%
                    ;;
            esac
            ;;
    esac

    return 0
}

stop () {
    mm_message_output info 'muting audio ...'

    case "${MM_HARDWARE_AUDIO}" in
        ANALOG_AD1986A)
           amixer set 'IEC958' off
           amixer set 'PCM' 0% mute 
           amixer set 'Front' 0% mute 
           ;;
        REALTEK_ALC655)
           ;;
        VIA_VT1612A|VIA_VT1616|VIA_VT1617A)
           amixer set 'IEC958' off
           amixer set 'IEC958 Playback AC97-SPSA' 0
           amixer set 'PCM' 0% mute 
           amixer set 'Master' 0% mute 
           amixer set 'VIA DXS',0 0%
           ;;
    esac

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
