#!/bin/sh
################################################################################
# audio
################################################################################
. /etc/rc.d/functions

start() {
    mm_message_output info 'configuring audio ...'

    case "${MM_AUDIO_TYPE}" in
        analog)
            sed -i 's%@SPEAKER_ARRANGEMENT@%Stereo 2.0%'   /root/.xine/config
            amixer set 'PCM'    90% unmute 
            amixer set 'Master' 90% unmute 
            amixer set 'VIA DXS',0 100%
            ;;
        digital)
            sed -i 's%@SPEAKER_ARRANGEMENT@%Pass Through%' /root/.xine/config
            amixer set 'IEC958' on
            case "${MM_HARDWARE_AUDIO}" in
                VT1612A|VT1616|VT1617A)
                    amixer set 'IEC958 Playback AC97-SPSA' 0
                    amixer set 'VIA DXS',0 100%
                    ;;
            esac
            ;;
        digital+analog)
            sed -i 's%@SPEAKER_ARRANGEMENT@%Pass Through%' /root/.xine/config
            amixer set 'IEC958' on
            amixer set 'PCM'    90% unmute 
            amixer set 'Master' 90% unmute 
            case "${MM_HARDWARE_AUDIO}" in
                VT1612A|VT1616|VT1617A)
                    amixer set 'IEC958 Playback AC97-SPSA' 0
                    amixer set 'VIA DXS',0 100%
                    ;;
            esac
            ;;
    esac

    return 0
}

stop () {
    mm_message_output info 'muting audio ...'

    amixer set 'IEC958' off
    amixer set 'PCM'    0% mute 
    amixer set 'Master' 0% mute 
    case "${MM_HARDWARE_AUDIO}" in
        VT1612A|VT1616|VT1617A)
           amixer set 'IEC958 Playback AC97-SPSA' 0
           amixer set 'VIA DXS',0 0%
           ;;
    esac

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
