#!/bin/sh
################################################################################
# lcdproc
################################################################################
. /etc/rc.d/functions

start() {
    mm_message_output info 'starting LCD/VFD ...'

    # LCDd is already running, so return.
    if /usr/bin/test -n "`/bin/pidof LCDd`" ; then
        return
    fi

    # Load the LCDproc configuration file.
    if /usr/bin/test -n "${MM_LCDPROC_DRIVER}" ; then
        if /usr/bin/test -e /etc/lcdproc.d/LCDd.conf.${MM_LCDPROC_DRIVER} ; then
            cp /etc/lcdproc.d/LCDd.conf.${MM_LCDPROC_DRIVER} /etc/LCDd.conf
        else
            cp /etc/lcdproc.d/LCDd.conf                      /etc/LCDd.conf
        fi
    fi

    # Get the LCDproc configuration file.
    mm_conf_get LCDd.conf /etc/LCDd.conf

    /bin/sed -i "s%@MM_LCDPROC_DRIVER@%${MM_LCDPROC_DRIVER}%" /etc/LCDd.conf

    # Start LCDproc LCDd daemon and Myth LCD server.
    if /usr/bin/test -n "${MM_LCDPROC_DRIVER}" ; then
        /usr/bin/test -e /usr/sbin/LCDd && /usr/sbin/LCDd -c /etc/LCDd.conf
    fi

    return 0
}


stop() {
    mm_message_output info 'stopping LCD/VFD display ...'

    /usr/bin/test -n "`/bin/pidof LCDd`" && /usr/bin/killall LCDd

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
