#!/bin/sh
################################################################################
# media
#
# This script mounts the remote media directories.
################################################################################
. /etc/rc.d/functions

start() {
    mm_message_output info "mounting media shares ..."

    if /usr/bin/test -n "${MM_MEDIA_GALLERY_URL}" ; then
        mm_url_mount "${MM_MEDIA_GALLERY_URL}" "${MM_MEDIA_GALLERY_MOUNTPOINT}"
    fi
    if /usr/bin/test -n "${MM_MEDIA_GAME_URL}"    ; then
        mm_url_mount "${MM_MEDIA_GAME_URL}"    "${MM_MEDIA_GAME_MOUNTPOINT}"
    fi
    if /usr/bin/test -n "${MM_MEDIA_MUSIC_URL}"   ; then
        mm_url_mount "${MM_MEDIA_MUSIC_URL}"   "${MM_MEDIA_MUSIC_MOUNTPOINT}"
    fi
    if /usr/bin/test -n "${MM_MEDIA_VIDEO_URL}"   ; then
        mm_url_mount "${MM_MEDIA_VIDEO_URL}"   "${MM_MEDIA_VIDEO_MOUNTPOINT}"
    fi
    if /usr/bin/test -n "${MM_MEDIA_DVD_RIP_URL}" ; then
        mm_url_mount "${MM_MEDIA_DVD_RIP_URL}" "${MM_MEDIA_DVD_RIP_MOUNTPOINT}"
    fi

    /bin/sed -i "s%@MEDIA_FILES_ORIGIN_PATH@%${MM_MEDIA_VIDEO_MOUNTPOINT}%" /home/minimyth/.xine/config

    return 0
}

stop() {
    mm_message_output info "unmounting media shares ..."

    if /usr/bin/test -n "${MM_MEDIA_DVD_RIP_URL}" && /usr/bin/test -d "${MM_MEDIA_DVD_RIP_MOUNTPOINT}" ; then
        /bin/umount "${MM_MEDIA_DVD_RIP_MOUNTPOINT}"
    fi
    if /usr/bin/test -n "${MM_MEDIA_VIDEO_URL}"   && /usr/bin/test -d "${MM_MEDIA_VIDEO_MOUNTPOINT}"   ; then
        /bin/umount "${MM_MEDIA_VIDEO_MOUNTPOINT}"
    fi
    if /usr/bin/test -n "${MM_MEDIA_MUSIC_URL}"   && /usr/bin/test -d "${MM_MEDIA_MUSIC_MOUNTPOINT}"   ; then
        /bin/umount "${MM_MEDIA_MUSIC_MOUNTPOINT}"
    fi
    if /usr/bin/test -n "${MM_MEDIA_GAME_URL}"    && /usr/bin/test -d "${MM_MEDIA_GAME_MOUNTPOINT}"    ; then
        /bin/umount "${MM_MEDIA_GAME_MOUNTPOINT}"
    fi
    if /usr/bin/test -n "${MM_MEDIA_GALLERY_URL}" && /usr/bin/test -d "${MM_MEDIA_GALLERY_MOUNTPOINT}" ; then
        /bin/umount "${MM_MEDIA_GALLERY_MOUNTPOINT}"
    fi

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
