#!/bin/sh
################################################################################
# modules
################################################################################
. /etc/rc.d/functions

start() {
    mm_message_output info 'loading kernel modules ...'

    # ACPI.
    modprobe button
    modprobe fan
    modprobe processor
    modprobe thermal
    modprobe video

    # Real time clock.
    modprobe rtc

    # Input.
    modprobe evdev
    modprobe psmouse

    # Sensors.
    case "${MM_HARDWARE_SENSOR}" in
        VT1211)
            modprobe i2c-core
            modprobe i2c-dev
            modprobe i2c-sensor
            modprobe i2c-isa
            modprobe vt1211
            ;;
        W83782D)
            modprobe i2c-core
            modprobe i2c-dev
            modprobe i2c-sensor
            modprobe i2c-isa
            modprobe i2c-viapro
            modprobe w83781d
            ;;
    esac

    # IO scheduler.
    modprobe as-iosched

    # IDE.
    modprobe via82cxxx
    modprobe ide-core
    modprobe ide-cd

    # IEEE1394 (firewire).
    modprobe ieee1394
    modprobe ohci1394
    modprobe sbp2

    # Parallel port.
    modprobe parport
    modprobe parport_pc
    modprobe ppdev

    # USB.
    modprobe usbcore
    modprobe ehci-hcd
    modprobe uhci-hcd
    modprobe usbhid
    modprobe usblcd
    modprobe usb-storage
    modprobe usbserial
    modprobe ftdi-sio

    # SCSI (used by USB devices).
    modprobe sd_mod
    modprobe sr_mod

    # CD-ROM.
    modprobe cdrom

    # File systems.
    modprobe nls_ascii
    modprobe nls_base
    modprobe nls_cp437
    modprobe nls_cp850
    modprobe nls_iso8859-1
    modprobe nls_iso8859-15
    modprobe nls_utf8
    modprobe cifs
    modprobe fat
    modprobe isofs
    modprobe msdos
    modprobe smbfs
    modprobe udf
    modprobe vfat

    # Net.
    modprobe netlink_dev
    modprobe af_packet
    modprobe unix

    # Sound.
    modprobe soundcore
    modprobe snd-via82xx

    # Video.
    modprobe agpgart
    modprobe via-agp
    modprobe via

    return 0
}

stop() {
    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit $?
