#!/bin/sh
################################################################################
# mythtv
#
# This script configures MythTV.
################################################################################
. /etc/rc.d/functions

start() {
    mm_message_output info 'configuring MythTV ...'

    # Determine broadcast address.
    MM_MYTH_WOL_BROADCAST=`ifconfig eth0 | grep ' Bcast:' | sed 's%.* Bcast:\([^ ]*\) .*%\1%'`

    # Configure mysql.txt file.
    sed -i "s%@MM_MYTH_SERVER@%${MM_MYTH_SERVER}%"                                   /root/.mythtv/mysql.txt
    sed -i "s%@MM_MYTH_DBUSERNAME@%${MM_MYTH_DBUSERNAME}%"                           /root/.mythtv/mysql.txt
    sed -i "s%@MM_MYTH_DBPASSWORD@%${MM_MYTH_DBPASSWORD}%"                           /root/.mythtv/mysql.txt
    sed -i "s%@MM_MYTH_DBNAME@%${MM_MYTH_DBNAME}%"                                   /root/.mythtv/mysql.txt
    if [ "${MM_MYTH_WOL_ENABLED}" = "yes" ] ; then
        sed -i "s%@MM_MYTH_WOL_FALSE@%\#%"                                           /root/.mythtv/mysql.txt
        sed -i "s%@MM_MYTH_WOL_TRUE@%%"                                              /root/.mythtv/mysql.txt
    else
        sed -i "s%@MM_MYTH_WOL_FALSE@%%"                                             /root/.mythtv/mysql.txt
        sed -i "s%@MM_MYTH_WOL_TRUE@%\#%"                                            /root/.mythtv/mysql.txt
    fi
    sed -i "s%@MM_MYTH_WOLSQLRECONNECTWAITTIME@%${MM_MYTH_WOLSQLRECONNECTWAITTIME}%" /root/.mythtv/mysql.txt
    sed -i "s%@MM_MYTH_WOLSQLCONNECTRETRY@%${MM_MYTH_WOLSQLCONNECTRETRY}%"           /root/.mythtv/mysql.txt
    sed -i "s%@MM_MYTH_WOLSQLCOMMAND@%${MM_MYTH_WOLSQLCOMMAND}%"                     /root/.mythtv/mysql.txt
    sed -i "s%@MM_MYTH_WOL_BROADCAST@%${MM_MYTH_WOL_BROADCAST}%"                     /root/.mythtv/mysql.txt
    sed -i "s%@MM_MYTH_WOL_MAC@%${MM_MYTH_WOL_MAC}%"                                 /root/.mythtv/mysql.txt

    # Test Myth database connection.
    if [ "${MM_MYTH_WOL_ENABLED}" != "yes" ] ; then
        [ "${MM_MYTH_WOL_ENABLED}" != "yes" ] && mm_mythdb_command_run
        if [ $? -ne 0 ] ; then
            mm_message_output err 'error: cannot connect to the Myth backend database.'
            exit 1
        fi 
    fi

    # Set themes.
    if [ -n "${MM_THEME_NAME}" ] ; then
        [ "${MM_MYTH_WOL_ENABLED}" != "yes" ] && mm_mythdb_setting_update "Theme"    "${MM_THEME_NAME}"
    fi
    if [ -n "${MM_THEMEOSD_NAME}" ] ; then
        [ "${MM_MYTH_WOL_ENABLED}" != "yes" ] && mm_mythdb_setting_update "OSDTheme" "${MM_THEMEOSD_NAME}"
    fi

    # Mount theme directory.
    if [ -n "${MM_THEME_URL}" ] ; then
        if [ ! -n "${MM_THEME_NAME}" ] ; then
            mm_message_output err 'error: "MM_THEME_NAME" not present.'
            exit 1
        fi
        if [ -e "/usr/share/themes/${MM_THEME_NAME}" ] ; then
            mm_message_output err "error: theme directory \"${MM_THEME_NAME}\" already exists."
            exit 1
        fi
        mm_url_mount "${MM_THEME_URL}" "/usr/share/mythtv/themes/${MM_THEME_NAME}"
    fi

    # Mount OSD theme directory.
    if [ -n "${MM_THEMEOSD_URL}" ] ; then
        if [ ! -n "${MM_THEMEOSD_NAME}" ] ; then
            mm_message_output err 'error: "MM_THEMEOSD_NAME" not present.'
            exit 1
        fi
        if [ -e "/usr/share/themes/${MM_THEMEOSD_NAME}" ] ; then
            mm_message_output err "error: theme directory \"${MM_THEMEOSD_NAME}\" already exists."
            exit 1
        fi
        mm_url_mount "${MM_THEMEOSD_URL}" "/usr/share/mythtv/themes/${MM_THEMEOSD_NAME}"
    fi

    # Mount themecache directory.
    if [ -n "${MM_THEMECACHE_URL}" ] ; then
        mm_url_mount "${MM_THEMECACHE_URL}" "/root/.mythtv/themecache"
    fi

    # Configure MythDVD ripping.
    if [ "${MM_MYTHDVD_ENABLED}" = "yes" ] ; then
        if [ -d /mnt/dvd ] && [ -w /mnt/dvd ] ; then
            mkdir -p /mnt/dvd/mythdvd/temp
        fi
        if [ -d /mnt/dvd/mythdvd/temp ] && [ -w /mnt/dvd/mythdvd/temp ]  ; then
            [ "${MM_MYTH_WOL_ENABLED}" != "yes" ] && mm_mythdb_setting_update "DVDRipLocation" "/mnt/dvd/mythdvd/temp"
            TRANSCODE=`which transcode`
            [ "${MM_MYTH_WOL_ENABLED}" != "yes" ] && mm_mythdb_setting_update "TranscodeCommand" "${TRANSCODE}"
            mtd --daemon
        fi
    fi

    # Configure Myth database jumppoints to match MiniMyth frontend.
    cat /etc/minimyth.d/minimyth.conf | grep '^MM_MYTHDB_JUMPPOINT=' | sed -e 's%^MM_MYTHDB_JUMPPOINT=%%' | \
        sed -e 's%^[ ]*%%' -e 's%[ ]*$%%' | \
        sed -e 's%^"%%'    -e 's%"$%%'    | \
        sed -e "s%^'%%"    -e "s%'$%%"    |
    while read jumppoint ; do
        jumppoint_destination=`echo ${jumppoint} | cut -d~ -f1`
        jumppoint_keylist=`echo ${jumppoint} | cut -d~ -f2`
        [ "${MM_MYTH_WOL_ENABLED}" != "yes" ] && mm_mythdb_jumppoint_update "${jumppoint_destination}" "${jumppoint_keylist}"
    done

    # Configure Myth database keybindings to match MiniMyth frontend.
    cat /etc/minimyth.d/minimyth.conf | grep '^MM_MYTHDB_KEYBINDING=' | sed -e 's%^MM_MYTHDB_KEYBINDING=%%' | \
        sed -e 's%^[ ]*%%' -e 's%[ ]*$%%' | \
        sed -e 's%^"%%'    -e 's%"$%%'    | \
        sed -e "s%^'%%"    -e "s%'$%%"    |
    while read keybinding ; do
        keybinding_context=`echo ${keybinding} | cut -d~ -f1`
        keybinding_action=`echo ${keybinding} | cut -d~ -f2`
        keybinding_keylist=`echo ${keybinding} | cut -d~ -f3`
        [ "${MM_MYTH_WOL_ENABLED}" != "yes" ] && mm_mythdb_keybinding_update "${keybinding_context}" "${keybinding_action}" "${keybinding_keylist}"
    done

    # Configure Myth database settings to match MiniMyth frontend.
    cat /etc/minimyth.d/minimyth.conf | grep '^MM_MYTHDB_SETTING=' | sed -e 's%^MM_MYTHDB_SETTING=%%' | \
        sed -e 's%^[ ]*%%' -e 's%[ ]*$%%' | \
        sed -e 's%^"%%'    -e 's%"$%%'    | \
        sed -e "s%^'%%"    -e "s%'$%%"    |
    while read setting ; do
        setting_value=`echo ${setting} | cut -d~ -f1`
        setting_data=`echo ${setting} | cut -d~ -f2`
        [ "${MM_MYTH_WOL_ENABLED}" != "yes" ] && mm_mythdb_setting_update "${setting_value}" "${setting_data}"
    done

    # Delete disabled plugins.
    if [ "${MM_MYTHTV_OPTICAL_DISK_ENABLED}" = "no" ] ; then
        sed -i 's%<depends>mythmusic mythdvd</depends>%<depends>disabled</depends>%' /usr/share/mythtv/mainmenu.xml
    fi
    if [ "${MM_MYTHDVD_ENABLED}"     = "no" ] ; then
        rm -rf /usr/lib/mythtv/plugins/libmythdvd.so
        rm -rf /usr/share/mythtv/dvd*
        rm -rf /usr/share/mythtv/mythdvd*
    fi
    if [ "${MM_MYTHGALLERY_ENABLED}" = "no" ] ; then
        rm -rf /usr/lib/mythtv/plugins/libmythgallery.so
        rm -rf /usr/share/mythtv/gallery*
        rm -rf /usr/share/mythtv/mythgallery*
    fi
    if [ "${MM_MYTHMUSIC_ENABLED}"   = "no" ] ; then
        rm -rf /usr/lib/mythtv/plugins/libmythmusic.so
        rm -rf /usr/share/mythtv/music*
        rm -rf /usr/share/mythtv/mythmusic*
    fi
    if [ "${MM_MYTHNEWS_ENABLED}"    = "no" ] ; then
        rm -rf /usr/lib/mythtv/plugins/libmythnews.so
        rm -rf /usr/share/mythtv/news*
        rm -rf /usr/share/mythtv/mythnews*
    fi
    if [ "${MM_MYTHSTREAM_ENABLED}"  = "no" ] ; then
        rm -rf /usr/lib/mythtv/plugins/libmythstream.so
        rm -rf /usr/share/mythtv/stream*
        rm -rf /usr/share/mythtv/mythstream*
    fi
    if [ "${MM_MYTHVIDEO_ENABLED}"   = "no" ] ; then
        rm -rf /usr/lib/mythtv/plugins/libmythvideo.so
        rm -rf /usr/share/mythtv/video*
        rm -rf /usr/share/mythtv/mythvideo*
    fi
    if [ "${MM_MYTHWEATHER_ENABLED}" = "no" ] ; then
        rm -rf /usr/lib/mythtv/plugins/libmythweather.so
        rm -rf /usr/share/mythtv/weather*
        rm -rf /usr/share/mythtv/mythweather*
    fi

    return 0
}

stop() {
    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
