#!/bin/sh
################################################################################
# network
################################################################################
. /etc/rc.d/functions

start() {
    mm_message_output info 'starting network ...'

    # Bring up the local (loopback) interface.
    ifconfig lo 127.0.0.1

    # Get the IP address and other IP parameters.
    # If an IP address was already obtained then request the same address.
    ip=`ifconfig eth0 | grep '^ *inet addr:' | sed 's%^ *inet addr:\([^ ]*\) .*%\1%'`
    if [ -z "$ip" ] ; then
        udhcpc -s /etc/udhcpc.script -i eth0         >> /dev/null 2>&1
    else
        udhcpc -s /etc/udhcpc.script -i eth0 -r $ip  >> /dev/null 2>&1
    fi

    # Start portmap on local interface.
    portmap -l

    return 0
}

stop() {
    mm_message_output info 'stopping network ...'

    [ -n "`pidof portmap`" ] && killall portmap
    [ -n "`pidof udhcpc`"  ] && killall udhcpc

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
