#!/bin/sh
################################################################################
# ssh
################################################################################
. /etc/rc.d/functions

start() {
    mm_message_output info "configuring ssh ..."

    if /usr/bin/test -e /etc/ssh/id_rsa ; then
        /bin/mkdir -p /etc/dropbear
        /usr/bin/dropbearconvert openssh dropbear /etc/ssh/id_rsa /etc/dropbear/id_rsa
        /bin/chmod 640 /etc/dropbear/id_rsa
        /bin/chown root:ssh /etc/dropbear/id_rsa
    fi

    if /usr/bin/test "${MM_SSH_SERVER_ENABLED}" = "yes" ; then
        if /usr/bin/test ! -n "`/bin/pidof dropbear`" ; then
            mm_message_output info "starting ssh server ..."
            if /usr/bin/test ! -e /etc/dropbear/id_rsa ; then
                mm_message_output err "error: cannot not start ssh server: no host key."
                exit 1
            fi
            /usr/sbin/dropbear -r /etc/dropbear/id_rsa
        fi
    fi

    return 0
}


stop() {
 
    if /usr/bin/test -n "`/bin/pidof dropbear`" ; then
        mm_message_output info "stopping ssh server ..."
        /usr/bin/killall dropbear
    fi

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
