#!/bin/sh
################################################################################
# ssh_remote
#
# This script configures ssh remote command execution.
################################################################################
. /etc/rc.d/functions

start() {
    mm_message_output info "configuring ssh remote command execution ..."

    if /usr/bin/test -e /etc/ssh/id_rsa ; then
        /bin/chmod 0600 /etc/ssh/id_rsa
        /bin/chown root:root /etc/ssh/id_rsa

        /bin/mkdir -p /root/.ssh
        /bin/cp /etc/ssh/id_rsa /root/.ssh/id_rsa
        /bin/chmod 0600 /root/.ssh/id_rsa
        /bin/chown root:root /root/.ssh/id_rsa

        /bin/mkdir -p /home/minimyth/.ssh
        /bin/cp /etc/ssh/id_rsa /home/minimyth/.ssh/id_rsa
        /bin/chmod 0600 /home/minimyth/.ssh/id_rsa
        /bin/chown root:root /home/minimyth/.ssh/id_rsa
    fi

    if /usr/bin/test "${MM_SSH_REMOTE_ENABLED}" = "yes" ; then
        if /usr/bin/test "${MM_MYTHSTREAM_ENABLED}" = "yes" ; then
            mkdir -p /var/log
            mm_ssh_remote_put /var/log/init_ssh_remote.log /usr/share/mythtv/mythstream/parsers
            if /usr/bin/test $? -ne 0 ; then
                mm_message_output err "error: failed to copy MythStream parsers to remote host. see /var/log/init_ssh_remote.log for more details."
                exit 1
            fi
        fi
        if /usr/bin/test "${MM_MYTHVIDEO_ENABLED}" = "yes" ; then
            mkdir -p /var/log
            mm_ssh_remote_put /var/log/init_ssh_remote.log /usr/share/mythtv/mythvideo/scripts
            if /usr/bin/test $? -ne 0 ; then
                mm_message_output err "error: failed to copy MythVideo scripts to remote host. see /var/log/init_ssh_remote.log for more details."
                exit 1
            fi
        fi
    fi

    return 0
}

stop() {
    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
