#!/bin/sh
################################################################################
# telnet
################################################################################
. /etc/rc.d/functions

start() {

    # Run telnet server on machines that are not secure or when debugging.
    if /usr/bin/test -z "${MM_SECURITY_LEVEL}"      || \
       /usr/bin/test     ${MM_SECURITY_LEVEL} -le 0 || \
       /usr/bin/test    "${MM_DEBUG}" = "yes"       ; then
        if /usr/bin/test ! -n "`/bin/pidof telnetd`" ; then
            mm_message_output info "starting telnet server ..."
            /usr/sbin/telnetd -l /bin/login
        fi
    # Otherwise, stop the telnet server.
    else
        if /usr/bin/test   -n "`/bin/pidof telnetd`" ; then
            mm_message_output info "stopping telnet server ..."
            /usr/bin/killall telnetd
        fi
    fi

    return 0
}

stop() {

    if /usr/bin/test   -n "`/bin/pidof telnetd`" ; then
        mm_message_output info "stopping telnet server ..."
        /usr/bin/killall telnetd
    fi

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
