#!/bin/sh
################################################################################
# time
################################################################################
. /etc/rc.d/functions

start() {

    local NTP_CONF
    local NTP_SERVER
    local NTP_SUCCESS

    mm_message_output info "configuring time ..."

    NTP_CONF='/etc/ntp.conf'

    /bin/rm -f ${NTP_CONF}~
    for NTP_SERVER in ${MM_NTP_SERVERS}; do
        if /usr/bin/test -n "${NTP_SERVER}" ; then
            /bin/echo server ${NTP_SERVER} >> ${NTP_CONF}~
        fi
    done
    /bin/mv -f ${NTP_CONF}~ ${NTP_CONF}

    # Set localtime file.
    /bin/cp /usr/share/zoneinfo/${MM_TZ} /etc/localtime

    # Set time.
    NTP_SUCCESS=0
    for NTP_SERVER in ${MM_NTP_SERVERS} ; do
        /usr/bin/ntpdate ${NTP_SERVER}
        if /usr/bin/test $? -eq 0 ; then
            NTP_SUCCESS=1
            break
        fi
    done
    if /usr/bin/test ${NTP_SUCCESS} -eq 0 ; then
        mm_message_output err "error: 'ntpdate' failed to synchronize with any NTP server." 
        case ${MM_NTP_FAILURE_ACTION} in
            stop)
                exit 1
                ;;
            continue)
                ;;
        esac
    fi

    # Start NTP daemon.
    /usr/bin/ntpd

    return 0
}

stop() {
    mm_message_output info "saving time ..."

    if /usr/bin/test -n "`/bin/pidof ntpd`" ; then
        /usr/bin/killall ntpd
        /sbin/hwclock --systohc --utc
    fi

    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
