#!/bin/sh
################################################################################
# video
#
# The script configures the video.
################################################################################
. /etc/rc.d/functions

start() {
    mm_message_output info 'configuring video ...'

    if   [ "${MM_VIDEO_ASPECT_RATIO}" = "4:3"  ] ; then
        sed -i "s%@MONITORASPECT@%4:3%"  /root/.mplayer/config
    elif [ "${MM_VIDEO_ASPECT_RATIO}" = "16:9" ] ; then
        sed -i "s%@MONITORASPECT@%16:9%" /root/.mplayer/config
    else
        mm_message_output err 'error: invalid value for MM_VIDEO_ASPECT_RATIO.'
        exit 1
    fi

    if   [ "${MM_VIDEO_DEINTERLACE_ENABLED}" = "no"  ] ; then
        mm_mythdb_setting_update Deinterlace 0
        sed -i "s%@DEINTERLACE_BY_DEFAULT@%0%" /root/.xine/config
        sed -i "s%@XVMC_BOB_DEINTERLACING@%0%" /root/.xine/config
        sed -i "s%@DEINT_BOB@%%"               /root/.mplayer/config
    elif [ "${MM_VIDEO_DEINTERLACE_ENABLED}" = "yes" ] ; then
        mm_mythdb_setting_update Deinterlace 1
        mm_mythdb_setting_update DeinterlaceFilter bobdeint
        sed -i "s%@DEINTERLACE_BY_DEFAULT@%1%" /root/.xine/config
        sed -i "s%@XVMC_BOB_DEINTERLACING@%1%" /root/.xine/config
        sed -i "s%@DEINT_BOB@%:deint-bob%"     /root/.mplayer/config
    else
        mm_message_output err 'error: invalid value for MM_VIDEO_DEINTERLACE_ENABLED.'
        exit 1
    fi

    case "${MM_X_DRIVER}" in
        intel_i810)
            PREFE
            PREFERRED_MPEG2_DECODER=xvmc
            sed -i "s%@XVMC_TRUE@%%"    /root/.mplayer/config
            sed -i "s%@XVMC_FALSE@%\#%" /root/.mplayer/config
            ;;
        intel_i830|intel_i915)
            PREFERRED_MPEG2_DECODER=ffmpeg
            sed -i "s%@XVMC_TRUE@%\#%"  /root/.mplayer/config
            sed -i "s%@XVMC_FALSE@%%"   /root/.mplayer/config
            ;;
        nvidia)
            # this should really be the more efficient 'libmpeg2',
            # but it causes stalls during when fast forwarding and rewinding.
            PREFERRED_MPEG2_DECODER=ffmpeg
            sed -i "s%@XVMC_TRUE@%\#%"  /root/.mplayer/config
            sed -i "s%@XVMC_FALSE@%%"   /root/.mplayer/config
            ;;
        via|via_pro)
            PREFERRED_MPEG2_DECODER=xvmc-vld
            sed -i "s%@XVMC_TRUE@%%"    /root/.mplayer/config
            sed -i "s%@XVMC_FALSE@%\#%" /root/.mplayer/config
            ;;
    esac

    case "${PREFERRED_MPEG2_DECODER}" in
        ffmpeg)
            if [ "$(MM_VERSION_MYTH) = "0.18.2" ] ; then
                mm_mythdb_setting_update UseMPEG2Dec 0
                mm_mythdb_setting_update UseXVMC 0
                mm_mythdb_setting_update UseXvMcVld 0
            else
                mm_mythdb_setting_update PreferredMPEG2Decoder ${PREFERRED_MPEG2_DECODER}
            fi
        libmpeg2)
            if [ "$(MM_VERSION_MYTH) = "0.18.2" ] ; then
                mm_mythdb_setting_update UseMPEG2Dec 1
                mm_mythdb_setting_update UseXVMC 0
                mm_mythdb_setting_update UseXvMcVld 0
            else
                mm_mythdb_setting_update PreferredMPEG2Decoder ${PREFERRED_MPEG2_DECODER}
            fi
            ;;
        xvmc)
            if [ "$(MM_VERSION_MYTH) = "0.18.2" ] ; then
                mm_mythdb_setting_update UseMPEG2Dec 0
                mm_mythdb_setting_update UseXVMC 1
                mm_mythdb_setting_update UseXvMcVld 0
            else
                mm_mythdb_setting_update PreferredMPEG2Decoder ${PREFERRED_MPEG2_DECODER}
            fi
            ;;
        xvmc-vld)
            if [ "$(MM_VERSION_MYTH) = "0.18.2" ] ; then
                mm_mythdb_setting_update UseMPEG2Dec 0
                mm_mythdb_setting_update UseXVMC 0
                mm_mythdb_setting_update UseXvMcVld 1
            else
                mm_mythdb_setting_update PreferredMPEG2Decoder ${PREFERRED_MPEG2_DECODER}
            fi
            ;;
    esac

    return 0
}

stop() {
    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
