#!/bin/sh
################################################################################
# video
#
# The script configures the video.
################################################################################
. /etc/rc.d/functions

start() {

    local kernel_module
    local PREFERRED_MPEG2_DECODER
    local DEINTERLACE_FILTER
    local X_RESOLUTION
    local X_RESOLUTION_X
    local X_RESOLUTION_Y
    local GUI_X
    local GUI_Y
    local GUI_OFFSET_X
    local GUI_OFFSET_Y

    mm_message_output info 'configuring video ...'

    PREFERRED_MPEG2_DECODER=''
    case "${MM_X_DRIVER}" in
        intel_810)
            /bin/sed -i "s%@MM_XVMC_LIB@%I810XvMC%"           /etc/X11/XvMCConfig
            PREFERRED_MPEG2_DECODER='xvmc'
            /bin/sed -i "s%@VIDEO_DRIVER@%xvmc%"              /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_TRUE@%%"                     /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_FALSE@%\#%"                  /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_TRUE@%%"                     /home/minimyth/.mplayer/config
            /bin/sed -i "s%@XVMC_FALSE@%\#%"                  /home/minimyth/.mplayer/config
            ;;
        intel_915)
            PREFERRED_MPEG2_DECODER='ffmpeg'
            /bin/sed -i "s%@VIDEO_DRIVER@%xv%"                /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_TRUE@%\#%"                   /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_FALSE@%%"                    /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_TRUE@%\#%"                   /home/minimyth/.mplayer/config
            /bin/sed -i "s%@XVMC_FALSE@%%"                    /home/minimyth/.mplayer/config
            ;;
        nvidia)
            /bin/sed -i "s%@MM_XVMC_LIB@%XvMCNVIDIA_dynamic%" /etc/X11/XvMCConfig
            # this should really be the more efficient 'libmpeg2',
            # but it causes stalls during when fast forwarding and rewinding.
            PREFERRED_MPEG2_DECODER='ffmpeg'
            /bin/sed -i "s%@VIDEO_DRIVER@%xv%"                /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_TRUE@%\#%"                   /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_FALSE@%%"                    /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_TRUE@%\#%"                   /home/minimyth/.mplayer/config
            /bin/sed -i "s%@XVMC_FALSE@%%"                    /home/minimyth/.mplayer/config
            ;;
        via)
            /bin/sed -i "s%@MM_XVMC_LIB@%viaXvMC%"            /etc/X11/XvMCConfig
            PREFERRED_MPEG2_DECODER='xvmc-vld'
            /bin/sed -i "s%@VIDEO_DRIVER@%xxmc%"              /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_TRUE@%%"                     /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_FALSE@%\#%"                  /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_TRUE@%%"                     /home/minimyth/.mplayer/config
            /bin/sed -i "s%@XVMC_FALSE@%\#%"                  /home/minimyth/.mplayer/config
            mm_mythdb_settings_set "UseChromaKeyOSD" "1"
            ;;
        via_pro)
            /bin/sed -i "s%@MM_XVMC_LIB@%viaXvMCPro%"         /etc/X11/XvMCConfig
            PREFERRED_MPEG2_DECODER='xvmc-vld'
            /bin/sed -i "s%@VIDEO_DRIVER@%xxmc%"              /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_TRUE@%%"                     /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_FALSE@%\#%"                  /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_TRUE@%%"                     /home/minimyth/.mplayer/config
            /bin/sed -i "s%@XVMC_FALSE@%\#%"                  /home/minimyth/.mplayer/config
            mm_mythdb_settings_set "UseChromaKeyOSD" "1"
            ;;
        vmware)
            PREFERRED_MPEG2_DECODER='ffmpeg'
            /bin/sed -i "s%@VIDEO_DRIVER@%xv%"                /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_TRUE@%\#%"                   /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_FALSE@%%"                    /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_TRUE@%\#%"                   /home/minimyth/.mplayer/config
            /bin/sed -i "s%@XVMC_FALSE@%%"                    /home/minimyth/.mplayer/config
            ;;
    esac

    case "${PREFERRED_MPEG2_DECODER}" in
        ffmpeg)
            mm_mythdb_settings_update PreferredMPEG2Decoder ${PREFERRED_MPEG2_DECODER}
            ;;
        libmpeg2)
            mm_mythdb_settings_update PreferredMPEG2Decoder ${PREFERRED_MPEG2_DECODER}
            ;;
        xvmc)
            mm_mythdb_settings_update PreferredMPEG2Decoder ${PREFERRED_MPEG2_DECODER}
            ;;
        xvmc-vld)
            mm_mythdb_settings_update PreferredMPEG2Decoder ${PREFERRED_MPEG2_DECODER}
            ;;
    esac

    if   /usr/bin/test "${MM_VIDEO_DEINTERLACE_ENABLED}" = "no"  ; then
        mm_mythdb_settings_update Deinterlace 0
        /bin/sed -i "s%@DEINTERLACE_BY_DEFAULT@%0%" /home/minimyth/.xine/config
        /bin/sed -i "s%@XVMC_BOB_DEINTERLACING@%0%" /home/minimyth/.xine/config
        /bin/sed -i "s%@BOBDEINT@%%"                /home/minimyth/.mplayer/config
    elif /usr/bin/test "${MM_VIDEO_DEINTERLACE_ENABLED}" = "yes" ; then
        case ${PREFERRED_MPEG2_DECODER} in
            ffmpeg)
                if /bin/cat /proc/cpuinfo | /bin/grep -e '^flags' | /bin/grep -q -e ' sse ' > /dev/null 2>&1 ; then
                    DEINTERLACE_FILTER='kerneldeint'
                else
                    DEINTERLACE_FILTER='linearblend'
                fi
                ;;
            libmpeg2)
                if /bin/cat /proc/cpuinfo | /bin/grep -e '^flags' | /bin/grep -q -e ' sse ' > /dev/null 2>&1 ; then
                    DEINTERLACE_FILTER='kerneldeint'
                else
                    DEINTERLACE_FILTER='linearblend'
                fi
                ;;
            xvmc)
                DEINTERLACE_FILTER='bobdeint'
                ;;
            xvmc-vld)
                DEINTERLACE_FILTER='bobdeint'
                ;;
            *)
                if /bin/cat /proc/cpuinfo | /bin/grep -e '^flags' | /bin/grep -q -e ' sse ' > /dev/null 2>&1 ; then
                    DEINTERLACE_FILTER='kerneldeint'
                else
                    DEINTERLACE_FILTER='linearblend'
                fi
                ;;
        esac
        mm_mythdb_settings_update Deinterlace 1
        mm_mythdb_settings_update DeinterlaceFilter ${DEINTERLACE_FILTER}
        /bin/sed -i "s%@DEINTERLACE_BY_DEFAULT@%1%" /home/minimyth/.xine/config
        /bin/sed -i "s%@XVMC_BOB_DEINTERLACING@%1%" /home/minimyth/.xine/config
        /bin/sed -i "s%@BOBDEINT@%:bobdeint%"       /home/minimyth/.mplayer/config
    else
        mm_message_output err "error: something is very wrong in the 'video' init script."
        exit 1
    fi

    if   /usr/bin/test "${MM_VIDEO_ASPECT_RATIO}" = "4:3"  ; then
        /bin/sed -i "s%@MONITORASPECT@%4:3%"  /home/minimyth/.mplayer/config
    elif /usr/bin/test "${MM_VIDEO_ASPECT_RATIO}" = "16:9" ; then
        /bin/sed -i "s%@MONITORASPECT@%16:9%" /home/minimyth/.mplayer/config
    else
        mm_message_output err "error: something is very wrong in the 'video' init script."
        exit 1
    fi

    if   /usr/bin/test "${MM_VIDEO_RESIZE_ENABLED}" = "no"  ; then
        mm_mythdb_settings_set    'UseVideoModes' '0'

        mm_mythdb_settings_delete 'GuiVidModeResolution'
        mm_mythdb_settings_delete 'TvVidModeResolution'
        mm_mythdb_settings_delete 'TVVidModeRefreshRate'
        mm_mythdb_settings_delete 'TvVidModeForceAspect'

        mm_mythdb_settings_delete 'VidModeWidth0'
        mm_mythdb_settings_delete 'VidModeHeight0'
        mm_mythdb_settings_delete 'TVVidModeResolution0'
        mm_mythdb_settings_delete 'TVVidModeRefreshRate0'
        mm_mythdb_settings_delete 'TVVidModeForceAspect0'

        mm_mythdb_settings_delete 'VidModeWidth1'
        mm_mythdb_settings_delete 'VidModeHeight1'
        mm_mythdb_settings_delete 'TVVidModeResolution1'
        mm_mythdb_settings_delete 'TVVidModeRefreshRate1'
        mm_mythdb_settings_delete 'TVVidModeForceAspect1'

        mm_mythdb_settings_delete 'VidModeWidth2'
        mm_mythdb_settings_delete 'VidModeHeight2'
        mm_mythdb_settings_delete 'TVVidModeResolution2'
        mm_mythdb_settings_delete 'TVVidModeRefreshRate2'
        mm_mythdb_settings_delete 'TVVidModeForceAspect2'
    elif /usr/bin/test "${MM_VIDEO_RESIZE_ENABLED}" = "yes" ; then
        mm_mythdb_settings_set 'GuiSizeForTV' '1'
        mm_mythdb_settings_set 'UseVideoModes' '1'

        X_RESOLUTION=`/bin/echo ${MM_X_MODE}      | /bin/sed -e 's%^\([0-9][0-9]*\)[Xx]\([0-9][0-9]*\).*%\1x\2%'`
        X_RESOLUTION_X=`/bin/echo ${X_RESOLUTION} | /bin/sed -e 's%^\([0-9][0-9]*\)x\([0-9][0-9]*\)$%\1%'`
        X_RESOLUTION_Y=`/bin/echo ${X_RESOLUTION} | /bin/sed -e 's%^\([0-9][0-9]*\)x\([0-9][0-9]*\)$%\2%'`
        mm_mythdb_settings_set 'GuiVidModeResolution' "${X_RESOLUTION}"
        mm_mythdb_settings_set 'TvVidModeResolution'  "${X_RESOLUTION}"
        mm_mythdb_settings_set 'TVVidModeRefreshRate' '0'
        mm_mythdb_settings_set 'TvVidModeForceAspect' '0.0'
        if /usr/bin/test ! "${MM_X_MODE_0}" = "none" ; then
            X_RESOLUTION=`/bin/echo ${MM_X_MODE_0}    | /bin/sed -e 's%^\([0-9][0-9]*\)[Xx]\([0-9][0-9]*\).*%\1x\2%'`
            X_RESOLUTION_X=`/bin/echo ${X_RESOLUTION} | /bin/sed -e 's%^\([0-9][0-9]*\)x\([0-9][0-9]*\)$%\1%'`
            X_RESOLUTION_Y=`/bin/echo ${X_RESOLUTION} | /bin/sed -e 's%^\([0-9][0-9]*\)x\([0-9][0-9]*\)$%\2%'`
            mm_mythdb_settings_set 'VidModeWidth0'         "${X_RESOLUTION_X}"
            mm_mythdb_settings_set 'VidModeHeight0'        "${X_RESOLUTION_Y}"
            mm_mythdb_settings_set 'TVVidModeResolution0'  "${X_RESOLUTION}"
            mm_mythdb_settings_set 'TVVidModeRefreshRate0' '0'
            mm_mythdb_settings_set 'TVVidModeForceAspect0' '0.0'
        else
            mm_mythdb_settings_delete 'VidModeWidth0'
            mm_mythdb_settings_delete 'VidModeHeight0'
            mm_mythdb_settings_delete 'TVVidModeResolution0'
            mm_mythdb_settings_delete 'TVVidModeRefreshRate0'
            mm_mythdb_settings_delete 'TVVidModeForceAspect0'
        fi
        if /usr/bin/test ! "${MM_X_MODE_1}" = "none" ; then
            X_RESOLUTION=`/bin/echo ${MM_X_MODE_1}    | /bin/sed -e 's%^\([0-9][0-9]*\)[Xx]\([0-9][0-9]*\).*%\1x\2%'`
            X_RESOLUTION_X=`/bin/echo ${X_RESOLUTION} | /bin/sed -e 's%^\([0-9][0-9]*\)x\([0-9][0-9]*\)$%\1%'`
            X_RESOLUTION_Y=`/bin/echo ${X_RESOLUTION} | /bin/sed -e 's%^\([0-9][0-9]*\)x\([0-9][0-9]*\)$%\2%'`
            mm_mythdb_settings_set 'VidModeWidth1'         "${X_RESOLUTION_X}"
            mm_mythdb_settings_set 'VidModeHeight1'        "${X_RESOLUTION_Y}"
            mm_mythdb_settings_set 'TVVidModeResolution1'  "${X_RESOLUTION}"
            mm_mythdb_settings_set 'TVVidModeRefreshRate2' '0'
            mm_mythdb_settings_set 'TVVidModeForceAspect1' '0.0'
        else
            mm_mythdb_settings_delete 'VidModeWidth1'
            mm_mythdb_settings_delete 'VidModeHeight1'
            mm_mythdb_settings_delete 'TVVidModeResolution1'
            mm_mythdb_settings_delete 'TVVidModeRefreshRate1'
            mm_mythdb_settings_delete 'TVVidModeForceAspect1'
        fi
        if /usr/bin/test ! "${MM_X_MODE_2}" = "none" ; then
            X_RESOLUTION=`/bin/echo ${MM_X_MODE_2}    | /bin/sed -e 's%^\([0-9][0-9]*\)[Xx]\([0-9][0-9]*\).*%\1x\2%'`
            X_RESOLUTION_X=`/bin/echo ${X_RESOLUTION} | /bin/sed -e 's%^\([0-9][0-9]*\)x\([0-9][0-9]*\)$%\1%'`
            X_RESOLUTION_Y=`/bin/echo ${X_RESOLUTION} | /bin/sed -e 's%^\([0-9][0-9]*\)x\([0-9][0-9]*\)$%\2%'`
            mm_mythdb_settings_set 'VidModeWidth2'         "${X_RESOLUTION_X}"
            mm_mythdb_settings_set 'VidModeHeight2'        "${X_RESOLUTION_Y}"
            mm_mythdb_settings_set 'TVVidModeResolution2'  "${X_RESOLUTION}"
            mm_mythdb_settings_set 'TVVidModeRefreshRate2' '0'
            mm_mythdb_settings_set 'TVVidModeForceAspect2' '0.0'
        else
            mm_mythdb_settings_delete 'VidModeWidth2'
            mm_mythdb_settings_delete 'VidModeHeight2'
            mm_mythdb_settings_delete 'TVVidModeResolution2'
            mm_mythdb_settings_delete 'TVVidModeRefreshRate2'
            mm_mythdb_settings_delete 'TVVidModeForceAspect2'
        fi
    fi

    return 0
}

stop() {
    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
