#!/bin/sh
################################################################################
# video
#
# The script configures the video.
################################################################################
. /etc/rc.d/functions

start() {

    local hostname
    local pref_cmp0
    local pref_decoder
    local pref_max_cpus
    local pref_osdfade
    local pref_osdrenderer
    local pref_videorenderer
    local pref_deint0
    local pref_deint1
    local pref_filters
    local profilegroupid
    local profileid
    local X_RESOLUTION
    local X_RESOLUTION_X
    local X_RESOLUTION_Y
    local XVMC_LIB

    mm_message_output info "configuring video ..."

    case "${MM_X_DRIVER}" in
        intel_810)
            /usr/bin/test "${MM_VIDEO_DEINTERLACER}"  = "auto" && MM_VIDEO_DEINTERLACER='bob'
            /usr/bin/test "${MM_VIDEO_MPEG2_DECODER}" = "auto" && MM_VIDEO_MPEG2_DECODER='xvmc'
            XVMC_LIB='/usr/lib/libI810XvMC.so.1'  && \
                /usr/bin/test -e ${XVMC_LIB}      && \
                /bin/sed -i "s%@MM_XVMC_LIB@%${XVMC_LIB}%" /etc/X11/XvMCConfig
            XVMC_LIB='/usr/lib/libIntelXvMC.so.1' && \
                /usr/bin/test -e ${XVMC_LIB}      && \
                /bin/sed -i "s%@MM_XVMC_LIB@%${XVMC_LIB}%" /etc/X11/XvMCConfig
            ;;
        intel_915)
            /usr/bin/test "${MM_VIDEO_DEINTERLACER}"  = "auto" && MM_VIDEO_DEINTERLACER='bob'
            /usr/bin/test "${MM_VIDEO_MPEG2_DECODER}" = "auto" && MM_VIDEO_MPEG2_DECODER='ffmpeg'
            XVMC_LIB='/usr/lib/libI810XvMC.so.1'  && \
                /usr/bin/test -e ${XVMC_LIB}      && \
                /bin/sed -i "s%@MM_XVMC_LIB@%${XVMC_LIB}%" /etc/X11/XvMCConfig
            XVMC_LIB='/usr/lib/libIntelXvMC.so.1' && \
                /usr/bin/test -e ${XVMC_LIB}      && \
                /bin/sed -i "s%@MM_XVMC_LIB@%${XVMC_LIB}%" /etc/X11/XvMCConfig
            ;;
        nvidia)
            /usr/bin/test "${MM_VIDEO_DEINTERLACER}"  = "auto" && MM_VIDEO_DEINTERLACER='bob'
            /usr/bin/test "${MM_VIDEO_MPEG2_DECODER}" = "auto" && MM_VIDEO_MPEG2_DECODER='ffmpeg'
            XVMC_LIB='/usr/lib/nvidia/libXvMCNVIDIA.so.1'         && \
                /usr/bin/test -e ${XVMC_LIB}                      && \
                /bin/sed -i "s%@MM_XVMC_LIB@%${XVMC_LIB}%" /etc/X11/XvMCConfig
            XVMC_LIB='/usr/lib/nvidia/libXvMCNVIDIA_dynamic.so.1' && \
                /usr/bin/test -e ${XVMC_LIB}                      && \
                /bin/sed -i "s%@MM_XVMC_LIB@%${XVMC_LIB}%" /etc/X11/XvMCConfig
            ;;
        radeon)
            /usr/bin/test "${MM_VIDEO_DEINTERLACER}"  = "auto" && MM_VIDEO_DEINTERLACER='bob'
            /usr/bin/test "${MM_VIDEO_MPEG2_DECODER}" = "auto" && MM_VIDEO_MPEG2_DECODER='ffmpeg'
            ;;
        sis)
            /usr/bin/test "${MM_VIDEO_DEINTERLACER}"  = "auto" && MM_VIDEO_DEINTERLACER='bob'
            /usr/bin/test "${MM_VIDEO_MPEG2_DECODER}" = "auto" && MM_VIDEO_MPEG2_DECODER='ffmpeg'
            ;;
        openchrome)
            /usr/bin/test "${MM_VIDEO_DEINTERLACER}"  = "auto" && MM_VIDEO_DEINTERLACER='bob'
            /usr/bin/test "${MM_VIDEO_MPEG2_DECODER}" = "auto" && MM_VIDEO_MPEG2_DECODER='xvmc-vld'
            XVMC_LIB='/usr/lib/libchromeXvMC.so.1' && \
                /usr/bin/test -e ${XVMC_LIB}       && \
                /bin/sed -i "s%@MM_XVMC_LIB@%${XVMC_LIB}%" /etc/X11/XvMCConfig
            mm_mythdb_settings_set "UseChromaKeyOSD" "1"
            ;;
        vmware)
            /usr/bin/test "${MM_VIDEO_DEINTERLACER}"  = "auto" && MM_VIDEO_DEINTERLACER='bob'
            /usr/bin/test "${MM_VIDEO_MPEG2_DECODER}" = "auto" && MM_VIDEO_MPEG2_DECODER='ffmpeg'
            ;;
    esac
    /bin/sed -i "s%@MM_XVMC_LIB@%%" /etc/X11/XvMCConfig

    if ( /usr/bin/test ${MM_VERSION_MYTH_BINARY_MAJOR} -ge  1    ) || \
       ( /usr/bin/test ${MM_VERSION_MYTH_BINARY_MAJOR} -eq  0 &&      \
         /usr/bin/test ${MM_VERSION_MYTH_BINARY_MINOR} -ge 21    ) ; then
        if /usr/bin/test -n "${MM_VIDEO_PLAYBACK_PROFILE}" ; then
            pref_max_cpus=`cat /proc/cpuinfo | grep -c '^processor[[:cntrl:]]*:'`
            pref_cmp0='> 0 0'
            pref_cmp1=''
            pref_decoder=''
            pref_videorenderer=''
            pref_osdrenderer=''
            pref_osdfade=''
            case "${MM_VIDEO_MPEG2_DECODER}" in
                ffmpeg)
                    pref_decoder='ffmpeg'
                    pref_videorenderer='xv-blit'
                    pref_osdrenderer='softblend'
                    pref_osdfade='0'
                    ;;
                libmpeg2)
                    pref_decoder='libmpeg2'
                    pref_videorenderer='xv-blit'
                    pref_osdrenderer='softblend'
                    pref_osdfade='0'
                    ;;
                xvmc)
                    pref_decoder='xvmc'
                    pref_videorenderer='xvmc-blit'
                    pref_osdrenderer='ia44blend'
                    pref_osdfade='0'
                    ;;
                xvmc-vld)
                    pref_decoder='xvmc-vld'
                    pref_videorenderer='xvmc-blit'
                    pref_osdrenderer='ia44blend'
                    pref_osdfade='0'
                    ;;
                *)
                    mm_message_output err "error: something is very wrong in the 'video' init script."
                    exit 1
                    ;;
            esac
            pref_deint0=''
            pref_deint1=''
            pref_filters=''
            case "${MM_VIDEO_DEINTERLACER}" in
                none)
                    pref_deint0='none'
                    pref_deint1='none'
                    pref_filters=''
                    ;;
                bob)
                    pref_deint0='bobdeint'
                    pref_deint1='none'
                    pref_filters=''
                    ;;
                kernel)
                    pref_deint0='kerneldeint'
                    pref_deint1='none'
                    pref_filters=''
                    ;;
                linear-blend)
                    pref_deint0='linearblend'
                    pref_deint1='none'
                    pref_filters=''
                    ;;
                one-field)
                    pref_deint0='onefield'
                    pref_deint1='none'
                    pref_filters=''
                    ;;
                *)
                    mm_message_output err "error: something is very wrong in the 'video' init script."
                    exit 1
                    ;;
            esac
            hostname=`/bin/hostname`
            profilegroupid=
            if /usr/bin/test -n "${hostname}" ; then
                profilegroupid=`mm_mythdb_get \
                    "SELECT profilegroupid \
                     FROM displayprofilegroups \
                     WHERE name=\"MiniMyth\" \
                     AND hostname=\"${hostname}\" \
                    ;" | grep -v 'profilegroupid'`
            fi
            profileid=
            if /usr/bin/test -n "${profilegroupid}" ; then
                profileid=`mm_mythdb_get \
                    "SELECT profileid \
                     FROM displayprofiles \
                     WHERE profilegroupid=\"${profilegroupid}\" \
                     AND value=\"pref_priority\" \
                     AND data=\"1\" \
                    ;" | grep -v 'profileid'`
            fi
            if /usr/bin/test -n "${profilegroupid}" ; then
                mm_mythdb_set \
                    "DELETE FROM displayprofiles \
                    WHERE profilegroupid=\"${profilegroupid}\" ; "
            fi
            if /usr/bin/test -n "${profilegroupid}" && \
               /usr/bin/test -n "${profileid}"      ; then
                mm_mythdb_set \
                    "INSERT INTO displayprofiles SET profilegroupid=\"${profilegroupid}\", profileid=\"${profileid}\", \
                     value=\"pref_priority\", data=\"1\" ; "
                mm_mythdb_set \
                    "INSERT INTO displayprofiles SET profilegroupid=\"${profilegroupid}\", profileid=\"${profileid}\", \
                     value=\"pref_cmp0\", data=\"${pref_cmp0}\" ; "
                mm_mythdb_set \
                    "INSERT INTO displayprofiles SET profilegroupid=\"${profilegroupid}\", profileid=\"${profileid}\", \
                     value=\"pref_cmp1\", data=\"${pref_cmp1}\" ; "
                mm_mythdb_set \
                    "INSERT INTO displayprofiles SET profilegroupid=\"${profilegroupid}\", profileid=\"${profileid}\", \
                     value=\"pref_max_cpus\", data=\"${pref_max_cpus}\" ; "
                mm_mythdb_set \
                    "INSERT INTO displayprofiles SET profilegroupid=\"${profilegroupid}\", profileid=\"${profileid}\", \
                     value=\"pref_decoder\", data=\"${pref_decoder}\" ; "
                mm_mythdb_set \
                    "INSERT INTO displayprofiles SET profilegroupid=\"${profilegroupid}\", profileid=\"${profileid}\", \
                     value=\"pref_videorenderer\", data=\"${pref_videorenderer}\" ; "
                mm_mythdb_set \
                    "INSERT INTO displayprofiles SET profilegroupid=\"${profilegroupid}\", profileid=\"${profileid}\", \
                     value=\"pref_osdrenderer\", data=\"${pref_osdrenderer}\" ; "
                mm_mythdb_set \
                    "INSERT INTO displayprofiles SET profilegroupid=\"${profilegroupid}\", profileid=\"${profileid}\", \
                     value=\"pref_osdfade\", data=\"${pref_osdfade}\" ; "
                mm_mythdb_set \
                    "INSERT INTO displayprofiles SET profilegroupid=\"${profilegroupid}\", profileid=\"${profileid}\", \
                     value=\"pref_deint0\", data=\"${pref_deint0}\" ; "
                mm_mythdb_set \
                    "INSERT INTO displayprofiles SET profilegroupid=\"${profilegroupid}\", profileid=\"${profileid}\", \
                     value=\"pref_deint1\", data=\"${pref_deint1}\" ; "
                mm_mythdb_set \
                    "INSERT INTO displayprofiles SET profilegroupid=\"${profilegroupid}\", profileid=\"${profileid}\",
                     value=\"pref_filters\", data=\"${pref_filters}\" ; "
            fi
            mm_mythdb_settings_set DefaultVideoPlaybackProfile "${MM_VIDEO_PLAYBACK_PROFILE}"
        fi
    else
        case "${MM_VIDEO_MPEG2_DECODER}" in
            ffmpeg)
                mm_mythdb_settings_set PreferredMPEG2Decoder "${MM_VIDEO_MPEG2_DECODER}"
                ;;
            libmpeg2)
                mm_mythdb_settings_set PreferredMPEG2Decoder "${MM_VIDEO_MPEG2_DECODER}"
                ;;
            xvmc)
                mm_mythdb_settings_set PreferredMPEG2Decoder "${MM_VIDEO_MPEG2_DECODER}"
                ;;
            xvmc-vld)
                mm_mythdb_settings_set PreferredMPEG2Decoder "${MM_VIDEO_MPEG2_DECODER}"
                ;;
            *)
                mm_message_output err "error: something is very wrong in the 'video' init script."
                exit 1
                ;;
        esac
        case "${MM_VIDEO_DEINTERLACER}" in
            none)
                mm_mythdb_settings_set Deinterlace 0
                ;;
            bob)
                mm_mythdb_settings_set Deinterlace 1
                mm_mythdb_settings_set DeinterlaceFilter "bobdeint"
                ;;
            kernel)
                mm_mythdb_settings_set Deinterlace 1
                mm_mythdb_settings_set DeinterlaceFilter "kerneldeint"
                ;;
            linear-blend)
                mm_mythdb_settings_set Deinterlace 1
                mm_mythdb_settings_set DeinterlaceFilter "linearblend"
                ;;
            one-field)
                mm_mythdb_settings_set Deinterlace 1
                mm_mythdb_settings_set DeinterlaceFilter "onefield"
                ;;
            *)
                mm_message_output err "error: something is very wrong in the 'video' init script."
                exit 1
                ;;
        esac
    fi

    case "${MM_VIDEO_MPEG2_DECODER}" in
        ffmpeg)
            /bin/sed -i "s%@VIDEO_DRIVER@%xv%"   /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_TRUE@%\#%"      /home/minimyth/.mplayer/config
            /bin/sed -i "s%@XVMC_FALSE@%%"       /home/minimyth/.mplayer/config
            ;;
        libmpeg2)
            /bin/sed -i "s%@VIDEO_DRIVER@%xv%"   /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_TRUE@%\#%"      /home/minimyth/.mplayer/config
            /bin/sed -i "s%@XVMC_FALSE@%%"       /home/minimyth/.mplayer/config
            ;;
        xvmc)
            /bin/sed -i "s%@VIDEO_DRIVER@%xvmc%" /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_TRUE@%%"        /home/minimyth/.mplayer/config
            /bin/sed -i "s%@XVMC_FALSE@%\#%"     /home/minimyth/.mplayer/config
            ;;
        xvmc-vld)
            /bin/sed -i "s%@VIDEO_DRIVER@%xxmc%" /home/minimyth/.xine/config
            /bin/sed -i "s%@XVMC_TRUE@%%"        /home/minimyth/.mplayer/config
            /bin/sed -i "s%@XVMC_FALSE@%\#%"     /home/minimyth/.mplayer/config
            ;;
        *)
            mm_message_output err "error: something is very wrong in the 'video' init script."
            exit 1
            ;;
    esac

    case "${MM_VIDEO_DEINTERLACER}" in
        none)
            mm_mythdb_settings_set Deinterlace 0
            /bin/sed -i "s%@DEINTERLACE_BY_DEFAULT@%0%"                     /home/minimyth/.xine/config
            /bin/sed -i "s%@DEINTERLACE_PLUGIN@%none%"                      /home/minimyth/.xine/config
            /bin/sed -i "s%@BOBDEINT@%%"                                    /home/minimyth/.mplayer/config
            ;;
        bob)
            mm_mythdb_settings_set Deinterlace 1
            mm_mythdb_settings_set DeinterlaceFilter "bobdeint"
            /bin/sed -i "s%@DEINTERLACE_BY_DEFAULT@%1%"                     /home/minimyth/.xine/config
            /bin/sed -i "s%@DEINTERLACE_PLUGIN@%tvtime:method=ScalerBob%"   /home/minimyth/.xine/config
            /bin/sed -i "s%@BOBDEINT@%:bobdeint%"                           /home/minimyth/.mplayer/config
            ;;
        kernel)
            mm_mythdb_settings_set Deinterlace 1
            mm_mythdb_settings_set DeinterlaceFilter "kerneldeint"
            /bin/sed -i "s%@DEINTERLACE_BY_DEFAULT@%1%"                     /home/minimyth/.xine/config
            /bin/sed -i "s%@DEINTERLACE_PLUGIN@%tvtime:method=LinearBlend%" /home/minimyth/.xine/config
            /bin/sed -i "s%@BOBDEINT@%%"                                    /home/minimyth/.mplayer/config
            ;;
        linear-blend)
            mm_mythdb_settings_set Deinterlace 1
            mm_mythdb_settings_set DeinterlaceFilter "linearblend"
            /bin/sed -i "s%@DEINTERLACE_BY_DEFAULT@%1%"                     /home/minimyth/.xine/config
            /bin/sed -i "s%@DEINTERLACE_PLUGIN@%tvtime:method=LinearBlend%" /home/minimyth/.xine/config
            /bin/sed -i "s%@BOBDEINT@%%"                                    /home/minimyth/.mplayer/config
            ;;
        one-field)
            mm_mythdb_settings_set Deinterlace 1
            mm_mythdb_settings_set DeinterlaceFilter "onefield"
            /bin/sed -i "s%@DEINTERLACE_BY_DEFAULT@%1%"                     /home/minimyth/.xine/config
            /bin/sed -i "s%@DEINTERLACE_PLUGIN@%tvtime:method=LinearBlend%" /home/minimyth/.xine/config
            /bin/sed -i "s%@BOBDEINT@%%"                                    /home/minimyth/.mplayer/config
            ;;
        *)
            mm_message_output err "error: something is very wrong in the 'video' init script."
            exit 1
            ;;
    esac

    if   /usr/bin/test "${MM_VIDEO_ASPECT_RATIO}" = "4:3"   ; then
        /bin/sed -i "s%@MONITORASPECT@%4:3%"   /home/minimyth/.mplayer/config
    elif /usr/bin/test "${MM_VIDEO_ASPECT_RATIO}" = "16:9"  ; then
        /bin/sed -i "s%@MONITORASPECT@%16:9%"  /home/minimyth/.mplayer/config
    elif /usr/bin/test "${MM_VIDEO_ASPECT_RATIO}" = "16:10" ; then
        /bin/sed -i "s%@MONITORASPECT@%16:10%" /home/minimyth/.mplayer/config
    else
        mm_message_output err "error: something is very wrong in the 'video' init script."
        exit 1
    fi

    if   /usr/bin/test "${MM_VIDEO_RESIZE_ENABLED}" = "no"  ; then
        mm_mythdb_settings_set    'UseVideoModes' '0'

        mm_mythdb_settings_delete 'GuiVidModeResolution'
        mm_mythdb_settings_delete 'TvVidModeResolution'
        mm_mythdb_settings_delete 'TVVidModeRefreshRate'
        mm_mythdb_settings_delete 'TvVidModeForceAspect'

        mm_mythdb_settings_delete 'VidModeWidth0'
        mm_mythdb_settings_delete 'VidModeHeight0'
        mm_mythdb_settings_delete 'TVVidModeResolution0'
        mm_mythdb_settings_delete 'TVVidModeRefreshRate0'
        mm_mythdb_settings_delete 'TVVidModeForceAspect0'

        mm_mythdb_settings_delete 'VidModeWidth1'
        mm_mythdb_settings_delete 'VidModeHeight1'
        mm_mythdb_settings_delete 'TVVidModeResolution1'
        mm_mythdb_settings_delete 'TVVidModeRefreshRate1'
        mm_mythdb_settings_delete 'TVVidModeForceAspect1'

        mm_mythdb_settings_delete 'VidModeWidth2'
        mm_mythdb_settings_delete 'VidModeHeight2'
        mm_mythdb_settings_delete 'TVVidModeResolution2'
        mm_mythdb_settings_delete 'TVVidModeRefreshRate2'
        mm_mythdb_settings_delete 'TVVidModeForceAspect2'
    elif /usr/bin/test "${MM_VIDEO_RESIZE_ENABLED}" = "yes" ; then
        mm_mythdb_settings_set 'GuiSizeForTV' '0'
        mm_mythdb_settings_set 'UseVideoModes' '1'

        X_RESOLUTION=`/bin/echo ${MM_X_MODE}      | /bin/sed -e 's%^\([0-9][0-9]*\)[Xx]\([0-9][0-9]*\).*%\1x\2%'`
        X_RESOLUTION_X=`/bin/echo ${X_RESOLUTION} | /bin/sed -e 's%^\([0-9][0-9]*\)x\([0-9][0-9]*\)$%\1%'`
        X_RESOLUTION_Y=`/bin/echo ${X_RESOLUTION} | /bin/sed -e 's%^\([0-9][0-9]*\)x\([0-9][0-9]*\)$%\2%'`
        mm_mythdb_settings_set 'GuiVidModeResolution' "${X_RESOLUTION}"
        mm_mythdb_settings_set 'TvVidModeResolution'  "${X_RESOLUTION}"
        mm_mythdb_settings_set 'TVVidModeRefreshRate' '0'
        mm_mythdb_settings_set 'TvVidModeForceAspect' '0.0'
        if /usr/bin/test ! "${MM_X_MODE_0}" = "none" ; then
            X_RESOLUTION=`/bin/echo ${MM_X_MODE_0}    | /bin/sed -e 's%^\([0-9][0-9]*\)[Xx]\([0-9][0-9]*\).*%\1x\2%'`
            X_RESOLUTION_X=`/bin/echo ${X_RESOLUTION} | /bin/sed -e 's%^\([0-9][0-9]*\)x\([0-9][0-9]*\)$%\1%'`
            X_RESOLUTION_Y=`/bin/echo ${X_RESOLUTION} | /bin/sed -e 's%^\([0-9][0-9]*\)x\([0-9][0-9]*\)$%\2%'`
            mm_mythdb_settings_set 'VidModeWidth0'         "${X_RESOLUTION_X}"
            mm_mythdb_settings_set 'VidModeHeight0'        "${X_RESOLUTION_Y}"
            mm_mythdb_settings_set 'TVVidModeResolution0'  "${X_RESOLUTION}"
            mm_mythdb_settings_set 'TVVidModeRefreshRate0' '0'
            mm_mythdb_settings_set 'TVVidModeForceAspect0' '0.0'
        else
            mm_mythdb_settings_delete 'VidModeWidth0'
            mm_mythdb_settings_delete 'VidModeHeight0'
            mm_mythdb_settings_delete 'TVVidModeResolution0'
            mm_mythdb_settings_delete 'TVVidModeRefreshRate0'
            mm_mythdb_settings_delete 'TVVidModeForceAspect0'
        fi
        if /usr/bin/test ! "${MM_X_MODE_1}" = "none" ; then
            X_RESOLUTION=`/bin/echo ${MM_X_MODE_1}    | /bin/sed -e 's%^\([0-9][0-9]*\)[Xx]\([0-9][0-9]*\).*%\1x\2%'`
            X_RESOLUTION_X=`/bin/echo ${X_RESOLUTION} | /bin/sed -e 's%^\([0-9][0-9]*\)x\([0-9][0-9]*\)$%\1%'`
            X_RESOLUTION_Y=`/bin/echo ${X_RESOLUTION} | /bin/sed -e 's%^\([0-9][0-9]*\)x\([0-9][0-9]*\)$%\2%'`
            mm_mythdb_settings_set 'VidModeWidth1'         "${X_RESOLUTION_X}"
            mm_mythdb_settings_set 'VidModeHeight1'        "${X_RESOLUTION_Y}"
            mm_mythdb_settings_set 'TVVidModeResolution1'  "${X_RESOLUTION}"
            mm_mythdb_settings_set 'TVVidModeRefreshRate2' '0'
            mm_mythdb_settings_set 'TVVidModeForceAspect1' '0.0'
        else
            mm_mythdb_settings_delete 'VidModeWidth1'
            mm_mythdb_settings_delete 'VidModeHeight1'
            mm_mythdb_settings_delete 'TVVidModeResolution1'
            mm_mythdb_settings_delete 'TVVidModeRefreshRate1'
            mm_mythdb_settings_delete 'TVVidModeForceAspect1'
        fi
        if /usr/bin/test ! "${MM_X_MODE_2}" = "none" ; then
            X_RESOLUTION=`/bin/echo ${MM_X_MODE_2}    | /bin/sed -e 's%^\([0-9][0-9]*\)[Xx]\([0-9][0-9]*\).*%\1x\2%'`
            X_RESOLUTION_X=`/bin/echo ${X_RESOLUTION} | /bin/sed -e 's%^\([0-9][0-9]*\)x\([0-9][0-9]*\)$%\1%'`
            X_RESOLUTION_Y=`/bin/echo ${X_RESOLUTION} | /bin/sed -e 's%^\([0-9][0-9]*\)x\([0-9][0-9]*\)$%\2%'`
            mm_mythdb_settings_set 'VidModeWidth2'         "${X_RESOLUTION_X}"
            mm_mythdb_settings_set 'VidModeHeight2'        "${X_RESOLUTION_Y}"
            mm_mythdb_settings_set 'TVVidModeResolution2'  "${X_RESOLUTION}"
            mm_mythdb_settings_set 'TVVidModeRefreshRate2' '0'
            mm_mythdb_settings_set 'TVVidModeForceAspect2' '0.0'
        else
            mm_mythdb_settings_delete 'VidModeWidth2'
            mm_mythdb_settings_delete 'VidModeHeight2'
            mm_mythdb_settings_delete 'TVVidModeResolution2'
            mm_mythdb_settings_delete 'TVVidModeRefreshRate2'
            mm_mythdb_settings_delete 'TVVidModeForceAspect2'
        fi
    fi

    # Configure CPU features.
    if /usr/bin/test -e /usr/bin/vlc ; then
        cpu_flags=`/bin/cat /proc/cpuinfo \
             | /bin/sed -e 's%[[:cntrl:]]% %g' \
             | /bin/grep -e '^flags *:' \
             | /bin/sed -e 's%^flags *:%%' -e 's%  *% %g' -e 's%^ %%' -e 's% $%%'`
        if /bin/echo " ${cpu_flags} " | /bin/grep -q ' 3dnow '  > /dev/null 2>&1 ; then
            /bin/sed -e 's%@MM_VLC_VLCRC_3DN@%1%g'    -i /home/minimyth/.config/vlc/vlcrc
        else
            /bin/sed -e 's%@MM_VLC_VLCRC_3DN@%0%g'    -i /home/minimyth/.config/vlc/vlcrc
        fi
        if /bin/echo " ${cpu_flags} " | /bin/grep -q ' mmx '    > /dev/null 2>&1 ; then
            /bin/sed -e 's%@MM_VLC_VLCRC_MMX@%1%g'    -i /home/minimyth/.config/vlc/vlcrc
        else
            /bin/sed -e 's%@MM_VLC_VLCRC_MMX@%0%g'    -i /home/minimyth/.config/vlc/vlcrc
        fi
        if /bin/echo " ${cpu_flags} " | /bin/grep -q ' mmxext ' > /dev/null 2>&1 ; then
            /bin/sed -e 's%@MM_VLC_VLCRC_MMXEXT@%1%g' -i /home/minimyth/.config/vlc/vlcrc
        else
            /bin/sed -e 's%@MM_VLC_VLCRC_MMXEXT@%0%g' -i /home/minimyth/.config/vlc/vlcrc
        fi
        if /bin/echo " ${cpu_flags} " | /bin/grep -q ' sse '    > /dev/null 2>&1 ; then
            /bin/sed -e 's%@MM_VLC_VLCRC_SSE@%1%g'    -i /home/minimyth/.config/vlc/vlcrc
        else
            /bin/sed -e 's%@MM_VLC_VLCRC_SSE@%0%g'    -i /home/minimyth/.config/vlc/vlcrc
        fi
        if /bin/echo " ${cpu_flags} " | /bin/grep -q ' sse2 '   > /dev/null 2>&1 ; then
            /bin/sed -e 's%@MM_VLC_VLCRC_SSE2@%1%g'   -i /home/minimyth/.config/vlc/vlcrc
        else
            /bin/sed -e 's%@MM_VLC_VLCRC_SSE2@%0%g'   -i /home/minimyth/.config/vlc/vlcrc
        fi
    fi

    return 0
}

stop() {
    return 0
}

case $1 in
    start) start ;;
    stop)  stop  ;;
esac

exit 0
